### ISSUE TITLE
incorrect help text for stripmdoc compiler arg

### ISSUE THREAD

**Issue by mbylstra** [grame-cncm/faust#10]
The help says the name of the arg is `stripdoc`, but it is actually `stripmdoc`

see 
https://github.com/grame-cncm/faust/blob/master-dev/compiler/main.cpp#L486
and 
https://github.com/grame-cncm/faust/blob/master-dev/compiler/main.cpp#L373

I've never actually used this function but I noticed the discrepancy when I was trying to understand the arg parsing code.

**Comment by sletz** [comment]
Fixed.
