### ISSUE TITLE
Rust's F{32,64}::rem_euclid behaves differently from C/C++ remainder

### ISSUE THREAD

**Issue by nuchi** [grame-cncm/faust#1000]
The faust primitive `remainder` is transformed to `std::remainder` in the C++ backend, and `F{32,64}::rem_euclid` in the rust backend. However [`std::remainder`](https://en.cppreference.com/w/cpp/numeric/math/remainder) computes different values than [`rem_euclid`](https://doc.rust-lang.org/std/primitive.f32.html#method.rem_euclid).

This is not urgent/important for me, I just happened to discover it while running the impulse tests. `tests/impulse-tests/dsp/math.dsp` computes `remainder(9.2, 2.0)` which is -0.8 in C++, but 1.2 in rust.

**Comment by sletz** [comment]
Thanks, do you have a fix for that ?

**Comment by nuchi** [comment]
I don't have a fix, nor do I particularly need one. I'm not a rust user, nor am I using `remainder` for anything. I just happened to stumble on this and thought I should report it in case any rust users run across mysterious errors and search for it here :)

It looks like the jax backend has a similar issue (there's a "todo" comment next to the remainder line in jax_instructions.hh) so maybe a similar solution would work for rust (define a custom remainder in the architecture file).

But I expect it can wait until a contributor shows up who cares more about rust than I do.

**Comment by DBraun** [comment]
Thanks for the reminder about JAX. I missed the situation in which the second argument is negative... But I feel better about the new PR here https://github.com/grame-cncm/faust/pull/1001.

It's funny how remainder means something different in each library: `jax.numpy.remainder` is **not** `std::remainder`.

**Comment by sletz** [comment]
Done in https://github.com/grame-cncm/faust/commit/3fdc3d57dc00b04113168a96232cee9b78ccef13
following this discussion:  https://users.rust-lang.org/t/analog-of-c-std-remainder/59670
