### ISSUE TITLE
[Android] Custom input/output support

### ISSUE THREAD

**Issue by eleventigers** [grame-cncm/faust#1009]
I am wondering if the sources generated with faust2api (android) provide a way to feed in custom sample frame buffers and get output buffers? I am developing an application where I would like to apply audio processing on existing music player (ExoPlayer to be specific) which allows to insert custom audio processors and having a Faust based processor would be great but I am not sure if I can avoid the Oboe based processing pipeline?

**Comment by sletz** [comment]
Nothing for that, sorry.
