### ISSUE TITLE
int64_t has not been decalred

### ISSUE THREAD

**Issue by ddgg-el** [grame-cncm/faust#1014]
Hello!

I am having problem compiling `faust` on MSYS2 MinGW64.
```
In file included from faust/compiler/interval/interval_algebra.hh:5,
                from faust/compiler/signals/interval.hh:30:
faust/compiler/FaustAlgebra/FaustAlgebra.hh:54:24: error: 'int64_t' has not been declared
  54 |     virtual T Int64Num(int64_t x)         = 0;
     |                        ^~~~~~~
faust/compiler/interval/interval_algebra.hh:17:23: error: 'int64_t' has not been declared
  17 |     interval Int64Num(int64_t x) override;
     |                       ^~~~~~~
```
Is there any dependency that I am not aware of?
Thank you!

**Comment by sletz** [comment]
Probably a missing header: that to add` #include <cstdint> `

**Comment by ddgg-el** [comment]
Including `cstdint`  I can compile `faust` but when running 
```
./build/bin/faust --version
```
results in a `Segmentation fault`.

**Comment by sletz** [comment]
Any log there ?

**Comment by ddgg-el** [comment]
no but I'll keep investigating...I think that it is something related to this installation of MinGW. On another computer it works flawless. I don't even have to add the "missing" header

**Comment by sletz** [comment]
Does this commit few the crash issue https://github.com/grame-cncm/faust/commit/08cf4e905fbcec5a2cd454705f317aff87e9b7cb ?

**Comment by sletz** [comment]
Should be fixed by https://github.com/grame-cncm/faust/commit/08cf4e905fbcec5a2cd454705f317aff87e9b7cb.
