### ISSUE TITLE
License compatibility for binary and source distribution of Csound opcodes

### ISSUE THREAD

**Issue by gogins** [grame-cncm/faust#103]
Currently, the Faust code is GPL version 3. Csound is LGPL v2.1 with an exception for some features to allow use of the VST2 SDK. 

Please make an exception to the Faust license -- but only, of course, if this is agreeable to the Faust copyright holders and developers -- to allow Faust-generated plugins to be dynamically loaded by "open source" hosts, and to allow Csound plugin opcodes generated by Faust to be distributed with Csound releases both as C++ source code and as binaries.

This of course does not apply to any source code or binaries of the Faust development environment, but only to user-generated plugins.

**Comment by kritzikratzi** [comment]
as far as i can tell, in the generated code you can find this exception to the GPL3: 

> EXCEPTION : As a special exception, you may create a larger work
>  that contains this FAUST architecture section and distribute
>  that work under terms of your choice, so long as this FAUST
>  architecture section is not modified.

so as long as you don't modify the architecture section of the generated plugins, and as long as you make it part of a "larger work" (no problem for csound), this exception seems to cover it. at least i think it's fair to say it is covered by the intent of the exception. 

---

Maybe it's more complicated though. I'm not a lawyer, but these things are fun to think about: 

Somehow it creates a situation where the resulting code can be (L)GPL2 until you go ahead and modify one character in the architecture section, which will revoke the special exception, which will revoke the relicensing to (L)GPL2 from the file. And this really seems fundamentally incompatible with the (L)GPL2 given you're supposed to have a right to modify, so you couldn't apply the special exception in the first place. In which case the special exception is sortof impossible to use for anyone wanting to distribute sources (binaries are no problem). 


Some clarification about the license would be nice. I really wonder why the "as long as not modified" part is in there.

**Comment by agraef** [comment]
Faust itself (the compiler) is GPL code, and that's not likely to change. Most of the architectures are under the LGPL (some under the BSDL), though.

The intention of using the LGPL for architectures seems to be to make it possible to publish Faust-generated plugins under whatever license you choose, subject to the constraint (in the LGPL case) that substantial code changes to the architecture are made available in some way. I'm no licensing expert, though, so I'm not sure whether the LGPL is the right license for that, but that's the current situation.
