### ISSUE TITLE
oscillator.lib : 136 : ERROR : undefined symbol : ma

### ISSUE THREAD

**Issue by yellowpepero** [grame-cncm/faust#1030]
stdfaust=library("stdfaust.lib");
music=library("music.lib");
oscil=library("oscillator.lib");
effect=library("effect.lib");

bypass=checkbox("Bypass");
vol=hslider("Volume [unit:dB]", -100, -100, 12, 0.1);

vocoder=effect.vocoder(bands, attack, release, bandwidth, input, wav) with {
    vocoderGroup(x)=hgroup("VOCODER", x);

    bands=8;
    attack=vocoderGroup(hslider("[0] Attack [style:knob]", 0, 0, 3, 0.01));
    release=vocoderGroup(hslider("[1] Release [styel:knob]", 0, 0, 3, 0.01));
    bandwidth=vocoderGroup(hslider("[2] Bandwidth [style:knob]", 0.1, 0.1, 2, 0.01));
    input=_;
    wav=select3(table, sine, sawtooth, noise) with {
        table=vocoderGroup(nentry("[4] Waveform", 0, 0, 2, 1));
        sine=music.osc(freq);
        sawtooth=oscil.sawtooth(freq);
        noise=music.noise;
        freq=vocoderGroup(hslider("[3] Frequency [style:knob]", 400, 0, 5000, 1));

        };
};

process=_ <: bypass * _, (1 - bypass) * vocoder :> _ * music.db2linear(vol);

  

BUT I have this Error 
oscillator.lib : 136 : ERROR : undefined symbol : ma
How can I fix it? 
Please help me..

**Comment by sletz** [comment]
I suggest you read some examples first:  https://faustdoc.grame.fr/workshops/2020-04-10-faust-101/ , https://faustdoc.grame.fr/manual/syntax/
