### ISSUE TITLE
JUCE getBusesProperties call to discreteChannels() causes debug errors

### ISSUE THREAD

**Issue by skraninger** [grame-cncm/faust#1031]
The architecture file juce-plugin.ccp definition of: FaustPlugInAudioProcessor::getBusesProperties()
uses calls to discreteChannels() to set the number of input and output channels.
This causes errors to be raised when debugging a VST3 the because discreteChannels() just sets a channel count and does not provide a discrete (left, right, mid, ...) channel layout specification that the VST3 requires (the function layout.isDiscreteLayout() returns false).
This error does not cause a crash when starting the VST3 (when not debugging), but seems to cause some excecution issues that appear if the VST3 is running for a long time and the UI is active changing values.
To correct this problem, replace the call to discreteChannels() with cannonicalChannelSet().
This will provide a correct channel set for up to 8 channels and solves the issue for VST3s.

**Comment by sletz** [comment]
Thanks, can you prepare a PR for that ?

**Comment by sletz** [comment]
BTW, what happens when they are more the 8 channels in the Faust DSP code ? Should we stay with` discreteChannels()` there ?

**Comment by skraninger** [comment]
cannonicalChannelSet(n) actually returns discreteChannels(n) when n > 8.  I am going to look into this some more and ask some additional questions in the JUCE forums.  There were some forum posts on Steinbergs forum about VST3 channel limitations and how they caused some issues with multi-channel systems (asking for changes).  I don't understand why discreteChannels() should raise an error, it seems like it should function properly.

**Comment by sletz** [comment]
OK, great, so then can you prepare a PR? This would be of great help ! Thanks.

**Comment by skraninger** [comment]
Q: Is there a simple function like canonicalChannelSet(n) that will return a valid VST3 channel layout up to n=64? I looked at the functions available, and it was not clear what to use?

A: No, such a function can’t really be implemented. VST3 only defines 61 different speaker types, so it’s not possible to define layouts with 62+ channels. Due to the way VST3 speaker layouts work, some channel layouts with fewer than 61 channels would have conflicting semantics and should be avoided, e.g. a channel layout with 37 channels would have to include both ambisonic and non-ambisonic speaker types, and most hosts won’t know how to work with such layouts.
If you need discrete channel layouts and/or arbitrary channel counts in a VST3 plugin, I’d recommend contacting Steinberg and asking whether they’d consider adding this to the VST3 specification.

ALSO

I have never prepared a PR.  I am happy to assist, but need a bit of direction as to how to do a PR for this project.
Thanks

**Comment by sletz** [comment]
Do you have a Faust fork when your code is implemented ?

**Comment by skraninger** [comment]
I pulled from Git Current Branch master-dev and made the changes.  I did not create a fork yet.
When I select the option to create a fork, there is an option to contribute to the grame-faust repository. At this point I cancelled. Should I contiune? Any specific intructions?

**Comment by sletz** [comment]
Yes just try to "contribute to the grame-faust ",and see what happens (hopefully a Pull Request will be created and so on...)

**Comment by sletz** [comment]
Where is your updated master-dev branch ?

**Comment by skraninger** [comment]
It looks like it was called:
Update juce-plugin.cpp

Comment:
JUCE architecture bus channel changes for VST3 compatibility up to 8
channels. The original code would create errors in debug and only provide 2
channels even when more channels were selected.

by improvoid (e12694bc4)

**Comment by sletz** [comment]
Thanks, done in https://github.com/grame-cncm/faust/commit/fb04f8173e0a5e34c6f29ae456606e92b3b70acc
