### ISSUE TITLE
Faust 2.7.4 stopped working with HISE

### ISSUE THREAD

**Issue by christoph-hart** [grame-cncm/faust#1032]
I've received a few reports of users not being able to use the latest Faust release with HISE. Apparently the 2.7.4 update broke something and now the processing stopped working altogether when loading any faust node in HISE. I debugged the wrapper code and everything looks OK on the HISE side, but no matter what faust code I throw at it, it will not process anything. A few remarks:

- 2.7.2 still works without issues
- the compilation of the faust code is fine, no errors and all parameters are correctly parsed and created.
- it's happening on both Windows and macOS
- both LLVM codegen and interpreter do not work anymore
- I can verify that the HISE wrapper calls the DLL function `faust::dsp::compute()` with properly sized buffers, but the function does not seem to do anything
- the CPU usage does not go up when loading a complex patch, so it's more likely that the processing is bypassed than that the signal gets muted along the way.

Has something changed in the API between 2.7.2 and 2.7.4 that could cause this? I can crawl through the commits between the versions to try to find the culprit, but if you have any clues it would save me a boring afternoon staring at the compiler :)

**Comment by sletz** [comment]
2.7.2 and 2.7.4 are probably wrong: the latest release is 2.74.6, so ?

**Comment by sletz** [comment]
See https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/dsp/dsp.h#L87

**Comment by christoph-hart** [comment]
Sorry, I meant `2.74.6`. `2.72.14` (and every release before) is working.

**Comment by sletz** [comment]
The `dsp` class has changed. I remember HISE maintains its own version ? Which has to be updated I guess.

**Comment by christoph-hart** [comment]
Ah yes, perfect, updating the `dsp.h` file in HISE fixed it. Thanks for the fast reply!

One question about the new `control()` function: from the comment I would assume that it needs to be called before every compute() call, but if I omit it, the parameters are still updated.

BTW, is there a document where you list the changes to the API?

**Comment by sletz** [comment]
`control()` is only generated with the `-ec` option, so nothing special to do if you keep the default options.
