### ISSUE TITLE
2.74.6 segfaults when built with LTO

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#1033]
Hi! :wave: 

After building faust 2.74.6, users on Arch Linux noticed segfaults:
https://gitlab.archlinux.org/archlinux/packaging/packages/faust/-/issues/1

This seems to be fixed by not building with LTO.
We have been building faust with LTO for quite some time now and this seems to be a recent breakage.
Do you maybe have any idea?

**Comment by dvzrv** [comment]
@sletz could you please point to a commit where this is fixed? This repository has nearly 50 branches most of which are very old. It's not really clear where/ whether there is a fix somewhere now. Thanks :pray:

**Comment by sletz** [comment]
AFAICS this is not a Faust problem right ?

**Comment by sletz** [comment]
Sorry I was not reading the https://gitlab.archlinux.org/archlinux/packaging/packages/faust/-/issues/1 issue correctly, so reopened.

**Comment by sletz** [comment]
@dvzrv Possible fix here https://github.com/grame-cncm/faust/tree/gAlgebra-fix1, can you teste and report ?

**Comment by cbix** [comment]
Apparently bb1637c72c8827b1ab3cb3b5d8c37d6c935ffb30 introduced the bug. I can confirm 08cf4e905fbcec5a2cd454705f317aff87e9b7cb fixes it.
