### ISSUE TITLE
Rust: Any way to access 'self' in an ffunction?

### ISSUE THREAD

**Issue by PolyVector** [grame-cncm/faust#1045]
Hiya, I'm trying to add sampling capabilities using a foreign function to an audio plugin that uses the Rust backend:

`readAudioSample = ffunction(float read_audio_sample(float), "", "");`

But I can't see any valid way of declaring it to be called with self, like `self.read_audio_sample()`. I'd like to access sample data without resorting to static variables if that's possible.

**Comment by sletz** [comment]
The `ffunction` primitive has never been worked ou in the Rust backend. Can you provide a minimal test with the currently generated code and the one you would like to have ? Thanks.

**Comment by PolyVector** [comment]
You know, thinking about it more... I wouldn't be able to add member variables to the generated struct to store sampler data, so having a member method wouldn't actually help me here.  Maybe what I'm asking doesn't actually make sense, I'll have to think on this more.

**Comment by sletz** [comment]
What about using the `soundfile` primitive ?

**Comment by PolyVector** [comment]
I don't think soundfile is supported in the Rust backend yet.  Ideally I'd like to be able to call into arbitrary plugin functions from the generated DSP, but to be honest I can't think of a practical use case beyond what soundfile would provide.

If needed I could probably write a Rust macro to add custom functionality to the generated code. I just need to learn how to do that 😄

**Comment by sletz** [comment]
Then if needed `soundfile` would be have to be added sure...
