### ISSUE TITLE
man-page uses en-dash for long-options

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#1051]
currently the `faust` manpage uses an en-dash for long-options: https://github.com/grame-cncm/faust/blob/b498ef5159a0a02a98e92dd3d6998859fae2c8a8/documentation/man/man1/faust.1#L18

with my groff/man, this renders as:

> **-i** **–inline-architecture-files** inline architecture files.

while this does look nice, it prevents the user from being able to copy/paste the flag.

afaict, the correct thing would be to use double-dash (`--`) for long options (e.g. `--inline-architecture-files`).

This can be achieved (i think, I'm not a groff expert), by using `\-\-` instead of ~~`\[en]`~~, like so:

```groff
 \f[B]\-i\f[R] \f[B]\-\-inline\-architecture\-files\f[R] inline 
```

This then renders as:
> **-i** **--inline-architecture-files** inline architecture files.

**Comment by sletz** [comment]
To be fixed here https://github.com/grame-cncm/faust/blob/master-dev/documentation/man/Makefile ?

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/52ccda8a84d627ad7128edabdd889ea280023ed0 and result visible [here](https://github.com/grame-cncm/faust/commit/c223f1ec70837ca4f45e67bcbaaae38e93a62ccc)
