### ISSUE TITLE
Compile error with C export, GCC >= 14.2.x and fastmath (-fm def)

### ISSUE THREAD

**Issue by SpotlightKid** [grame-cncm/faust#1055]
Using the `-fm def` option when exporting to C produces the following error:

    error: initializer element is not constant

This started to appear after I updated GCC to version 14.2.1 (Manjaro, x64-64).

```con
$ LC_ALL=C gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.2.1 20240910 (GCC) 
```

To reproduce:

```sh
#!/bin/sh -x

cat > lpf.dsp <<__EOF__
import("stdfaust.lib");
cutoff = hslider("Cutoff", 15000, 16, 15000, 0.1) : si.smoo;
process = fi.lowpass(2, cutoff);
__EOF__

faust -lang c -a minimal.c -cn faustlpf lpf.dsp > lpf_minimal.c
faust -lang c -a minimal.c -cn faustlpf -fm def lpf.dsp > lpf_minimal_fm.c

LDFLAGS="-lm" make lpf_minimal
LDFLAGS="-lm" make lpf_minimal_fm
```

Output:

```
$ LC_ALL=C ./test.sh
+ cat
+ faust -lang c -a minimal.c -cn faustlpf lpf.dsp
+ faust -lang c -a minimal.c -cn faustlpf -fm def lpf.dsp
+ LDFLAGS=-lm
+ make lpf_minimal
cc   -lm  lpf_minimal.c   -o lpf_minimal
+ LDFLAGS=-lm
+ make lpf_minimal_fm
cc   -lm  lpf_minimal_fm.c   -o lpf_minimal_fm
In file included from lpf_minimal_fm.c:80:
/usr/include/faust/dsp/fastmath.cpp:212:33: error: initializer element is not constant
  212 | static uint32_t log_precision = log2i(fast_log_precision);
      |                                 ^~~~~
/usr/include/faust/dsp/fastmath.cpp:214:33: error: initializer element is not constant
  214 | static uint32_t pow_precision = log2i(fast_pow_precision);
      |                                 ^~~~~
/usr/include/faust/dsp/fastmath.cpp: In function 'fast_log10f':
/usr/include/faust/dsp/fastmath.cpp:244:52: error: expected expression before 'float'
  244 |     return icsi_log(x, log_table, log_precision) / float(M_LN10);
      |                                                    ^~~~~
/usr/include/faust/dsp/fastmath.cpp: In function 'fast_log2f':
/usr/include/faust/dsp/fastmath.cpp:250:52: error: expected expression before 'float'
  250 |     return icsi_log(x, log_table, log_precision) / float(M_LN2);
      |                                                    ^~~~~
make: *** [<builtin>: lpf_minimal_fm] Error 1
```

**Comment by sletz** [comment]
ChatGPT answer, can you try and report ?
https://chatgpt.com/share/66fe3c6c-7060-8013-a2b2-638b7b4ed1e2

**Comment by SpotlightKid** [comment]
The AI tells me:

> Fix: You need to initialize these variables within a function instead of at the global level. > For example:
>
> ```cpp
> static uint32_t log_precision;
> static uint32_t pow_precision;
> 
> void initialize_precisions() {
>    log_precision = log2i(fast_log_precision);
>    pow_precision = log2i(fast_pow_precision);
> }
> ```
>
> Call initialize_precisions() at the start of your program or in the appropriate 
> initialization function.

However, that would mean changing *all* the architecture files, so that they call `initialize_precisions`, when fastmath is used. I don't think this the right solution.

**Comment by sletz** [comment]
Can't you call `initialize_precisions` in the fastmath.cpp file itself ?

**Comment by SpotlightKid** [comment]
No. That makes no sense. `fastmath.cpp` is a file that is included by the architecture files, which just provides alternative implementations of math functions. Where would that call even live. There is no initialization function in there.

**Comment by sletz** [comment]
Done in https://github.com/grame-cncm/faust/commit/c93205ee821357440c2ff2171fe59783e0447d95 can you test and report ? Thanks.

**Comment by SpotlightKid** [comment]
The new version of `fastmath.cpp` doesn't work with export to **C** (perhaps unsurprisingly, given the filename extension).

* The initial `error: initializer element is not constant` persists.
* `#include <stdbool.h>` is missing.
* some functions use `static_cast`, which is C++.

It seems to me that either:

* a version of `fastmath.cpp` for C is needed.
* or the `-fm` option should not be supported for C export and throw an error when used together with `-lang c`.

**Comment by sletz** [comment]
I cannot really test on my side in the general case. Can't you fix it on your side and prepare a PR ? Thanks.

**Comment by SpotlightKid** [comment]
Sorry, I have no idea how. It looks like `fastmath.cpp` is generated? Is there a way to generate a C `fastmath.h` version?

**Comment by sletz** [comment]
No, fastmath.cpp is not generated. You can perfectly modify it until it is usable in C and C++, thanks.

**Comment by SpotlightKid** [comment]
AFAICS, `static` needs to be added to line 35 and 37 of `fastmath.cpp`:

```c++
#ifdef _WIN32
#define EXPORT __declspec(dllexport) __attribute__((always_inline)) static
#else
#define EXPORT __attribute__((visibility("default"))) __attribute__((always_inline)) static
#endif
```

Otherwise, if you might get this linking error:

```
In file included from <...>/lpf.h:44,
                 from <...>/lpf.c:8:
/usr/include/faust/dsp/fastmath.cpp: In function 'computelpf':
/usr/include/faust/dsp/fastmath.cpp:108:14: error: inlining failed in call to 'always_inline' 'fast_tanf': function body can be overwritten at link time
  108 | EXPORT float fast_tanf(float x)
```

**Comment by sletz** [comment]
OK, so with this fix, it compiles for you  GCC >= 14.2.x in C and C++ ?

**Comment by SpotlightKid** [comment]
With the added `static`, yes.

**Comment by sletz** [comment]
Thanks, fixed in https://github.com/grame-cncm/faust/commit/fea73ffdd90ed4ee978933c5967c7ac872f60f21.
