### ISSUE TITLE
-lang rust doesn't generate control function

### ISSUE THREAD

**Issue by crop2000** [grame-cncm/faust#1057]
if faust is used with -ec 
`-ec --external-control separated 'control' and 'compute' functions.`
the calculations that are moved to the control function are not rendered to the output

**Comment by sletz** [comment]
The `-ec ` is not properly implemented in the Rust backend for now. Added this check: https://github.com/grame-cncm/faust/commit/ed1f7bc2fc66752be458ae4adc0b8176fe8878a9.
