### ISSUE TITLE
removing trait impl from rust generator

### ISSUE THREAD

**Issue by crop2000** [grame-cncm/faust#1059]
The current [rust code generation](https://github.com/grame-cncm/faust/tree/master-dev/compiler/generator/rust) has some limitations. The functions associated with the generated struct are wrapped into one trait. The trait defines the interface, but the interface might depend on compile options. For example [-ec](https://github.com/grame-cncm/faust/issues/1057) should be implemented for rust as well. It would break the current trait-interface. So one would need multiple traits. 

But I think the code generation should not define any trait. Rather, the traits should be defined and implemented in the architecture files. I thought about architecture files primarily as files that provide usability scaffolding like [here](https://github.com/Frando/rust-faust/blob/main/faust-build/faust-template.rs). I didn't expect single file programs like in the faust repository. I hope it is enough to provide backward compatible architecture files, like this for the [faust-build crate](https://github.com/crop2000/rust-faust/blob/try_less_traits/faust-build/faust-template.rs).

The change would reduce the complexity of the code generated by rust and give more duties to the architecture files.

I am currently preparing a pr regarding this issue.

**Comment by sletz** [comment]
The general strategy we have for the C/C++ backend and architecture model is needed to put less in the code generation step, and more in the architecture files, since this is more flexible in general. The current Rust code generation has ben developed first in 2017, with little Rust experience at that time, and refine a bit from there. So yes this kind of change is welcome. 

The only thing to be sure is to provide backward compatibility, and possibly have feedback from @obsoleszenz, @plule...etc. form [this contributor list](https://github.com/Frando/rust-faust/graphs/contributors)

**Comment by crop2000** [comment]
There is a limit to backwards compatibility.
If people have a program that has a reference to the trait FaustDsp (not the dsp struct) then the trait implementation is needed and the used architecture file must to be updated. 
This is the case in rust-faust/rust-state crate.
I will update the architecture files rust-faust and faust, for as a reference.

**Comment by crop2000** [comment]
I would favor a cleanup which reduces the generated code to the most necessary ... and provides const rather then functions for get_num_inputs for example.  

but this will be definitely not backward compatible. 

now i am divided between 2 thoughts (but still favor solution 1).

1) because people need to add  the FaustDsp trait implementation to their own architecture files anyway, we should change the generated code to be as simple as possible.

2) because people might use their own architecture files we should keep as much of the current interface in the dsp struct impl so that they only need to remove references to FaustDsp from their code which works well if they haven't depend on the trait anyway.

The difference between 1 and 2 is: for 1 one needs to update the architecture file for 2 one needs to change the code that uses the output of faust ... 2 is slightly easier to reason about if one doesn't understand rust well enough. 

but i think it is possible to write a trait impl that could be copied into a architecure file. then a guideline "please add this code-block to your architecture file for backwards compatibility" is maybe sufficient.

**Comment by crop2000** [comment]
The latest iteration of my propsal introduces a flag to deactivate the generation of the FaustDsp trait. And moves the actual functions into a impl bock associated with the struct.
