### ISSUE TITLE
LLVM-19 support

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#1064]
Debian recently switched the default LLVM to llvm-19, and faust-2.75.7 no longer compiles.

See https://bugs.debian.org/1084254

it *does* compile with LLVM-18, but since `llvm-config` points to LLVM-19, it's a bit complicated... afaict, the name of the `llvm-config` executable is hardcoded in multiple locations in faust (including some generators).

**Comment by umlaeute** [comment]
ah, i just noticed 5b275806093fb2e3348043de1150f01ff892d232, which i guess makes this issue obsolete.

**Comment by sletz** [comment]
Yes, LLVM 19 is supported now.
