### ISSUE TITLE
Missing -pthread compile flag for 'make light' target

### ISSUE THREAD

**Issue by cyberic99** [grame-cncm/faust#107]
If I `make light`, I get compile errors, related to pthread functions being undefined.
This is on archlinux.

Adding `-pthread` on this line:
https://github.com/grame-cncm/faust/blob/6cd9bb4cff6ff195cd1db77ec1b7810edb804b9a/compiler/Makefile.unix#L312
fixes the issue.

**Comment by sletz** [comment]
Fixed thanks.

**Comment by cyberic99** [comment]
wow that was fast! ;-)
