### ISSUE TITLE
faust2ladspa: some UI elements not working

### ISSUE THREAD

**Issue by oldstar84** [grame-cncm/faust#1078]
hello,
if using faust2ladspa with the following *.dsp code, the hbargraph shows "100%" and never move.

my test.dsp:
ba = library("basics.lib");
process = _ <: attach(_,abs : ba.linear2db : hbargraph("input",-60,0));

FAUST Version 2.74.6  and
ladspa-sdk-dev (1.17-1) is installed

I compiled it with: faust2ladspa test.dsp

also the standard values for sliders seems not to be recognized in my ladspa plugins

my code runs fine as lv2 plugin.

any hints?

**Comment by sletz** [comment]
LADSPA architecture is **very** old and is not maintained anymore, so better use LV2 format.
