### ISSUE TITLE
faust2vcvrack error when compiling for windows

### ISSUE THREAD

**Issue by mysticallego** [grame-cncm/faust#1082]
When you compile any program with faust2vcvrack, it outputs macro code that causes an error when compiling for windows.

This block of code is the source of the error:
```c++
#ifdef _WIN32
typedef unsigned int uint
#endif
```
There should be a semicolon after uint.

**Comment by sletz** [comment]
Here https://github.com/grame-cncm/faust/blob/2189f61c629ad839f4e599bd2134c29691cc9357/architecture/vcvrack/template/src/FaustModule.cpp#L55 ?

**Comment by mysticallego** [comment]
Yes, exactly.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/09da2d8a44f56fabad1b9147ddd5fd8b35c07726
