### ISSUE TITLE
Using rnoise and other arc4random functions in HISE results in a crash on Windows, but not macOS

### ISSUE THREAD

**Issue by aaronventure** [grame-cncm/faust#1083]
Hi,

I'm using Faust with HISE, and if I use rnoise or any other arc4random functions, it results in a crash on Windows, but it works fine on macOS. I talked to Christoph about this a few months ago

https://github.com/christophhart/HISE/issues/552
https://forum.hise.audio/topic/9992/faust-acting-up-on-windows/35?_=1732282155580

where he stated that he has no idea why it crashes, implying it could be on Faust's end. 

Do you have any idea what might be causing it?

1. Install latest Faust
2. Build HISE for Faust https://forum.hise.audio/topic/6746/updated-build-instructions
3. Add an effect > Script FX > Faust node > Open in Editor (icon)
4. Attempt to use rnoise in a series, or multiply it, etc.

I'm attempting to get Faust to create a bunch of random numbers on "compile" - `no.noise : ba.latch(1)` always results in the same output, but rnoise works exactly as expected (on macOS), but it's not possible to use it on Windows. 

Thanks!

**Comment by sletz** [comment]
To have a proper random, we use the `arc4random`  foreign function  (see https://github.com/grame-cncm/faustlibraries/blob/5754a85396e0a14e9b56195a20119493e3dae463/noises.lib#L153) that seems not to be available on windows. 
Can ideas coming from https://chatgpt.com/share/6741b247-163c-8013-9606-a9cf122d4c26 be teste on your side ?
