### ISSUE TITLE
faust2daisy generated code does not compile for -pod or -patch option

### ISSUE THREAD

**Issue by ghoppla** [grame-cncm/faust#1089]
### faust2daisy generated code does not compile for -pod or -patch option

When compiling code using `faust2daisy` with option -pod or -patch the code does not compile. 
Only -patchsm is working. 

The problem is that somehow ValueConverter.h is not included in the generated cpp file. 

### Steps for reproduction 

**Versions Used:**
- Faust master-dev, 2.76.0, Commit: [5ed7170](https://github.com/grame-cncm/faust/commit/5ed7170ba01bf5f536988d77d90c3235c6ea82fc)
- libDaisy v7.1.0

**Daisy Toolchain Setup on Linux:**

1. Create a folder, e.g.
   ```bash
   $ mkdir ~/daisy
   ```

2. Get arm-none-eabi:
   - See [DaisyWiki](https://github.com/electro-smith/DaisyWiki/wiki/1d.-Installing-the-Toolchain-on-Linux)

3. Get libDaisy:
   ```bash
   $ git clone --recurse-submodules https://github.com/electro-smith/libDaisy
   ```

4. Create `environment.rc` file with the following content:
   ```bash
   export LIBDAISY_DIR=~/daisy/libDaisy

   GCC_PATH=~/daisy/gcc-arm-none-eabi-10-2020-q4-major/bin
   export PATH=$GCC_PATH:$PATH
   ```

5. Compile libDaisy:
   ```bash
   $ source environment.rc
   $ cd libDaisy
   $ make
   ```

**Compilation:**
1. dsp file minimal_example.dsp
```faust
import("stdfaust.lib");
declare name "Daisy Seed Bug";
declare options "[midi:on]";

gate = button("gate");
vel = hslider("gain", 0, 0, 1, .01);
freq = hslider("freq", 440, 0, 20000, 0.01);

process = os.triangle(freq) * vel : _*en.adsr(.1,.1,.7,.2, gate) <: _,_;
```

2. Generated cpp code with:
```bash
$ faust2daisy -patch -midi -sr 48000 -bs 32 -uim -source minimal_example.dsp
```

when running make within the generated folder 
```bash
$ cd minimal_example
$ make
```
a lot of the compilation errors appear, since ValueConverter.h is not included: 

```
ex_faust.cpp:1220:1: error: expected class-name before '{' token
 1220 | {
      | ^
ex_faust.cpp:1265:29: error: 'ValueConverter' was not declared in this scope
 1265 |             std::unique_ptr<ValueConverter> fConverter;
      |                             ^~~~~~~~~~~~~~
ex_faust.cpp:1265:43: error: template argument 1 is invalid
 1265 |             std::unique_ptr<ValueConverter> fConverter;
      |                                           ^
ex_faust.cpp:1265:43: error: template argument 2 is invalid
ex_faust.cpp:1267:76: error: 'ValueConverter' was not declared in this scope; did you mean 'fConverter'?
 1267 |             AnalogKnob(uint16_t* adcptr, FAUSTFLOAT* zone, std::unique_ptr<ValueConverter>& converter, int rate)
      |                                                                            ^~~~~~~~~~~~~~
      |                                                                            fConverter
ex_faust.cpp:1267:90: error: template argument 1 is invalid
 1267 |             AnalogKnob(uint16_t* adcptr, FAUSTFLOAT* zone, std::unique_ptr<ValueConverter>& converter, int rate)
      |                                                                                          ^
ex_faust.cpp:1267:90: error: template argument 2 is invalid
ex_faust.cpp: In member function 'virtual void DaisyControlUI::AnalogKnob::update()':
ex_faust.cpp:1275:36: error: base operand of '->' is not a pointer
 1275 |                 *fZone = fConverter->ui2faust(Process());
      |                                    ^~
ex_faust.cpp: In member function 'void DaisyControlUI::InitKnobs()':
ex_faust.cpp:1320:33: error: 'ValueConverter' was not declared in this scope
 1320 |                 std::unique_ptr<ValueConverter> converter;
      |                                 ^~~~~~~~~~~~~~
ex_faust.cpp:1320:47: error: template argument 1 is invalid
 1320 |                 std::unique_ptr<ValueConverter> converter;
      |                                               ^
ex_faust.cpp:1320:47: error: template argument 2 is invalid
ex_faust.cpp:1322:50: error: 'LogValueConverter' was not declared in this scope
 1322 |                     converter = std::make_unique<LogValueConverter>(0., 1., fKnobs[i].fMin, fKnobs[i].fMax);
      |                                                  ^~~~~~~~~~~~~~~~~
ex_faust.cpp:1322:107: error: no matching function for call to 'make_unique<<expression error> >(double, double, float&, float&)'
 1322 |                     converter = std::make_unique<LogValueConverter>(0., 1., fKnobs[i].fMin, fKnobs[i].fMax);

.
.
.
```

**Comment by ghoppla** [comment]
In this part of the faust architecture the corresponding gui source files are included.
```
#include "faust/gui/meta.h"
#include "faust/gui/UI.h"
#if defined PATCHSM
#include "faust/gui/DaisyPatchInitControlUI.h"
#else
#include "faust/gui/DaisyControlUI.h"
#endif
#include "faust/dsp/dsp.h"
```

ValueConverter.h is included in DaisyControlUI.h and DaisyPatchInitControlUI.h
I don't understand why the ValueConverter.h is included for with DaisyPatchInitControlUI.h only.

**Comment by sletz** [comment]
Well `DaisyPatchInitControlUI` was developed after `DaisyControlUI` with an external contribution, and looking at the file, **a lot**  of code is actually duplicated. So I guess the proper way would be to rework all of that, and put the new code of `DaisyPatchInitControlUI` in `DaisyControlUI` to finally keep a unique `DaisyControlUI` file, and possibly use `#if defined PATCHSM ....some code... #endif` inside it.

But this means a bit of work ((-;

**Comment by ghoppla** [comment]
hmmm... unfortunately I don't have this expensive hardware to verify that stuff finally, since I've built my own hw interface for the raw daisy seed board. I could do it in blind mode without testing on the patch / pod only but thats not that good idea I think.

**Comment by ghoppla** [comment]
Despite the fact that the code is duplicated, from the preprocessor logic the the weird thing is that ValueConverter.h is not included for the -pod and -patch Option. Don't get it why...

**Comment by sletz** [comment]
> . I could do it in blind mode without testing on the patch / pod only but thats not that good idea I think.

But you could at least test if the restructured code would compile right ?

**Comment by DBraun** [comment]
Note that using all `if` instead of `else` doesn't work:
```c++
#include "faust/gui/meta.h"
#include "faust/gui/UI.h"
#if defined PATCHSM
#include "faust/gui/DaisyPatchInitControlUI.h"
#endif
#if defined POD
#include "faust/gui/DaisyControlUI.h"
#endif
#include "faust/dsp/dsp.h"
```
So for some reason `#if defined POD` isn't working, and my earlier example only worked because it was falling into an `else`.

**Comment by DBraun** [comment]
I suspect this line is too early

https://github.com/grame-cncm/faust/blob/3527fef813118be5849a65dc9af62cbf48a80d2c/tools/faust2appls/faust2daisy#L117

Since it happens before all of the preprocessor stuff

**Comment by DBraun** [comment]
Maybe using 0 and 1 for the booleans is better than false and true in https://github.com/grame-cncm/faust/blob/3527fef813118be5849a65dc9af62cbf48a80d2c/tools/faust2appls/faust2daisy

**Comment by DBraun** [comment]
I think it's because we're using `faust -i` for inline architectures. That leads to `gInlineArchSwitch` being true and https://github.com/grame-cncm/faust/blob/cfcb1d07db7028331c1a7a3d8acda023da126c8d/compiler/parser/enrobage.cpp#L497 and then https://github.com/grame-cncm/faust/blob/cfcb1d07db7028331c1a7a3d8acda023da126c8d/compiler/parser/enrobage.cpp#L167

Looking at this:
```c++
#include "faust/gui/meta.h"
#include "faust/gui/UI.h"
#if defined PATCHSM
#include "faust/gui/DaisyPatchInitControlUI.h"
#else
#include "faust/gui/DaisyControlUI.h"
#endif
#include "faust/dsp/dsp.h"
```
Even though `PATCHSM` is not defined, I think `#include "faust/gui/DaisyPatchInitControlUI.h"` is passed through the `inject` function. All of its code is injected, including
```c++
#include "faust/gui/DecoratorUI.h"
#include "faust/gui/ValueConverter.h"
```
Then when `#include "faust/gui/DaisyControlUI.h"` is injected, the algorithm thinks `DecoratorUI.h` and `ValueConverter.h` have already been included, and so they get skipped.
