### ISSUE TITLE
Menu-style UI elements in faust2juce targets: item alway resetting to index-1

### ISSUE THREAD

**Issue by dariosanfilippo** [grame-cncm/faust#1101]
Hello.

It appears that the selected item of menus in faust2juce projects always reset to index-1 whenever the UI is re/opened. This might be related to a bug that was recently fixed in the same target where checkboxes always switched to 1 in a similar way.

Thanks,
Dario

**Comment by dariosanfilippo** [comment]
Correction: it seems that the problem is just when loading the app.

`process = hslider("[02]Test[style:menu{'t0':0;'t1':1;'t2':2}]", 0, 0, 2, 1);`

Compiling the code above with faust2juce, when reopening the app it'll always be on "t1" instead of t0.

Thanks

**Comment by sletz** [comment]
@dariosanfilippo Should be fixed in [2.77.4.](https://github.com/grame-cncm/faust/commit/f70a5ae0f00dce97a896ce1612211d9f4c5e6757)
