### ISSUE TITLE
Docker-compile query

### ISSUE THREAD

**Issue by orbsmiv** [grame-cncm/faust#112]
I'm in the process of tidying the Dockerfile (I'll submit a PR soon) but it's throwing an error on the following lines in the Makefile:

```
cp libraries/old/*.lib $(prefix)/share/faust/
cp libraries/*.lib $(prefix)/share/faust/
```

... as it can't find the directories. Is this indicative of a separate issue? When I remove these lines the installation appears to continue without issue and I'm able to run the Faust command from the resulting image, although I'm yet to test anything thoroughly.

FYI the Dockerfile currently looks like this (although the multiple `RUN` lines are for testing purposes only):
```
FROM debian:stretch-slim

RUN apt-get update && \
  apt-get install -y build-essential libssl-dev llvm libncurses5-dev libssl1.1 libncurses5 zlib1g-dev && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir /faust
WORKDIR /faust
COPY . /faust

RUN make

RUN make install

RUN make -C tools/faust2appls install && make clean

# RUN apt-get purge -y build-essential libssl-dev llvm libncurses5-dev && apt-get autoremove -y
RUN apt-get purge -y build-essential libssl-dev libncurses5-dev && apt-get autoremove -y

CMD ["/usr/local/bin/faust"]
```

**Comment by orlarey** [comment]
Maybe the problem is that prefix is by default `/usr/local`:

```
DESTDIR ?=
PREFIX ?= /usr/local
prefix := $(DESTDIR)$(PREFIX)
```
You can control its value with the environment variables DESTDIR and PREFIX
