### ISSUE TITLE
Supercollider output: check for mem alloc fail

### ISSUE THREAD

**Issue by vivid-synth** [grame-cncm/faust#12]
For the SuperCollider output, calls to RTAlloc should handle the case that the allocation fails (e.g. there's not enough memory.)

We've been fixing this in our own UGens here: https://github.com/supercollider/supercollider/issues/782

Here is a specific issue from Faust-created UGens: https://github.com/supercollider/sc3-plugins/issues/133

**Comment by sletz** [comment]
Hopefully fixed in 413ff48e23b50d0adfe0cd50b9740d1c6524d9a8.
