### ISSUE TITLE
including emacs faust-mode

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#120]
As the other completers are also included, I'd suggest adding/submoduling @agraef 's [emacs-faust-mode](https://github.com/agraef/emacs-faust-mode) to this repository.

This would be great to have in the next release!

**Comment by sletz** [comment]
I guess @agraef can directly commit/push that.

**Comment by agraef** [comment]
Will do.

**Comment by agraef** [comment]
Done. Note that I added the version from my fork at https://github.com/agraef/emacs-faust-mode, as the original version at https://github.com/rukano/emacs-faust-mode in its current state isn't usable (recent changes by yassinphilip broke indentation and add a bunch of useless hard-wired keywords).
