### ISSUE TITLE
Add -std=c++11

### ISSUE THREAD

**Issue by ryandesign** [grame-cncm/faust#125]
Hi, building faust from source on OS X Yosemite, I see warnings like these:

```
generator/sharing.cpp:161:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto& p : fConditionProperty) {
               ^
generator/sharing.cpp:161:24: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto& p : fConditionProperty) {
                       ^
generator/sharing.cpp:167:16: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (const auto& p : fConditionStatistics) {
               ^
generator/sharing.cpp:167:24: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (const auto& p : fConditionStatistics) {
                       ^
generator/sharing.cpp:197:5: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto p = fConditionProperty.find(t);
    ^
```
```
normalize/mterm.cpp:480:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
                        for (auto p : fFactors)
                             ^
normalize/mterm.cpp:480:16: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
                        for (auto p : fFactors)
                                    ^
```
```
signals/binop.cpp:48:9: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
        WasmOp::I32Add, WasmOp::I64Add, WasmOp::F32Add, WasmOp::F64Add,
        ^
```

Since you appear to require C++11, please specify that by adding `-std=c++11` to the flags that you send to the C++ compiler. Not all compilers default to C++11 mode.

**Comment by ryandesign** [comment]
Hmm, I see now in compiler/Makefile.unix that you add `-std=gnu++11` if I ask for LLVM 3.5 or later. But it appears that your source code needs C++11 support even if I ask for LLVM 3.4, for example.

Note that I am compiling with a different compiler (the version of clang that comes with Xcode, of if necessary a newer clang that supports C++11 provided by MacPorts), not the one matched to the version of LLVM I selected.

**Comment by agraef** [comment]
@sletz couldn't we just add the -std=gnu++11 unconditionally and be done with it? I can't reproduce @ryandesign's issue as I'm on Sierra where LLVM 3.9 is being used IIRC. But if it solves the issue at hand and doesn't break anything, then it's probably the right thing.

@ryandesign, the next Faust release will be based on cmake if I'm not mistaken, so this issue may just resolve itself by then.

**Comment by ryandesign** [comment]
It looks like the intention was to fall back to `-std=c++11` if the previous LLVM version tests had not already added `-std=gnu++11`:

    CXXFLAGS ?= -std=c++11

The problem is that this line never has any effect, because all code paths lead to `CXXFLAGS` already being set to something by the preceding `if` block:

```
ifeq ($(system), Darwin)
    CXXFLAGS += -I /opt/local/include
    CXXFLAGS += -stdlib=libc++
else
    ifneq ($(findstring MINGW32, $(system)),)
        CXXFLAGS += -O1 -I/usr/include
    else
        CXXFLAGS += -O1 -fPIC -D__USE_MINGW_ANSI_STDIO
    endif
endif
```

Looks like this got messed up when the file's lines were reordered in ba4cdc7fa721c9946b158352a4c6078a68c03bdd.

The unconditional setting of `-stdlib=libc++` and `-I /opt/local/include` on Darwin are things we're going to have to patch in MacPorts too. MacPorts might not be in /opt/local; it might be somewhere else. And anyway, `-I` flags belong in `CPPFLAGS` not `CXXFLAGS`. And on OS X 10.8 and earlier, the default C++ stdlib is libstdc++, and if faust wants to link with llvm libraries built against libstdc++, it cannot itself use libc++; that will not compile. Granted, the old OS X libstdc++ doesn't support C++11, but in MacPorts we have a newer version of libstdc++ that we can use to get C++11 support on older systems.

**Comment by dfober** [comment]
all the code is now covered by c++11 extensions
