### ISSUE TITLE
SuperCollider architecture: initialize outputs

### ISSUE THREAD

**Issue by snappizz** [grame-cncm/faust#13]
The Ctor function in a SuperCollider UGen needs to set output values. Otherwise, downstream UGens may access garbage memory and create explosions (https://github.com/supercollider/supercollider/issues/2333).

The simplest solution here is to add an unconditional `ClearUnitOutputs(unit, 1)` at some point in `Faust_Ctor`.

**Comment by sletz** [comment]
Hopefully fixed in 413ff48e23b50d0adfe0cd50b9740d1c6524d9a8.

**Comment by snappizz** [comment]
Thanks for the quick response!
