### ISSUE TITLE
Faust prefix in SuperCollider Ugens

### ISSUE THREAD

**Issue by florian-grond** [grame-cncm/faust#131]
@sletz  just merged a much-appreciated patch which helps to better integrate Faust generated Ugens in SuperCollider.
The last obstacle, it seems, to comply with the SuperCollider Ugen Naming convention is the Faust prefix which is automatically added to each Faust generated Ugen.

This prefix shows up in two places:
1) the C++ source code where it can be removed during compilation. So when compiling Faust generated SC3 plugins one needs to set_property(TARGET ... APPEND PROPERTY COMPILE_DEFINITIONS SC_FAUST_PREFIX="\"\"")

2) it also shows up in the SuperCollider language class file: e.g. generated with faust2sc
**Faust**HOAEncoder1 : MultiOutUGen
....
 name { ^"**Faust**HOAEncoder1" }

I would be great to have a flag in **faust2supercollider**, which - when keeping the C++ sources with the -ks flag - allows controlling the SC_FAUST_PREFIX in the C++ sources setting it to " " and generating the SuperCollider language file without the Faust prefix too.

This would allow adding large collections of Faust libraries to the SC3plugins, without the need to check for each Faust generated Ugen the prefix having to set the COMPILE_DEFINITIONS and editing the SuperCollider class file.

@brianlheim, @patrickdupuis, @sletz, @telephon, @LFSaw, @jamshark70  
For Faust to leave traces in the Ugens I suggest adding an **info** method to the SuperCollider class file which prints to the SuperCollider post window:
This info method could contain info about the Faust version with which it was generated, the author of the Faust code and the license, essentially everything that is declared in the Faust file under:
declare name       
declare version     
declare author     
declare license     
declare copyright

**Comment by sletz** [comment]
"I would be great to have a flag in faust2supercollider" => can you @lorian-grond and/or @nicobou prepare a PR for that? Thanks.

**Comment by florian-grond** [comment]
Will try if @nicobou wants to assist, at the earliest next Friday.
@brianlheim, @patrickdupuis, @telephon, @LFSaw, @jamshark70
any opinion about the info method in the SuperCollider class file?

**Comment by nicobou** [comment]
@florian-grond sure, I want to assist.

**Comment by florian-grond** [comment]
yes, I was also thinking to post on request.



www.grond.at

**Comment by brianlheim** [comment]
IMO, if the method posts, it should be named `postInfo` or similar to indicate the action it performs. The name `info` on its own suggests that it will return some metadata object. I would in fact prefer if it were named `info` and returned this data as a string or some similar format. Then the client can decide what to do with the information.

**Comment by telephon** [comment]
yes, makes sense.

**Comment by florian-grond** [comment]
thanks @brianlheim  we can definitely call it info and return a string

**Comment by sletz** [comment]
PR merged.
