### ISSUE TITLE
Please do not add 'make' to makefiles: please always use $(MAKE) instead

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#133]
By using 'make' you assume that make executable is always named 'make', but this isn't true on BSDs.
I submitted several pull requests in the past correcting these, but then you always add 'make' again.

For example:
>	make -C tools/faust2appls install

Could you please replace make -> $(MAKE) everywhere?

**Comment by agraef** [comment]
The Grame team is probably busy getting the new cmake build system off the ground, which should hopefully solve all these petty problems.

For the time being, please post a patch or submit a PR with your suggested changes, and I'll commit it.

**Comment by yurivict** [comment]
Ok, will do this, thanks!

**Comment by agraef** [comment]
I just saw that you already submitted a PR (#108) in December, currently reviewing it.

**Comment by yurivict** [comment]
Yes, I forgot that it hasn't been merged.

**Comment by orlarey** [comment]
Merged in 397f68d37805d2a5218149eae0e9432a82b993a7
