### ISSUE TITLE
Installs Mach-O on FreeBSD: lib/faust/ios-libsndfile.a

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#135]
It appears that this line:
> cp architecture/ios-libsndfile.a $(prefix)/lib/faust

installs this library unconditionally.

```
$ file /usr/local/lib/faust/ios-libsndfile.a
/usr/local/lib/faust/ios-libsndfile.a: Mach-O universal binary with 5 architectures: [armv7: current ar archive random library] [x86_64]
```

**Comment by agraef** [comment]
Yeah, it's installed on all OSes. I think we've discussed this once or twice before. ;-) The idea probably is that you can use this in cross-compilation to produce working iOS binaries, but I'm not sure that this will work on anything else but a Mac. (Something similar is available for Android, but there the cross-platform compilation tools *are* available from Google.)

**Comment by yurivict** [comment]
> you can use this in cross-compilation to produce working iOS binaries, but I'm not sure that this will work on anything else but a Mac.

Certainly not on BSDs.
