### ISSUE TITLE
[Windows] Invalid macros used for 64-bit compilation

### ISSUE THREAD

**Issue by felakuti4life** [grame-cncm/faust#140]
Windows specific includes and code are currently guarded with the `WIN32` macro. However, the correct check for pretty much all of these checks should be looking to see if `_WIN32` or `_WIN64` are defined.

For example, in cpp_code_container.hh:
```
#ifdef WIN32 
#pragma warning (disable: 4250)
#endif
```

should be

```
#if defined(_WIN32) || defined(_WIN64) 
#pragma warning (disable: 4250)
#endif
```

**Comment by dfober** [comment]
WIN32 is defined for both architectures (32 and 64). For the time being, there is no need to differentiate.
