### ISSUE TITLE
updating Faust in old project getting Error for definitions found in faustparser.cpp

### ISSUE THREAD

**Issue by mxa** [grame-cncm/faust#152]
I forked Synth-A-Modeler and updated Faust, but then get `physicalmodeling.lib : 67 : ERROR : syntax error, unexpected ENABLE, expecting RBRAQ or IDENT`
It works with Faust 0.9.46 though. Any ideas where this error is from? https://github.com/chairaudio/SaM-Designer/issues/2

**Comment by orlarey** [comment]
@mxa 'enable' is now a reserved keyword for a new primitive of the language (still experimental). Try to rename enable in your code, that should solve the problem.

**Comment by mxa** [comment]
Thanks @orlarey with a little help by @g2oo7fy I figured it out.
