### ISSUE TITLE
Getting executable code with llvm-dsp on win 64 ?

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#158]
I'm having some trouble with getting faust to work on windows.
I am calling the following: 

     createCDSPFactoryFromString( "score", "process = _;", 0, nullptr, "x86_64-pc-windows-msvc", err, -1);

The code generation seems to happen, but I get a crash when calling `dsp_imp* dsp = fNew();` in `llvm_dsp* llvm_dsp_factory_aux::createDSPInstance(dsp_factory* factory)`  :  `Exception thrown at 0x000000000A130040 in score.exe: 0xC0000005: Access violation executing location 0x000000000A130040.`. 

Couldn't it mean that the memory hasn't been marked as executable in some way ? I'm using LLVM 6, and the latest MSVC - everything in 64 bit.

**Comment by dfober** [comment]
So far, I’ve got similar issues when using MSVC (LLVM 5.0 - x64). 
The good news is that it works when compiled using MSYS2. 
See the build/README.md for the packages you need.

**Comment by jcelerier** [comment]
Thanks !

**Comment by pierreguillot** [comment]
Indeed, the LLVM compilation throw an exception that is not catched. The exception gives: "Broken function found, compilation aborted!", (so you have to catch it otherwise the program will crash). Anyway, I don't know how to fix this so it doesn't help... Perhaps, the build/readme.md should inform about this problem?

**Comment by sletz** [comment]
The crash described by @jcelerier  is different from the ""Broken function found, compilation aborted!"" issue. Does it happens with any DSP you've tested?

**Comment by pierreguillot** [comment]
Alright, sorry for the confusion. I'll be back on the Windows machine next week and give you further information. Do you want me to create a new issue?

**Comment by sletz** [comment]
Yes, a new issue would be better.
Goggling ""Broken function found, compilation aborted!""  reports LLVM code generation issue, as if the Faust LLVM backend was not generating correct IR code, before even JITing it.  It would be interesting to see if the issue happens with any DSP. You can also possibly test the LLVM backend using the Faust command line, like : faust -lang llvm foo.dsp
