### ISSUE TITLE
Necessity of openssl ? 

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#159]
Hello,

I noticed that for a "normal" faust build, if I am not mistaken, OpenSSL is only used for that one tiny SHA1 function call here : https://github.com/grame-cncm/faust/blob/1093937dc648fe24b802a7ecb7221b2eaa35d35c/compiler/generator/llvm/machine/llvm_machine_dsp_aux.cpp#L730

Woul it make sense to replace with a smaller library that only does this without requiring cumbersome (at least on windows!) dependencies, such as : 
https://github.com/mohaps/TinySHA1 or https://github.com/kazuho/picohash ? 

I can contribute a patch which uses tinysha1 if you are interested.

**Comment by dfober** [comment]
OpenSSL is not required any more (nor any other library). SHA1 is now part of the src code.
The remaining references to OpenSSL should be removed.

**Comment by jcelerier** [comment]
okay! the problem is the include here: 

    https://github.com/grame-cncm/faust/blob/1093937dc648fe24b802a7ecb7221b2eaa35d35c/compiler/generator/llvm/machine/llvm_machine_dsp_aux.cpp#L22

**Comment by sletz** [comment]
Fixed in 6e8ad5686b63b254028f3d76cd6f0b7683b306fd.

**Comment by jcelerier** [comment]
thanks !
