### ISSUE TITLE
faust2 places FAUSTFLOAT define too early in cpp output

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#16]
faust1 has this in the proper location (right before `<<includeclass>>`) so that architectures like csound.cpp and pure.cpp can override the `#define` without getting silly warnings about `FAUSTFLOAT` being redefined.

faust2 places it near the beginning of the output file, so that there's no chance in hell to have it defined by the architecture first (which also makes the `#ifndef FAUSTFLOAT` in the generated code rather pointless). Adding insult to injury, it's not possible to make this work with faust2 (using an `#ifdef` in the architecture) without breaking faust1 compilation.

faust1 does this right IMHO, so faust2 should follow suit.

**Comment by sletz** [comment]
Should be fixed in cc8ff39b877e814c34c185cc53746522599d857a.

**Comment by agraef** [comment]
Works, thanks!
