### ISSUE TITLE
faust/gui/JSONUIDecoder.h not found on LInux

### ISSUE THREAD

**Issue by vrx** [grame-cncm/faust#162]
I compiled faust from github but when trying to compile any example i get this message 
faust/gui/JSONUIDecoder.h not found

**Comment by vrx** [comment]
sorry, on ubuntu 17.10, typing usual make when compiling faust compiler, i tried github source and the tarball of latest release - same pb - i guess there must be some kind of path to set?

faust2jack filterBank.dsp 
/usr/local/share/faust/
faust/gui/JSONUIDecoder.h not found

that's all i got
thanks by advance !

**Comment by sletz** [comment]
1) have you done « sudo make install » ?

2) can you check what is then installed in /usr/local/include/faust  ? JSONUIDecoder should be there.

**Comment by vrx** [comment]
1 - yes
2- 
ls /usr/local/include/faust/
au  audio  dsp  gui  midi  misc.h  osc  sound-file.h  unity  vst

ls /usr/local/include/faust/gui/
ls: cannot open directory '/usr/local/include/faust/gui/': Permission denied

that was it ! permission access problem... thanks !
v
