### ISSUE TITLE
Building httpdlib with msys2/mingw in Windows

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#169]
I'm trying to build the dynamic httpdlib on Windows using the msys2/mingw32 environment. I have the corresponding libmicrohttpd package installed in msys2. Most of the compile goes through all right, but linkage fails. The link command is:

cd /C/msys64/home/ag/github/faust/build/faustdir/http && /C/msys64/mingw32/bin/g++.exe  -O3
  -shared -o ../../lib/libHTTPDFaust.dll -Wl,--out-implib,../../lib/libHTTPDFaust.dll.a -Wl,--major-image-version,0,--minor-image-version,7 -Wl,--whole-archive CMakeFiles/httpdynamic.dir/objects.a -Wl,--no-whole-archive -lws2_32 /C/msys64/home/ag/github/faust/windows/libmicrohttpd/x64/MSYS/libmicrohttpd.lib -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

I'm getting these linker errors:

~~~make
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x14): undefined reference to `MHD_stop_daemon'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x47): undefined reference to `MHD_stop_daemon'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xcb): undefined reference to `MHD_start_daemon'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x105): undefined reference to `MHD_create_response_from_buffer'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x129): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x141): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x159): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x163): undefined reference to `MHD_destroy_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x3f2): undefined reference to `MHD_create_response_from_fd'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x41a): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x432): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x449): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x453): undefined reference to `MHD_destroy_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x482): undefined reference to `MHD_create_response_from_buffer'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x4a0): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x4b8): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x4cf): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x9a0): undefined reference to `MHD_create_response_from_buffer'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x9c8): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x9e0): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x9f7): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x9ff): undefined reference to `MHD_destroy_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xf0e): undefined reference to `MHD_create_response_from_buffer'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xf36): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xf4e): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xf65): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0xf6f): undefined reference to `MHD_destroy_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x16e5): undefined reference to `MHD_get_connection_values'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x18e7): undefined reference to `MHD_create_response_from_buffer'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x1909): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x1921): undefined reference to `MHD_add_response_header'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x1938): undefined reference to `MHD_queue_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDServer.cpp.obj):HTTPDServer.cpp:(.text+0x1942): undefined reference to `MHD_destroy_response'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDSetup.cpp.obj):HTTPDSetup.cpp:(.text+0x2f): undefined reference to `MHD_stop_daemon'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDSetup.cpp.obj):HTTPDSetup.cpp:(.text+0x7f): undefined reference to `MHD_stop_daemon'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDSetup.cpp.obj):HTTPDSetup.cpp:(.text+0x189): undefined reference to `MHD_stop_daemon'
collect2.exe: error: ld returned 1 exit status
make[4]: *** [http/CMakeFiles/httpdynamic.dir/build.make:620: ../lib/libHTTPDFaust.dll] Error 1
make[4]: Target 'http/CMakeFiles/httpdynamic.dir/build' not remade because of errors.
make[4]: Leaving directory '/home/ag/github/faust/build/faustdir'
make[3]: *** [CMakeFiles/Makefile2:379: http/CMakeFiles/httpdynamic.dir/all] Error 2
~~~

@dfober, it seems that it's trying to link against a pre-compiled libmicrohttpd shipping with the Faust sources there. Which is a 64 bit binary, and that of course is useless when I'm building the 32 bit version with mingw32. Is there a way I can force it to link against the msys2 library instead?

**Comment by dfober** [comment]
oups !
that’s above all because the libmicrohttpd library is compiled using MSVC (both in 32 and 64 bits versions)
I’ll take account of MSYS and let the building system use the MSYS package.
—
Dom

**Comment by dfober** [comment]
I'm currently looking at the problem...
obviously what should not have taken 2 minutes turns out to be really time consuming. (thanks to the windows world!) 
Actually I have pkg-config and libmicrohttpd installed on msys2. pkg-config works perfectly from the command line, cmake can find it but the only result I can get is “libmicrohttpd not found” whether I used cmake pkg_check_modules or a direct call to pkg-config (from cmake). 
So it's turning into a nightmare and I don’t have more time to spend on that right now. Sorry but I think you’ll have to wait a bit for a solution.
—
Dom

**Comment by agraef** [comment]
No problem, take your time. For my students I still have the 2.5.21 release packaged up, that will do for now.

It's probably a cmake issue (cmake has improved a lot in recent years, but I always found its built-in magic a bit quirky on Windows).

**Comment by dfober** [comment]
The cmake setup has been modified to use pkg-config on windows (msys) when not MSVC.
It doesn’t work on my side, pkg-config reports an unknown module with libmicrohttpd (although it works on the command line).
I suspect a conflict with different cmake installations. Could you check on your side.

**Comment by agraef** [comment]
Yeah, same over here. Well, at least it doesn't crap out during linking any more, the target just doesn't get built at all, which is a bit more graceful kind of failure. ;-)

Maybe you could add a way to just specify the required include and linker options manually through a variable? Not very elegant, but nobody will complain if it works.

**Comment by dfober** [comment]
That’s fixed !
The problem was due to cmake that converts msys path to windows path, which was preventing pkg-config to find any installed package.
The fix should be transparent apart that it prints the PKG_CONFIG_PATH on output (for debug purpose and in case of remaining problems)
—
Dom

**Comment by agraef** [comment]
No dice over here. :( Here's what `make -C build reset`gives me:

~~~
-- Using MSYS PKG_CONFIG_PATH :/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig
-- Checking for one of the modules 'libmicrohttpd'
CMake Warning at http/CMakeLists.txt:105 (message):
  Cannot locate libmicrohttpd: skip HTTPDFaust generation
~~~

Seems that `pkg_search_module` is just broken, at least in the msys2 cmake. It's curious, though, that it works for you. Are you using cmake from msys2 or a native install?

Anyway, it's no fun trying to put bandaid on something just seems to be broken, and it's a big waste of time for both you and me. I'd really prefer to being able to tell it the proper libmicrohttpd compilation and linkage options myself. Could you please add a way to do that?

**Comment by dfober** [comment]
> Le 12 avr. 2018 à 16:43, Albert Graef <notifications@github.com> a écrit :
> 
> No dice over here. :( Here's what make -C build resetgives me:
> 
> -- Using MSYS PKG_CONFIG_PATH :/mingw32/lib/pkgconfig:/mingw32/share/pkgconfig
> -- Checking for one of the modules 'libmicrohttpd'
> CMake Warning at http/CMakeLists.txt:105 (message):
>   Cannot locate libmicrohttpd: skip HTTPDFaust generation
> Seems that pkg_search_module is just broken, at least in the msys2 cmake. It's curious, though, that it works for you. Are you using cmake from msys2 or a native install?
> 
> 

I’m using msys2 but I’m compiling 64bits code. On my installation PKG_CONFIG_PATH is /mingw64/lib/pkgconfig:/mingw64/share/pkgconfig

> Anyway, it's no fun trying to put bandaid on something just seems to be broken, and it's a big waste of time for both you and me. I'd really prefer to being able to tell it the proper libmicrohttpd compilation and linkage options myself. Could you please add a way to do that?
> 

something like a -DLIBMICROHTTPD_CFLAGS=“…” and -DLIBMICROHTTPD_LDFLAGS=“…”  ?

**Comment by agraef** [comment]
> something like a -DLIBMICROHTTPD_CFLAGS=“…” and -DLIBMICROHTTPD_LDFLAGS=“…” ?

Yep, that would be great!

**Comment by dfober** [comment]
> Le 13 avr. 2018 à 14:46, Albert Graef <notifications@github.com> a écrit :
> 
> something like a -DLIBMICROHTTPD_CFLAGS=“…” and -DLIBMICROHTTPD_LDFLAGS=“…” ?
> 
> Yep, that would be great!
> 
> 

that’s done !
I hope this time it's the right one!

**Comment by agraef** [comment]
Ok, thanks. But how do I invoke this? I'm afraid that the build documentation in the Wiki isn't very explicit on this. Anyway, this is what I came up with (to be run in the toplevel dir), is that the proper way to do it?

~~~
make -C build cmake CMAKE_OPT="-DLIBMICROHTTPD_CFLAGS=$(pkg-config --cflags libmicrohttpd) -DLIBMICROHTTPD_LDFLAGS=$(pkg-config --libs libmicrohttpd)"
~~~

**Comment by agraef** [comment]
The quoting should be handled by GNU make, I guess. Anyway, both work for me, and I'm getting this during configuration in either case:

~~~
-- Using manual cflags '-IC:/msys64/mingw32/include/p11-kit-1' and ldflags '-lmicrohttpd' for libmicrohttpd
~~~

Which looks good to me, since the printed flags match what I see when I run pkg-config manually.

But when I'm running `make world` afterwards, it still fails during linkage:

~~~
cd /C/msys64/home/ag/github/faust/build/faustdir/http && /C/msys64/mingw32/bin/g++.exe  -O3  -shared -o ../../lib/libHTTPDFaust.dll -Wl,--out-implib,../../lib/libHTTPDFaust.dll.a -Wl,--major-image-version,0,--minor-image-version,7 -Wl,--whole-archive CMakeFiles/httpdynamic.dir/objects.a -Wl,--no-whole-archive -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
CMakeFiles/httpdynamic.dir/objects.a(HTTPDControler.cpp.obj):HTTPDControler.cpp:(.text+0x3c3): undefined reference to `_imp__gethostname@8'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDControler.cpp.obj):HTTPDControler.cpp:(.text+0x439): undefined reference to `_imp__gethostbyname@4'
... (lots of similar messages)
~~~

No `-lmicrohttpd` in sight in the linker command anywhere, so there must still be something wrong in your cmake configuration. If I run the command manually with the `-lmicrohttpd` added, I can get rid of some of the missing symbols, but I still get these:

~~~
CMakeFiles/httpdynamic.dir/objects.a(HTTPDControler.cpp.obj):HTTPDControler.cpp:(.text+0x3c3): undefined reference to `_imp__gethostname@8'
CMakeFiles/httpdynamic.dir/objects.a(HTTPDControler.cpp.obj):HTTPDControler.cpp:(.text+0x439): undefined reference to `_imp__gethostbyname@4'
CMakeFiles/httpdynamic.dir/objects.a(sourcefetcher.cpp.obj):sourcefetcher.cpp:(.text+0x539): undefined reference to `_imp__select@20'
... (lots of similar messages)
collect2.exe: error: ld returned 1 exit status
~~~

So obviously the Windows socket library is missing in the mingw linker command, too. Looks like a glitch in the msys2 libmicrohttpd pkg-config to me. Anyway, if I add *both* `-lmicrohttpd -lws2_32` then the linkage goes through without any hitches. Here's the full successful linker command in all its glory, so that you can try to fix this in your cmake setup:

~~~
cd /C/msys64/home/ag/github/faust/build/faustdir/http && /C/msys64/mingw32/bin/g++.exe  -O3  -shared -o ../../lib/libHTTPDFaust.dll -Wl,--out-implib,../../lib/libHTTPDFaust.dll.a -Wl,--major-image-version,0,--minor-image-version,7 -Wl,--whole-archive CMakeFiles/httpdynamic.dir/objects.a -Wl,--no-whole-archive -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -lmicrohttpd -lws2_32
~~~

**Comment by agraef** [comment]
Another glitch in `make install`: Only libfaust.dll gets copied to the bin directory, but neither libHTTPDFaust.dll nor libOSCFaust.dll. (The corresponding static (\*.a) libraries and dll import (\*.dll.a) libraries get copied to lib all right, only the dlls themselves are missing.)

**Comment by dfober** [comment]
that’s quite confusing…
when I run pkg-config on msys, I get -lws2_32 included
$ pkg-config —libs libmicrohttpd
$ -L/mingw64/lib -lmicrohttpd -lgnutls /mingw64/lib/libintl.dll.a -lws2_32 -lgmp /mingw64/lib/libunistring.dll.a -lidn2 -lhogweed -lgmp -lnettle -ltasn1 -lp11-kit

anyway, I’ve added the ws2_32 link flag (could lead to duplicate input library but I think the linker should ignore that)

**Comment by dfober** [comment]
that’s fixed
