### ISSUE TITLE
osc under linux

### ISSUE THREAD

**Issue by vrx** [grame-cncm/faust#172]
under ubuntu, in order to get osclib to be recognized by faust scripts  i have to manually 
cd faust/architecture/osclib
make dynamic
sudo cp libOSCFaust.so /usr/lib/

but still, compilation fails ::
faust2jack -osc compressor.dsp 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libOSCFaust.so: undefined reference to `UdpSocket::SendTo(IpEndpointName const&, char const*, unsigned long)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libOSCFaust.so: undefined reference to `osc::OutboundPacketStream::operator<<(int)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libOSCFaust.so: undefined reference to `UdpSocket::SetEnableBroadcast(bool)'
collect2: error: ld returned 1 exit status

**Comment by vrx** [comment]
thanks but i am still missing something
cd faust/build/
make configoscdynamic
make: *** No rule to make target 'configoscdynamic'.  Stop.

issuing make help does not mention configoscdynamic

also may be good to state that i am using latest sources from github

**Comment by dfober** [comment]
> Le 30 mars 2018 à 07:03, Vincent Rioux <notifications@github.com> a écrit :
> 
> thanks but i am still missing something
> cd faust/build/
> make configoscdynamic
> make: *** No rule to make target 'configoscdynamic'. Stop.
> 
> issuing make help does not mention configoscdynamic
> 
> 
> also may be good to state that i am using latest sources from github
> 
> 

make sure that you are on the master-dev branch

**Comment by vrx** [comment]
git status
On branch master-dev

**Comment by vrx** [comment]
ok, started from scratch again, pulled latest version of github
installed libmicrohttpd-dev
followed your advices - now it's working fine - thanks !
