### ISSUE TITLE
JUCE project export UI destructor name issue

### ISSUE THREAD

**Issue by MacroMachines** [grame-cncm/faust#175]
I was able to export a simple sine wave FAUST .dsp to JUCE project, in the generated .xcode project I get a semantic error on the UI destructor causing a build error, I renamed the UI destructor on line 7956 of the FaustPluginProcessor.cpp from:
` virtual ~JuceStateUII() {}`
to:
`       ~JuceStateUI() {}`

note the prior UII with 2 'I's
the constructor was UI with one 'I'
it appears to compile and work after making this change, maybe a typo in the Faust2Juce generator?

**Comment by sletz** [comment]
This has been fixed in https://github.com/grame-cncm/faust/commit/ad9b84418a1fd11f564791ecf6864764d71b5ef3
@orlarey: can you possibly update the online compiler server? Thanks.

**Comment by MacroMachines** [comment]
great :)  
I am a bit curious if there is more documentation on the JUCE/FAUST workflow? 

I found a youtube video from about a year ago (Jul 2017 https://www.youtube.com/watch?v=sJUhI3R8Qjs) and a PDF with a bit of information, and I feel like this could be a very powerful combination of tools.  

Currently I am having a hard time seeing the workflow that might allow drafting of a plugin UI in faust and then advance / stylize the UI further in JUCE.  Based on my research and experiments thus far I am not sure how to go about the process of customizing a Faust plugin's UI. 

Currently I am dreaming that I could design DSP processing in Faust and use HISE for GUI layout/design and sample playback, seems like a dream team (if you haven't seen it, HISE is an opensource Kontact style multisampler plugin creation tool made with JUCE : http://www.hise.audio/ )

**Comment by sletz** [comment]
See: 

https://github.com/grame-cncm/faust/tree/master-dev/architecture/juce

https://www.youtube.com/watch?v=VCaQNnDOHR8
