### ISSUE TITLE
I-Q Modulation Example

### ISSUE THREAD

**Issue by Immortalin** [grame-cncm/faust#179]
It would be really awesome if an I-Q Modulation sample can be added to the example code since that is a core part of many signal processing systems e.g. QAM. It would help a lot to showcase faust's power.

**Comment by Immortalin** [comment]
@josmithiii I meant the landing page! It would really help adoption because right now it looks like a toy from the outside even though it is ridiculously powerful. :D

**Comment by MacroMachines** [comment]
> @Immortalin what looks like a toy??  and what is I-Q?  is QAM = quadrature amplitude modulation?  
To me it seems like Faust is mostly directed toward creative audio synthesis/effects DSP crowd, of which I am a part.  Are you maybe coming from a different angle like DSP coprocessors / matlab or scientific precision or something?

**Comment by Immortalin** [comment]
@MacroMachines yes, because the github description says it is for *signal processing* and sound synthesis.
