### ISSUE TITLE
Two problems with setup_FaustLive.exe in FaustLive-Windows-2.44.rar

### ISSUE THREAD

**Issue by philgalbiati** [grame-cncm/faust#191]
Greetings

I downloaded & unrar'ed FaustLive-Windows-2.44.rar yesterday, and found two problems:

1) The setup program set_FaustLive.exe would not run.  It appears that the permissions are not set as executable, as chmod ugo+x fixed the problem.

2) Even though I selected English as the installation language, the license dialog for M$ Visual C++ Redistributable presented itself en francais.

thanx
--p

**Comment by dfober** [comment]
Should be fixed with the last published release (https://github.com/grame-cncm/faustlive/releases)
