### ISSUE TITLE
__packed__ undeclared identifier with the MSVC

### ISSUE THREAD

**Issue by pierreguillot** [grame-cncm/faust#200]
From my appveyor CI: https://ci.appveyor.com/project/pierreguillot/faust-pd/build/1.0.192#L131
\_\_packed\_\_ is an undeclared identifier with the MSVC (defined here https://github.com/grame-cncm/faust/blob/master-dev/compiler/generator/dsp_aux.hh#L300)

**Comment by sletz** [comment]
Should be fixed in  https://github.com/grame-cncm/faust/commit/6ca8fae370ff64c96ca4dd1509c92fff7e26df93. Can you check ?

**Comment by pierreguillot** [comment]
Fixed! Thanks
