### ISSUE TITLE
Error compiling on MSYS2 (Win10 64bit)

### ISSUE THREAD

**Issue by alfonso73** [grame-cncm/faust#203]
Hi all,
here's what i get trying to compile faust on MSYS2

$ make
if test -d .git; then git submodule update --init; fi
make -C build faust BACKENDS=regular.cmake
make[1]: Entering directory '/home/livemachine/faust/build'
make cmake
make[2]: Entering directory '/home/livemachine/faust/build'
cd faustdir && cmake -C ../backends/regular.cmake -C ../targets/regular.cmake -DCMAKE_BUILD_TYPE=Release -G 'MSYS Makefiles' ..
loading initial cache file ../backends/regular.cmake
loading initial cache file ../targets/regular.cmake
-- In target faust: include ASMJS backend
-- In target faust: include C backend
-- In target faust: include CPP backend
-- In target faust: include JAVA backend
-- In target faust: include JS backend
-- In target faust: include OCPP backend
-- In target faust: include WASM backend
-- In target wasmlib: include WASM backend
-- In target asmjslib: include ASMJS backend
CMake Error at C:/msys64/mingw64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw64/share/cmake-3.12/Modules/FindPkgConfig.cmake:39 (find_package_handle_standard_args)
  http/CMakeLists.txt:95 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/livemachine/faust/build/faustdir/CMakeFiles/CMakeOutput.log".
make[2]: *** [Makefile:203: cmake] Error 1
make[2]: Leaving directory '/home/livemachine/faust/build'
make[1]: *** [Makefile:194: faustdir/Makefile] Error 2
make[1]: Leaving directory '/home/livemachine/faust/build'
make: *** [Makefile:35: compiler] Error 2

**Comment by dfober** [comment]
You should have pkg-config installed and it’s missing (at least for cmake).
It is required by the http target and to find the libmicrohttpd library.
If you don’t care about the faust http library, you can edit the build/targets/regular.cmake file or provide a custom one using the make TARGETS variables (see build/make help or build/README.md)
—
Dom

**Comment by alfonso73** [comment]
Thanks @dfober . I put on OFF the http stuff and now i have a faust.exe in the bin folder. But if i run faust MSYS2 claims that the command does not exist. Is there a way to compile faust2 on MSYS2?

**Comment by dfober** [comment]
> Le 28 juil. 2018 à 20:38, Alfonso Santimone <notifications@github.com> a écrit :
> 
> Thanks @dfober <https://github.com/dfober> . I put on OFF the http stuff and now i have a faust.exe in the bin folder. But if i run faust MSYS2 claims that the command does not exist. Is there a way to compile faust2 on MSYS2?
> 

Did you installed after compiling? :  
$ make install
In any case, faust.exe must available from your PATH env variable
you can also modify your PATH

**Comment by dfober** [comment]
> Le 28 juil. 2018 à 23:27, Alfonso Santimone <notifications@github.com> a écrit :
> 
> Yes i forgot to "make install" (btw in the readme is reported as "sudo make install" and is not supported in msys2). Now i have faust command working but no faust2...
> 

what do you mean with faust2?

**Comment by alfonso73** [comment]
I mean the script functionality. Things like faust2w64max6

Il dom 29 lug 2018, 08:48 Dominique Fober <notifications@github.com> ha
scritto:

**Comment by dfober** [comment]
> Le 29 juil. 2018 à 10:39, Alfonso Santimone <notifications@github.com> a écrit :
> 
> I mean the script functionality. Things like faust2w64max6

All the faust2xxx scripts are installed by the ‘install’ target in /usr/local/bin by default.
You should check that they are and that they have the correct access rights.
Now and AFAIK, these scripts have never been tested on windows (or almost never) and most of them will likely fail.
