### ISSUE TITLE
How to build Faust library with FAUSTFLOAT defined as double instead of float?

### ISSUE THREAD

**Issue by maurocsound** [grame-cncm/faust#207]
I'm trying to build Csound with Faust opcodes on Windows, but being that actual Csound sources use double numbers instead of float, there are some trouble in Csound compiling... So, I was wandering if there is an easy way to generate the Faust project so that all the FAUSTFLOAT are double instead of float...

**Comment by sletz** [comment]
Defining FAUSTFLOAT a float of double is done in each architecture file. If Csound architect file needs FAUSTFLOAT to be double, then #define FAUSTFLOAT double has simply to be added at the appropriate place. I see that csound.cpp  has this #define FAUSTFLOAT MYFLT at ligne 66 ? Is this not correct?

**Comment by maurocsound** [comment]
I think that is meant to create Csound plugins from Faust code, right?
In my case, I want to link Faust library in Csound, because there are some opcodes (Csound statements) created by Victor Lazzarini that need libfaust to work.

**Comment by sletz** [comment]
Ah OK then is the embedded/faustcsound/faustcsound.cpp file use used then. Same remark should apply. What is the exact  "trouble in Csound compiling" do you get? Have you asked on the sound mailing list?

**Comment by maurocsound** [comment]
Yes, in the csound-dev mailing list Victor Lazzarini suggested me to try compiling only the dll (faustops.dll) needed for those faust opcodes (in this way I could avoid to build all the Csound project just to make the faust opcodes work... It should be sufficient to install the Csound Windows binary package and then use the generated faustops.dll as a plugin). 

But then I have this (in the "MSYS2-MinGW 64bit" environment):

```
$ g++ -O3 -shared -o faustops.dll faustgen.cpp -lfaust -I "C:/Program Files/Csound6_X64/include/csound" -I "C:/msys64/usr/local/include"
faustgen.cpp: In function 'int32_t perf_faust(CSOUND*, faustgen*)':
faustgen.cpp:678:44: error: no matching function for call to 'llvm_dsp::compute(int32_t&, double* [1999], double* [40])'
   p->engine->compute(nsmps, p->ins, p->outs);
                                            ^
In file included from faustgen.cpp:38:0:
C:/msys64/usr/local/include/faust/dsp/llvm-dsp.h:81:14: note: candidate: virtual void llvm_dsp::compute(int, float**, float**)
         void compute(int count, FAUSTFLOAT** inputs, FAUSTFLOAT** outputs);
              ^~~~~~~
C:/msys64/usr/local/include/faust/dsp/llvm-dsp.h:81:14: note:   no known conversion for argument 2 from 'double* [1999]' to 'float**'
```

I compiled faust and generated libfaust.a, but from the above message I think FAUSTFLOAT are considered as float.

**Comment by sletz** [comment]
Is that wen compelling `embedded/faustcsound/faustcsound.cpp` ? If yes then try to add  `#define FAUSTFLOAT double `at the dewing of the file like:

```
#define FAUSTFLOAT double
#include "csdl.h"
#include "faust/dsp/llvm-dsp.h"
#include "faust/gui/UI.h"
#define MAXARG 40
```

**Comment by maurocsound** [comment]
I compiled the file "faustgen.cpp' inside the Opcodes dir of the Csound project from github... Maybe they are the same thing, named differently?

**Comment by sletz** [comment]
Possibly. Where is that file? Any link?

**Comment by maurocsound** [comment]
https://github.com/csound/csound/blob/develop/Opcodes/faustgen.cpp

Anyway, shouldn't I build libfaust.a with FLOATFAUST as "double" instead as "float" to make the generated dll work with the actual Csound Windows binaries?

**Comment by sletz** [comment]
1) ok for the file, use the same `#define FAUSTFLOAT double` line

2) "shouldn't I build libfaust.a with FLOATFAUST as "double"..") : nope, FLOATFAUST is not used in libfaust (that is in the compiler). This is an architecture file issue only.

**Comment by maurocsound** [comment]
It appears to work, the plugin dll is loaded when i run the Csound binary, but when I create a Csound instrument with a _faustcompile_ opcode inside it, and then I run it, Csound goes in crash. Strangely, _faustgen_ appear to work without problems.
Follows a little Csound program that goes in crash:

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
	a1 init 1
	a2 init 2
	a3 init 0

	; THE FOLLOWING MAKES Csound CRASH:
	ihandle faustcompile "process=+;", "-vec -lv 1"
	idsp, a3 faustaudio ihandle, a1, a2

	; THIS WORKS WELL: (of course, you will have to comment the two lines above)
	idsp, a3 faustgen "process=+;", a1, a2

	printk 1, a3[0]
endin

</CsInstruments>
<CsScore>
i1 0 2
</CsScore>
</CsoundSynthesizer>
```

I noticed that the Csound file I compiled to make faustops.dll is not updated from many years. Could the problem be related to the way Csound interfaces with the faust library? Anyway I reported the problem in the csound issues section of github. 

Thank you very much for your support!

**Comment by sletz** [comment]
1) do you have any crash log?
2) where is the "csound issues section of github." so that I can follow it there ?

**Comment by maurocsound** [comment]
Hi, there were some thread lock problems in the faustgen.cpp code. Victor Lazzarini is working on it and I'm testing... You can follow the discussion here: https://github.com/csound/csound/issues/969
