### ISSUE TITLE
MSVC build instruction query

### ISSUE THREAD

**Issue by stekyne** [grame-cncm/faust#209]
Hi guys,

The build documentation mentions the following: 

"you must have llvm-config available from the command line.
LLVM supported versions starts at 3.8, older versions may work but are not supported anymore.
using LLVM 5.0.0 works on every platform, you can get binary distributions from the LLVM Releases page"

However, I'm not seeing the llvm-config utility in the prebuilt Windows binaries. This mailing list email seems to confirm that: http://lists.llvm.org/pipermail/cfe-dev/2016-January/046703.html 

Has anyone found an easy solution to this? Might need to alter the documentation to reflect this if not. The alternative is to build LLVM locally which is a bit of a pain!

**Comment by dfober** [comment]
> Le 28 août 2018 à 22:47, Stephen Kyne <notifications@github.com> a écrit :
> 
> Hi guys,
> 
> The build documentation mentions the following:
> 
> "you must have llvm-config available from the command line.
> LLVM supported versions starts at 3.8, older versions may work but are not supported anymore.
> using LLVM 5.0.0 works on every platform, you can get binary distributions from the LLVM Releases page"
> 
> However, I'm not seeing the llvm-config utility in the prebuilt Windows binaries. This mailing list email seems to confirm that: http://lists.llvm.org/pipermail/cfe-dev/2016-January/046703.html <http://lists.llvm.org/pipermail/cfe-dev/2016-January/046703.html>
> 
> Has anyone found an easy solution to this? Might need to alter the documentation to reflect this if not. The alternative is to build LLVM locally which is a bit of a pain!
> 
That’s the solution (unless someone knows where to find a binary distribution that includes the dev tools). It takes time but it’s not so painful. 
LLVM is cmake based and it’s easy to target your dev environment. It includes also a package target so that you can next get a standard installation. 

The readme.md file has been update to reflect this issue.

—
Dom

**Comment by pierreguillot** [comment]
If it can help you:
Here is what I did to compile LLVM 6.0.0 for Win64 with the static runtime library:
```
cd llvm-6.0.0.src && mkdir build && cd build
cmake .. -G "Visual Studio 14 2015 Win64" -DLLVM_USE_CRT_DEBUG=MTd -DLLVM_USE_CRT_RELEASE=MT -DLLVM_BUILD_TESTS=Off -DCMAKE_INSTALL_PREFIX="./llvm-x64-mt" -Thost=x64
cmake --build . --target ALL_BUILD (--config Debug/Release)
cmake --build . --target INSTALL (optional)
```
I think by default, LLVM is linked against the dynamic runtime library, the equivalent would be to use:
```
cd llvm-6.0.0.src && mkdir build && cd build
cmake .. -G "Visual Studio 14 2015 Win64" -DLLVM_USE_CRT_DEBUG=MDd -DLLVM_USE_CRT_RELEASE=MD -DLLVM_BUILD_TESTS=Off -DCMAKE_INSTALL_PREFIX="./llvm-x64-mt" -Thost=x64
cmake --build . --target ALL_BUILD (--config Debug/Release)
cmake --build . --target INSTALL (optional)
```

If you want to compile faustlib with the static runtime library, you have to "force" CMAKE to use it. So in the backend file you can add something like: 
```
## For Windows use static runtime instead of default dynamic runtime
if(MSVC)
    set(CMAKE_CXX_FLAGS_RELEASE "/MT"  CACHE STRING  "FORCE CXX FLAGS" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "/MT"  CACHE STRING  "FORCE C FLAGS" FORCE)
    set(CMAKE_CXX_FLAGS_DEBUG "/MTd"  CACHE STRING  "FORCE CXX FLAGS" FORCE)
    set(CMAKE_C_FLAGS_DEBUG "/MTd"  CACHE STRING  "FORCE C FLAGS" FORCE)
    set(CompilerFlags
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS CMAKE_C_FLAGS_DEBUG CMAKE_C_FLAGS_RELEASE)
    foreach(CompilerFlag ${CompilerFlags})
      string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
    endforeach()
endif()
```
The compilation of LLVM lasts more than 1h. I can't do it on CI services so I uploaded prebuilt binaries on Github. You can use them if you want but I can't ensure you that I will keep them there. 
LLVM with the static runtime library: https://github.com/CICM/pd-faustgen/releases/tag/v0.0.0
LLVM with the dynamic runtime library: https://github.com/Musicoll/KiwiDependenciesPrebuilt/releases

**Comment by stekyne** [comment]
Thanks, that's really helpful. It should be enough to get me going. I'm trying to get the Windows build of Csound to include these binaries now. I may end up hosting the binaries for the CI build to pull down later. 

Cheers
