### ISSUE TITLE
CMake compile with /MT instead of /MD

### ISSUE THREAD

**Issue by pierreguillot** [grame-cncm/faust#210]
With MSVC, you can choose which C runtime library (CRT) to use:  the dynamic library (default) using the compile flag /MD for release or /MDd for debug or the static library using the compile flag /MT for release or /MTd for debug. It would be great if we could use a CMake option to setup which one to use like for LLVM for example:
`-DLLVM_USE_CRT_DEBUG=MTd -DLLVM_USE_CRT_RELEASE=MT` (see the file lib/cmake/llvm/ChooseMSVCCRT.cmake in the LLVM distribution for further information or [here](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/ChooseMSVCCRT.cmake)). 
This [thread](https://stackoverflow.com/questions/14172856/cmake-compile-with-mt-instead-of-md) could help also.

**Comment by dfober** [comment]
That’s done. You can update your repo.
See the README-MSVC.md file for details.

**Comment by pierreguillot** [comment]
Tested [here](https://github.com/CICM/pd-faustgen/blob/97133ec3ad0c569a2330238d31682985790a804b/FaustLib.cmake#L12) and it works perfectly! Thanks

I think there is a missing space [here](https://github.com/grame-cncm/faust/blob/master-dev/build/CMakeLists.txt#L28)
`option ( MSVC_STATIC		"Use static runtimes withMSVC" off)`
instead of 
`option ( MSVC_STATIC		"Use static runtimes with MSVC" off)`

**Comment by dfober** [comment]
fixed
