### ISSUE TITLE
DspFaust.h should use std::string and not just string

### ISSUE THREAD

**Issue by bgaster** [grame-cncm/faust#212]
The code:

#if DYNAMIC_DSP
        DspFaust(const string&, int, int);
#endif

should be replaced with:

#if DYNAMIC_DSP
        DspFaust(const std::string&, int, int);
#endif

To avoid having to have std namespace open.

**Comment by bgaster** [comment]
This is under architecture/api/DspFaust.h

**Comment by sletz** [comment]
Thanks for reporting. I'll need to also double check several other public headers.

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/92f2273504ee98439ae18f0c7bcb1b1bace472d5.
