### ISSUE TITLE
simple example compilation

### ISSUE THREAD

**Issue by simdax** [grame-cncm/faust#228]
Hello

Trying to build the noise.dsp example, I have a strange error

![image](https://user-images.githubusercontent.com/2458806/46744468-82290380-ccab-11e8-8dae-890a83873cbd.png)

the file /usr/include/stdlib.h exists, so I imagine it's a compile time path problem ?

**Comment by sletz** [comment]
On which OS? Can you possibly post the failling noise.cpp file ?

**Comment by simdax** [comment]
OK the point is the Arch Linux version of the faust package. Sorry about that. 

Arch linux version is something about 2.5
