### ISSUE TITLE
sound2faust doesn't get installed

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#230]
With the cmake build system, sound2faust (from tools/sound2faust) doesn't get installed any more, even if it is built (e.g., with the `world` target). This is bad because, in particular, it breaks the build of FaustLive on Darwin, which tries to copy the binary from the existing Faust installation when building the application bundle.

I noticed this while updating the Faust packages in MacPorts to the latest from git. Currently I work around this by patching the FaustLive Build/Darwin/Makefile to *not* copy the sound2faust executable from Faust if it doesn't exist, but I'm not sure how much havoc this wreaks. In any case, it would be nice if this could be fixed, so that sound2faust gets installed again if it is built.

**Comment by dfober** [comment]
next week...

**Comment by agraef** [comment]
Ok, thanks. Take your time. :)

**Comment by dfober** [comment]
should be fixed, can you test?

**Comment by agraef** [comment]
Looking good, thanks! I already refreshed the JGU Arch, Ubuntu and MacPorts packages to the latest revision (MacPorts is still pending, but should soon be live).
