### ISSUE TITLE
Building `HTTPDFaust`

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#232]
Building `HTTPDFaust` (`faust/architecture/httpdlib`) using the `cmake` file in `faust/architectures/httpdlib/cmake/CMakeLists.txt` does not link in the files that include the definition of the `extern` variables `jsscripts`, `jsscripts_len`, `stylesheet`, `stylesheet_len`. This means that when linking against the generated `.so` file, you will most likely end up with unresolved symbols.

However, when building using `faust/architectures/httpdlib/src/Makefile`, this links in the files in `hexa/` which provide definitions for the above mentioned variables.

What is the expected proper way of compiling this? It's confusing.

Tested on Linux Debian Stretch arm-v7

**Comment by sletz** [comment]
Yes. We'll need to adapt the cmake way for that. Hopefully @dfober can have a look next week.

**Comment by giuliomoro** [comment]
Great. While we are here, could we think about what would be the best way not to have those css and js files baked into the lib's binary?

What about installing them in `/usr/local/share/faust/httpdlib/static/` or something like that, so that the user can easily edit the default theme? Current workflow (edit css->recompile library->install) seems a bit complicated...

**Comment by dfober** [comment]
The code containing the the extern variables `jsscripts, jsscripts_len, stylesheet, stylesheet_len` is included with the new cmake system. If you don't get it, it might be that the corresponding source is not present (in `architecture/httpdlib/src/hexa/`, `jsscripts.cpp` and `stylesheet.cpp`). 
Normally this should not be the case: this code is dynamically generated but is now part of the repository (since the new cmake system).

**Comment by giuliomoro** [comment]
again, using the cmake file `faust/architectures/httpdlib/cmake/CMakeLists.txt` results in the files in `architecture/httpdlib/src/hexa/` not to be linked in, even if they do exist.
Here's a fuller log:

```
root@bela:~/faust/architecture/httpdlib/build# cmake ../cmake
-- The C compiler identification is Clang 3.9.1
-- The CXX compiler identification is Clang 3.9.1
-- Check for working C compiler: /usr/local/bin/distcc-clang
-- Check for working C compiler: /usr/local/bin/distcc-clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/distcc-clang++
-- Check for working CXX compiler: /usr/local/bin/distcc-clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generates a dynamic library - Use -DSTATIC=yes to change.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/faust/architecture/httpdlib/build
root@bela:~/faust/architecture/httpdlib/build# make -j3
Scanning dependencies of target HTTPDFaust
[ 10%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/msg/Message.cpp.o
[ 15%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/httpd/Address.cpp.o
[ 15%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/HTTPDControler.cpp.o
[ 21%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/httpd/HTTPDServer.cpp.o
[ 26%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/httpd/HTTPDSetup.cpp.o
[ 31%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/nodes/FaustFactory.cpp.o
[ 36%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/nodes/FaustNode.cpp.o
[ 42%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/nodes/MessageDriven.cpp.o
[ 47%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/nodes/RootNode.cpp.o
[ 52%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsoncontrol.cpp.o
[ 57%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsonfactory.cpp.o
[ 63%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsonfaustui.cpp.o
[ 68%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsongroup.cpp.o
[ 73%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsonroot.cpp.o
[ 78%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/json/jsonui.cpp.o
[ 84%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/html/htmlfactory.cpp.o
[ 89%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/html/htmlpage.cpp.o
[ 94%] Building CXX object CMakeFiles/HTTPDFaust.dir/root/faust/architecture/httpdlib/src/html/htmlui.cpp.o
[100%] Linking CXX shared library libHTTPDFaust.so
[100%] Built target HTTPDFaust
root@bela:~/faust/architecture/httpdlib/build# cp libHTTPDFaust.so /usr/local/lib/libHTTPDFaust.so
```
so the files are not built above. Just to give it a chance, I relink a program that uses `libHTTPDFaust` and  I get
```
/usr/local/lib/libHTTPDFaust.so: undefined reference to `jsscripts_len'/usr/local/lib/libHTTPDFaust.so: undefined reference to `stylesheet_len'
/usr/local/lib/libHTTPDFaust.so: undefined reference to `stylesheet'
/usr/local/lib/libHTTPDFaust.so: undefined reference to `jsscripts'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dfober** [comment]
Oups ! You're using an obsolete cmake file. Use the build system in the `build` folder.
Obsolete cmake and make files have been removed.

**Comment by giuliomoro** [comment]
great thanks, that works. Is there a reason why only the static library is generated and not the shared one?

**Comment by giuliomoro** [comment]
Actually: `make help` gives:
```
 'httpdynamic': builds the HTTPD library in dynamic mode (requires confighttpdynamic).
```
but then below, `confighttpdynamic` is deprecated.

So I can indeed build the shared library with:
```
make confighttpdynamic
make httpdynamic
```

but this is deprecated. So I guess a better question is: what is the recommended way of building `libHTTPFaust.so` ?

Thanks

**Comment by dfober** [comment]
you can generate the dynamic library too. See  the build/README.md file for more details about the compiled targets.

**Comment by dfober** [comment]
the deprecated targets have been removed. Use the target config files to specify your targets.
Note that the root level Makefile has an `all` and a `most` target that build everything (including the static and dynamic libraries).

**Comment by giuliomoro** [comment]
I must admit I get confused by the `targets/` files and the docs. It seems that in order to specify a subset of all the targets I'd need to create my own file in `targets/`. However, it seems that with 06f99874df6c8ecd3b85168f6d3063b3a1452c07 I can simply do

```
make httpdynamic
```

and that works fine. So thanks for that.

Note however that `make help` still returns
```
Targets that require specific configs:
 'staticlib'  : builds the libfaust library in static mode (requires configstatic).
 'dynamiclib' : builds the libfaust library in dynamic mode (requires configdynamic).
 'oscdynamic' : builds the OSC library in dynamic mode (requires configoscdynamic).
 'httpdynamic': builds the HTTPD library in dynamic mode (requires confighttpdynamic).
```

but those `requires` should probably be removed?

**Comment by dfober** [comment]
> It seems that in order to specify a subset of all the targets I'd need to create my own file in targets/.

Right, you can use your own targets file (and backends files too).  

Regarding `make httpdynamic`: it works provided that the http dynamic library is on in your targets file. Note that target files simply set cmake variables. The one that includes (or reject) the dynamic httpd library is HTTPDYNAMIC. 
Actually the help target is not really up-to-date. That's fixed now.

**Comment by dfober** [comment]
> However, it does work (even after running find faustdir -type d -name CMakeFiles -exec rm -rf {} \; to try and remove all of the cmake cache)

not on my side:
```
$ make httpdynamic
cmake --build faustdir --target httpdynamic --config Release -- -j 4
make[1]: *** No rule to make target `httpdynamic'.  Stop.
make: *** [httpdynamic] Error 2
```
cmake is a state machine (and sometimes that could be a nightmare) and to make sure you remove any previous state, you can safely delete the entire `faustdir` folder.

Note also that the first call to `make` generates your project (in your case, a makefile). To re-generate your project (e.g. with different targets), you have to call the `cmake` target. (just hope that I don't add more confusion :-)
Have a look at the Makefile, it'll likely be more evident.

**Comment by giuliomoro** [comment]
right thanks.

So it seems I always have to run
```
rm -rf faustdir/
```
in order for an updated `TARGETS=` to be applied.
e.g.:
```
$ make httpdynamic
... fails miserably
$  make TARGETS=all.cmake httpdynamic
... still says no rule to make target `httpdynamic`
$ rm -rf faustdir
$ make TARGETS=all.cmake httpdynamic
... finally works
```
maybe it's worth adding a 
```
distclean:
	rm -rf $(FAUSTDIR)
```
target to `build/Makefile`?

**Comment by dfober** [comment]
That's done (the distclean target)

Regarding targets change, the following call should work:
~~~
make cmake TARGETS=yourtargets.cmake
~~~
