### ISSUE TITLE
Trying to get it to work in unity

### ISSUE THREAD

**Issue by benammarkarim** [grame-cncm/faust#235]
I exported the plugin unity package using faust2unity then i attached the faustplugin.cs to an audiosource game object. i figured out after that i have to press initialization button but whenever i do that i get this error message: 

NullReferenceException: Object reference not set to an instance of an object
FaustUtilities_lead.FaustUI.getUI (System.Int32 i) (at Assets/Scripts/FaustUtilities_lead.cs:374)
FaustUtilities_lead.FaustPlugin_Editor.OnInspectorGUI () (at Assets/Scripts/FaustUtilities_lead.cs:53)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1599)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by sletz** [comment]
Which version of Unity ? Running on Windows ?

**Comment by benammarkarim** [comment]
Windows 10, running Unity 2018.3.0b2

**Comment by benammarkarim** [comment]
I managed to fix this, however, there is no sound when I start the project, no messages appear in the console.
May I get full steps to include sound in unity ? I probably forgot something...

**Comment by sletz** [comment]
"There was a problem in FaustUtilities script in the JSON parsing method, some parameters were missing." can you send me the fix? or prepare a pull request again master-dev branch? Thanks.

**Comment by sletz** [comment]
Or simply send me the modified FaustUtilities_lead.cs file?

**Comment by sletz** [comment]
Thanks for the file. But I see this is actually the manually modified file which is generated by the `faust2unity` script from this template version : https://github.com/grame-cncm/faust/blob/master-dev/architecture/unity/FaustUtilities_template.cs (with some renaming, code insertion...)

It would be actually easier if you can modify the original  `FaustUtilities_template.cs`, and send the diff, or the modified template file itself. 

Thanks again.

**Comment by sletz** [comment]
I reconstructed the diff, is this correct ?

<img width="1273" alt="capture d ecran 2018-11-02 a 18 49 49" src="https://user-images.githubusercontent.com/1430487/47931792-29c2db80-ded0-11e8-8187-fd887b27c398.png">

**Comment by sletz** [comment]
Done in my local git, thanks.
