### ISSUE TITLE
Wrong dll name in FaustUtilities Unity script on linux

### ISSUE THREAD

**Issue by Nagasaki45** [grame-cncm/faust#240]
A binary on linux with the name `libFaustPlugin_whatever.so` should be loaded into Unity with `DllImport("FaustPlugin_whatever")`. At the moment the automatically generated `FaustUtilities_whatever.cs` script loads this binary with `DllImport("libFaustPlugin_whatever")` when runs in the editor. Here's the source of the issue:

https://github.com/grame-cncm/faust/blob/6d00c06c39eb41312ea216bf1d0a50fc70c74045/architecture/unity/FaustUtilities_template.cs#L247-L255

`PLUGNAME` is replaced by `libFaustPlugin_whatever` while, for linux, it should be replaced by `FaustPlugin_whatever`.

A simple workaround for now is to just edit the file manually. Then it works.

BTW, I'm making my first steps with faust today and so far it's a beautiful piece of software. Thanks for that!

**Comment by Nagasaki45** [comment]
What a fast response. Thanks!

I'm checking it with the new commit but it still tries to load the wrong binary (`libFaustPlugin...`). I will be more than happy to help with the debugging. Please let me know if I can be of any help.

**Comment by sletz** [comment]
Have you correctly installed the new version ? (`make && sure make install`)

Testing  here with ` faust2unity -source noise.dsp`, I get this in the generated FaustUtilities_noise.cs file

```
   #if UNITY_STANDALONE_OSX || UNITY_STANDALONE_WIN || UNITY_EDITOR || UNITY_WSA || UNITY_WSA_10_0 || UNITY_IOS
        const string _dllName = "libFaustPlugin_noise";
        #elif UNITY_ANDROID || UNITY_STANDALONE_LINUX 
        const string _dllName = "FaustPlugin_noise";
        #else
        Debug.LogError("Architecture not supported by the plugin");
        #endif

```

This seems correct to me ?

**Comment by Nagasaki45** [comment]
The installation is correct. I can see the changes in the script that was generated (`UNITY_STANDALONE_LINUX` on the `elif` line).
Looking at the fix again I think I wasn't supper clear with my original description of the problem. The issue happens in the unity editor! I haven't even dried to build the project until now. Now, with the fix, the project doesn't run in the editor but is built fine.
Are these constant coming from faust or from unity? If from faust a possible solution could be to spit `UNITY_EDITOR` into `UNITY_EDITOR_LINUX` and `UNITY_EDIT_OTHER` or something along these lines.

**Comment by sletz** [comment]
The template files are ` FaustUtilities_template.cs` and F`austPolyUtilities_template.cs` in the following folder: https://github.com/grame-cncm/faust/tree/master-dev/architecture/unity

They are manipulated by `faust2unity` (https://github.com/grame-cncm/faust/blob/master-dev/tools/faust2appls/faust2unity)

Can you try to possibly adapt the `faust2unity` script yourself? (then re-install it with `sudo make install`), and if success, create a pull request against master-dev branch? This may be faster than those "blind" commit I can only do myself...
