### ISSUE TITLE
#include "effect.cpp" ... why?

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#245]
I see that many architectures have a line `#include "effect.cpp"`. Why is that? Many build system will try to build `effect.cpp` into `effect.o` and then link it together alongside the other `.o` files generated by the other `.cpp` files, including the one that included `effect.cpp`, leading to duplicated symbol errors at link time.
Why the choice of naming it `effect.cpp` and not `effect.h` ?

**Comment by sletz** [comment]
Right, fixed in https://github.com/grame-cncm/faust/commit/0f48f0ea1f738feaeab1028c120f19e1e8566de6

Can you test and report? Thanks.

**Comment by giuliomoro** [comment]
That seems good, thanks. On second thought, why is there need to fully include that file? Is there a way we could just include a `effect.h` containing forward declarations, and then have the implementation in `effect.cpp` ? This would potentially significantly reduce build times when tweaking effects, as the main `.cpp` file would not need to be rebuilt, in a properly setup build environment (especially with the help of  https://github.com/grame-cncm/faust/issues/248).

**Comment by sletz** [comment]
More complex todo right now I would say...

**Comment by giuliomoro** [comment]
ok, no problem.
