### ISSUE TITLE
POLYDEFS breaks faust2caqt without effect

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#255]
- get latest master
- build something with `faust2caqt` without `-effect`
you will get

this is because this command is called:
```
qmake -project 'QT += widgets printsupport network' CONFIG+=warn_off 'QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.9' INCLUDEPATH+=/tmp/vecnoeffect/build1 'INCLUDEPATH+=/usr/local/include /opt/local/include' 'QMAKE_CXXFLAGS= -Ofast -march=native -DNVOICES=1 -mmacosx-version-min=10.9 -Wno-unused-parameter ' 'LIBS+=-L/usr/local/lib -L/opt/local/lib -framework CoreAudio -framework AudioUnit -framework CoreServices -framework CoreMIDI -framework CoreFoundation   ' HEADERS+=/usr/local/include/faust/gui/faustqt.h 'RESOURCES+= /usr/local/include/faust/gui/Styles/Grey.qrc' '' '' '' 'DEFINES += POLY2' 'DEFINES += MIDICTRL' '' ''
```
so `POLY2` is defined, which is what triggers the inclusion of `effects.h` (I fail to understand why the naming has to be so obscure). I think this line should not be here:
https://github.com/grame-cncm/faust/blob/abe234fc9381418ada226079a72bf28e67720d73/tools/faust2appls/faust2caqt#L70

**Comment by sletz** [comment]
Fixed locally.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/de5ae5d06ec3364b0796c76f220f17af4c42d81f
