### ISSUE TITLE
Bela: `nvoices` is only initialized `#ifdef NVOICES`

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#256]
`nvoices` is only initialized `#ifdef NVOICES` 
https://github.com/grame-cncm/faust/blob/master-dev/architecture/bela.cpp#L425
so that if `POLY2` is defined buy not `NVOICES, then `nvoices` is used uninitalized at row
```
    dsp_poly = new mydsp_poly(new mydsp(), nvoices, true, true);
```

what should `nvoices` be initialized to when `NVOICES` is not defined? It looks like both `nvoices` and `dsp_poly` are needed only when at least one of `NVOICES` and `POLY2` are defined

**Comment by giuliomoro** [comment]
thanks. doesn't compile, I added some inline notes on the commit.

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/f762576a3e3fcfeb383d4e56a939ec2c10457c8b
