### ISSUE TITLE
warning: unused variable

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#259]
Not sure if this outlines any issues in the code generator?

```
faust2bela -tobela -midi -nvoices 2  guitarMIDI.dsp
```
...
```
/root/Bela/projects/guitarMIDI/render.cpp:9888:10: warning: unused variable 'fRec4' [-Wunused-variable]
   float fRec4 = fRec8;
         ^
```
full render.cpp file:
[render.zip](https://github.com/grame-cncm/faust/files/2657033/render.zip)

**Comment by sletz** [comment]
Known issue, in -vec mode the code generator still generates unused variables for some DSP. In the TODO list, but not on top...
