### ISSUE TITLE
soundfile primitive

### ISSUE THREAD

**Issue by blanchemain** [grame-cncm/faust#264]
$: /usr/local/bin/faust2jack   tp1.dsp
tp1.dsp.cpp: In member function ‘virtual void mydsp::instanceResetUserInterface()’:
tp1.dsp.cpp:14572:18: error: ‘defaultsound’ was not declared in this scope
    fSoundfile0 = defaultsound;
Why ?

**Comment by sletz** [comment]
```
faust2jack -h 
faust2jack [-httpd] [-soundfile] [-nvoices <num>] [-effect auto|<effect.dsp>] [-midi] [-osc] [additional Faust options (-vec -vs 8...)] <file.dsp>
Use '-httpd' to activate HTTP control
Use '-soundfile' when compiling DSP using 'soundfile' primitive, to add needed resources
Use '-nvoices <num>' to produce a polyphonic self-contained DSP with <num> voices, ready to be used with MIDI or OSC
Use '-effect <effect.dsp>' to produce a polyphonic DSP connected to a global output effect, ready to be used with MIDI or OSC
Use '-effect auto' to produce a polyphonic DSP connected to a global output effect defined as 'effect' in <file.dsp>, ready to be used with MIDI or OSC
Use '-midi' to activate MIDI control
Use '-osc' to activate OSC control
```

So use `faust2jack -soundfile  tp1.dsp`

**Comment by blanchemain** [comment]
I have
$ /usr/local/bin/faust2jack -soundfile tp1.dsp
Package sndfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `sndfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sndfile' found

I do not have the file sndfile.pc in the faust directory.

**Comment by sletz** [comment]
You'll have to install libsndfile (http://www.mega-nerd.com/libsndfile/) on your machine.

**Comment by blanchemain** [comment]
It's ok.
I am under debian linux and I did not have the libsndfile library.
Now it works.

**Comment by blanchemain** [comment]
Thank you!
