### ISSUE TITLE
faust2caqt is confused by Audio MIDI setup parameters

### ISSUE THREAD

**Issue by giuliomoro** [grame-cncm/faust#268]
In the "Audio MIDI setup" panel, if you selected two different devices for sound INPUT and sound OUTPUT, and the INPUT device has some output channels, a Faust app created with `faust2caqt` will use the INPUT device's outputs first and only then use the OUTPUT device' outputs.
This is on macos 10.11.6 

Steps to reproduce:

patch:
```
import("instruments.lib");
process = 0.001*_ + os.osc(100), 0.002*_  + os.osc(200), os.osc(300), no.noise;
```

If in Audio MIDI setup I set:

built-in out (0in/2out) --- Use this device for sound output
soundflower (2in/2out) --- Use this device for sound input

, and I launch the app compiled with `faust2caqt`, the app (if launched from the terminal) will log : 
```
ins 2
outs 4
```
and it will outputs 1 and 2 to soundflower and outputs 3 and 4 to the built-in out.

Expected behaviour would be:
- the app logs
```
ins 2
outs 2
```
- outputs 1 and 2 go to built-in out
- outputs 3 and 4 go nowhere

**Comment by sletz** [comment]
When the input and output devices are different, the code does "devices aggregation" to internally/programmatically set an unique duplex device. In you case the aggregated device combines outputs from "built-in out" device  and "soundflower" device to create  4 channels output device. 

You can try to create yourself an aggregated device using the "Audio MIDI setup" panel, and you'll see that the same behavior happens. 

I don't think we can do better than the behavior.

**Comment by giuliomoro** [comment]
I see. This is misleading, though, as the user will be confused by the sound not making its way through the system audio output. After all, many other applications (e.g.: Quicktime, Chrome,) are able to use different soundcards for inputs and outputs, and to obey to the settings in Audio MIDI setup, so the user would expect this one to be the same.

A proposal of what I consider a better behaviour:
the `faust2caqt`-generated application shall still internally create the aggregate device, but when the time comes to play back the audio, it shall send 0s to the output channels that belong to the input interface, and send the first audio output from Faust to the first output of the device selected as "OUTPUT" (this of course only if INPUT and OUTPUT are two distinct devices).
What do you think?

**Comment by sletz** [comment]
Using separated device is more difficult at code level : your code basically has to handle 2 separated audio callback with all kind of possible clock drift issues. This is the "raison d'être "of the aggregated device concept win the first place...  

I'll check if the aggregation code itself can possibly ignore some of the unwanted inputs/outputs.

**Comment by sletz** [comment]
Fix to test https://github.com/grame-cncm/faust/commit/80bfc926e77cbdb5b08b8fed44902145caec4714.

**Comment by giuliomoro** [comment]
Almost! I tested with the fix in https://github.com/grame-cncm/faust/pull/269/commits/f4a0c63ccf7ab4e0bf0d6ba0f47b816b78b0d79a and it works for me. Thanks!
