### ISSUE TITLE
faust2octave fails on linux

### ISSUE THREAD

**Issue by miccio-dk** [grame-cncm/faust#270]
As per title; here's the incriminating error:
```
user@my-laptop:~/path/to/file$ faust2octave file.dsp
file.dsp.cpp: In member function ‘virtual bool CMDUI::run()’:
file.dsp.cpp:302:29: error: ‘getchar’ was not declared in this scope
         while ((c = getchar()) != 'q') {
                             ^
```

I've gotten the file to compile by including `<stdio.h>` higher up in the .cpp (was only included from line ~800)

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/3f86c1110d17c0c7b47495eea1f1b3911782f06e,  (master-dev branch) can you try and report ?

**Comment by miccio-dk** [comment]
sorry for the delay, just recompiled and can confirm it works now! :)
