### ISSUE TITLE
faustgen~ compiled with cmake on OS X still has a dependency with LLVM

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faust#271]
```
otool -L faustgen~ 
faustgen~:
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.9.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@executable_path/../Frameworks/MaxAPI.framework/Versions/A/MaxAPI (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/MaxAudioAPI.framework/Versions/A/MaxAudioAPI (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/libexec/llvm-7.0/lib/libLLVM.dylib (compatibility version 1.0.0, current version 7.0.0)
	/opt/local/lib/libffi.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (comp
```

**Comment by dfober** [comment]
You link with the dynamic llvm lib, that's the reason.
on my side I don't have the problem:
otool -L faustgen~ 
faustgen~:
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.31.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@executable_path/../Frameworks/MaxAPI.framework/Versions/A/MaxAPI (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/MaxAudioAPI.framework/Versions/A/MaxAudioAPI (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)

I guess you're using llvm from macport. With llvm from llvm.org, only static libraries are distributed.
