### ISSUE TITLE
Makefile lists the 'httpd' target which isn't defined

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#274]
I believe that previous versions were building ```libHTTPDFaust.so``` based on this target, which was in addition to the ```all``` target. Now, in version ```2.14.4``` it seems to be defunct.

It should be either implemented, or removed entirely. I suggest it should be implemented as it was before, since it incurs an additional dependency ```libmicrohttpd``` that isn't otherwise needed.

**Comment by dfober** [comment]
Please, indicate the command line you're running (I guess make), including where you run this command (I guess from the project root folder) and the target as well.
(Just to make sure I understand the point)

**Comment by yurivict** [comment]
Yes, I run GNU make from the root folder. The target is ```all``` and ```all httpd```, with the expectation that ```httpd``` would add httpd parts.
