### ISSUE TITLE
faustlive related issue maybe?

### ISSUE THREAD

**Issue by jdsierral** [grame-cncm/faust#279]
Hi it seems like a couple of days some renaming of files was done and now I'm unable to compile faustlive from source. Specifically I'm having problems with

`faust/architecture/faust/gui/QTUI.h`

which was previously named

`faust/architecture/faust/gui/faustqt.h`

So while compiling faustlive it complains about not finding the that header file.
I presume it is more a matter of updating faustlive's repo according to the new naming conventions.

Hope this helps

JuanS

**Comment by sletz** [comment]
Use the FaustLive dv branche for now.

**Comment by jdsierral** [comment]
Thanks so much. I should have checked that XD
