### ISSUE TITLE
being new to faust 2 - page 20 tutorial fails

### ISSUE THREAD

**Issue by MarcWeber** [grame-cncm/faust#28]
http://faust.grame.fr/images/faust-tutorial2.pdf page 20 has wrong imports and should be updated

magnetophon told me about this fix replacing the first lines.

From library pdf I tried adding my own imports, but compilation failed at .cpp stage with a warning (it did run though).

```
    import("stdfaust.lib");

    t = hslider("interpolation time", 0.001, 0, 0.01, 0.0001);
    c = hslider("pan", 0.05, 0, 1, 0.01): si.smooth(ba.tau2pole(t));
````

**Comment by sletz** [comment]
Do you have the "compilation failed at .cpp stage" precise error message ?
