### ISSUE TITLE
Error using faust2max6 on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by glocq** [grame-cncm/faust#282]
Trying to compile a .dsp into a max executable yields:
```
fatal error: 'ext.h' file not found
```

**Comment by sletz** [comment]
You will have to:

- install Max/DSP SDK
- edit the faust/tools/faust2appls/faustpath  script to properly setup the $MAXSDK variable
- install again (sudo make install)

**Comment by glocq** [comment]
Thank you for this fast answer! Is there documentation somewhere where I could have found this info?

**Comment by sletz** [comment]
Not yet ((-;

**Comment by glocq** [comment]
Awesome, this will certainly be helpful to other people :)

**Comment by noahneumark** [comment]
I'm not sure if these instructions are still applicable, but it didn't work for me. I'm still getting the fatal error: 'ext.h' file not found. I'm on Big Sur 11.7.4. I installed the latest Max/MSP SDK (v 8.2.0) to /usr/local/include/c74support/ which is the default path.
