### ISSUE TITLE
infinite loop in Heap2str

### ISSUE THREAD

**Issue by Fr0stbyteR** [grame-cncm/faust#291]
I am reviewing codes in webaudio-wasm-standalone-wrapper, in which I found the function `Heap2Str` has some problem.

    while (buf[i] !== 0) {
        str += String.fromCharCode(buf[i++]);
    }

as in js, buf[i] beyond its length returns `undefined` instead of 0.
Do we use this function ? if not I will remove it.

**Comment by sletz** [comment]
OK, then please correct it (even if we don't use it right now, we can keep the code).

**Comment by Fr0stbyteR** [comment]
Sure, it will be corrected in my next pull request.
