### ISSUE TITLE
parser MAKE

### ISSUE THREAD

**Issue by alessandrostone** [grame-cncm/faust#296]
Hi :)

Is this line correct in faust/compiler/parser/Makefile ?
      
`$(LEX) -I -ofaustlexer.cpp $(OPTIONS) faustlexer.l`

should it be:

`$(LEX) -I -o faustlexer.cpp $(OPTIONS) faustlexer.l`

 maybe?

**Comment by sletz** [comment]
Maybe ((-; but its actually working like that !
