### ISSUE TITLE
FR: Include libfaust dynamic library with releases

### ISSUE THREAD

**Issue by olilarkin** [grame-cncm/faust#297]
For iPlug2's faust support it would be great just to tell people "install the latest faust release", rather than maintaining a separate faust build in the iPlug2 dependencies folder. If the macOS and windows dmg/installer included the dylib/dll i think i could do this.

**Comment by olilarkin** [comment]
oh i see you do include the .dylib in the dmg

**Comment by sletz** [comment]
@olilarkin is is fixed? Can it be closed ?

**Comment by dfober** [comment]
I think so. The dynamic lib is now included in the macos and windows packages.

**Comment by olilarkin** [comment]
thanks
