### ISSUE TITLE
buildUserInterfaceCDSPInstance not working since recent commits

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#298]
It works at f16c6ad9c34cc94f5df1a7987671a09dd1203c99 but not at 35980866c9569fe88e58281f388e4811fa3973bf - is there something new to do ?

From the looks of it I would suspect commit 6cfc7df029067a84f73d8c59af8e869883516d46 which seems to have changed a bunch of UI stuff.

**Comment by sletz** [comment]
Crash? What else?

**Comment by jcelerier** [comment]
hmm, actually even this simple code does not work anymore : 

```
#include <faust/dsp/llvm-c-dsp.h>
#include <iostream>
#include <cassert>

int main(int argc, const char** argv)
{
    char err[4096] = {};
    auto fac = createCDSPFactoryFromString(
                "score",
                "process = +;",
                argc, argv, "", err, -1);
    assert(fac);
}
```

**Comment by sletz** [comment]
Which platform?

**Comment by sletz** [comment]
I think using argc/argv stuff in incorrect in this case. This https://github.com/grame-cncm/faust/blob/master-dev/tests/llvm-tests/llvm-test.c works.

**Comment by sletz** [comment]
@jcelerier any new on that? Can it be closed ?

**Comment by jcelerier** [comment]
yes, like this it works on the latest master-dev commit ! thanks.
