### ISSUE TITLE
 llvm_dsp_factory_aux::gLLVMFactoryTable apparently not protected in ~llvm_dsp::~llvm_dsp

### ISSUE THREAD

**Issue by kmatheussen** [grame-cncm/faust#306]
https://github.com/grame-cncm/faust/blob/4ccd394570b2772bba86f1464bf31162dc40a917/compiler/generator/llvm/llvm_dsp_aux.cpp#L333

Shouldn't line 333 and 334 be switched?

**Comment by kmatheussen** [comment]
Another thing, is the only purpose of the lock to protect "llvm_dsp_factory_aux::gLLVMFactoryTable"? In case, perhaps we can change the destructor to
```cplusplus
llvm_dsp::~llvm_dsp()
{
    {
        TLock lock(llvm_dsp_factory_aux::gDSPFactoriesLock);
        llvm_dsp_factory_aux::gLLVMFactoryTable.removeDSP(fFactory, this);
    }

    // Used in -sch mode
    fFactory->getFactory()->fDestroy(fDSP);

    if (fFactory->getMemoryManager()) {
        fFactory->getMemoryManager()->destroy(fDSP);
    } else {
        // LLVM module memory code
        free(fDSP);
    }
}
```
?

**Comment by sletz** [comment]
The lock is supposed to protect all the code, so yes  333 and 334 should be switched.
