### ISSUE TITLE
faust2supercollider: complex plugins crash scsynth while booting

### ISSUE THREAD

**Issue by LFSaw** [grame-cncm/faust#31]
I try to fix the JPVerb and Greyhole plugins and have the strange behaviour that the plugins compile fine but the server crashes immediately while booting. I assume this is due to an increased amount of memory allocated (?) since smaller FAUST plugins such as

```
import("stdfaust.lib");
process = _,_;
```

compile and run just fine.

Help much appreciated.

This is related to https://github.com/supercollider/sc3-plugins/issues/133

**Comment by LFSaw** [comment]
I put the complete (and compiling in faust and faustlive) dsp files here: https://gist.github.com/LFSaw/17a6125b113cd420eaed104a10653b20

**Comment by sletz** [comment]
We fixed some memory related issues some month ago. What Faust version are you using? I suggest using the GIT master branch.

**Comment by LFSaw** [comment]
I am on current master: ce5f468

**Comment by LFSaw** [comment]
I added the crash report and build/reproduce instructions to the gist (see above).
Apparently, it is a seg-fault:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fff5e06b9f8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
```

**Comment by sletz** [comment]
This object takes a lot of heap memory (something like 8923344 bytes) as well as static global memory taken by the prime_delays table (which take 1302 integer).  Could the static global memory size be the issue?

**Comment by LFSaw** [comment]
good point but the previous version (from some 4 years ago) used to work... and I did not change anything in the dsp file despite integrating the primes into the dsp file rather than having them as an external c-header function.

also, increasing memory to the server by

```
s.options.memSize_(65536 * 4); // in kilobyte
```

did not do the trick... Is the memory allocated at scsynth startup? AFAIK not, that is only where the interface table (holding pointers to the UGen plugins) is loaded... (that is my simple understanding, I might be wring here).

**Comment by sletz** [comment]
Are you on OS X?

**Comment by LFSaw** [comment]
yes, as written in the gist

**Comment by sletz** [comment]
Can you test possible fix on master-dev branch ?

https://github.com/grame-cncm/faust/commit/c80f4427d6d47daec8f3bb4b9dd3c74aadbd1aa2

**Comment by LFSaw** [comment]
I checked it out, run the appropriate commands and managed to make it work with the 2 dsp files.
Thanks for the quick fix!

Will this go into the master branch?

Btw., it seems that the mem-check in line 418 of supercollider.cpp is never reached by scsynth (not necessarily hazardous since the `MAlloc` fail is catched otherwise...).

https://github.com/grame-cncm/faust/commit/c80f4427d6d47daec8f3bb4b9dd3c74aadbd1aa2#diff-2e586352d40979469e42302965f6d390R418

**Comment by LFSaw** [comment]
(quick fix as in "speedy", not "hacky" :) )

**Comment by sletz** [comment]
Will be merged in master soon.
