### ISSUE TITLE
Error getting audio input in Chrome

### ISSUE THREAD

**Issue by cristianvogel** [grame-cncm/faust#314]
I'm trying to work in the webbased Faust Editor but I get this error and no audio.
'fuast.grame.fr says Error getting audio input'

Mac OS Mojave / Google Chrome Version 73.0.3683.103

This is my Script - it does not use Audio Input:
 
`import("stdfaust.lib");
freq = hslider("freq",240,50,1000,0.01);
gain = hslider("gain",0.5,0,1,0.01);
gate = button("gate") : en.adsr(0.3,0.01,0.9,3.1);
timbre(f) = os.saw3(f + (5*os.lf_sawpos(0.1)))*0.5 + sy.sawTrombone(f*2 - (7*os.lf_sawpos(0.137)))*0.25 + os.sawtooth(f*3 + (5*os.lf_sawpos(0.139)))*0.125;
process = gain*gate*timbre(freq)*0.5 <: _,_;
effect = dm.zita_light;`

**Comment by sletz** [comment]
Be sure to use the secure version: https://faust.grame.fr/editor/ (with the "S")

**Comment by cristianvogel** [comment]
Ok... but maybe you want to change the Try It Out button on the Faust main web page, to link to the secured version so that people get a better first impression?

**Comment by sletz** [comment]
The link is relative to the main page: so it works correctly if you started from the https://faust.grame.fr/ URL.
