### ISSUE TITLE
OSCFaust missing when build for jack

### ISSUE THREAD

**Issue by wargreen** [grame-cncm/faust#324]
Hi,

When build my .dsp for any jack, i got this issue :
`/usr/bin/ld : ne peut trouver -lOSCFaust`

I use debian SID with faust-common   2.14.4~repack2-1, and faustworks     0.5~repack0-6 
Thank you

**Comment by sletz** [comment]
What version of Faust are you using?

**Comment by wargreen** [comment]
FAUST Version 2.14.4
from debian, package 2.14.4~repack2-1

**Comment by sletz** [comment]
Try to move to latest publied one 2.15.11 : https://github.com/grame-cncm/faust/releases

**Comment by ldegen** [comment]
FYI, ran into the same issue (version 2.15.11 packaged for debian sid). 
I can confirm that the same release build from the source tar ball does not have this issue.

**Comment by sletz** [comment]
Could it be then a debian packaging issue ?

**Comment by ldegen** [comment]
Probably. It seems that the file `$PREFIX/lib/libOSCFaust.a` is simply missing. Can't say why, though, but maybe the package maintainers can have a look. I am just now submitting a bug there.

**Comment by ldegen** [comment]
Here is the ticket in the debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939704

**Comment by umlaeute** [comment]
the problem is fixed in Debian/sid.
It will take ~5 days until the package migrates to Debian/testing.
After that I can (finally) provide a [backport](https://backports.debian.org) of faust-2.15.11 for Debian/buster.

I think *this* issue can be closed (as out-of-scope for upstream)

**Comment by sletz** [comment]
Thanks.
