### ISSUE TITLE
example for slider style:menu doesn't work in Web editor

### ISSUE THREAD

**Issue by Digital-Larry** [grame-cncm/faust#327]
https://faust.grame.fr/doc/manual/index.html#stylemenu-metadata

```
import("stdfaust.lib");
s = hslider("Signal[style:menu{'Noise':0;'Sawtooth':1}]",0,0,1,1);
process = select2(s,no.noise,os.sawtooth(440));
```
Running that on macOS 10.14.5, Google Chrome... the DSP part of the code works fine.  But I just see a slider.

![Screen Shot 2019-06-03 at 5 53 59 PM](https://user-images.githubusercontent.com/3178344/58843715-9948a700-8628-11e9-896f-6149504d7774.png)

**Comment by sletz** [comment]
Yes, menu is not available (yet) on the Web version.

**Comment by Digital-Larry** [comment]
ok... where would I be able to use it?

**Comment by sletz** [comment]
`nentry` is probably usable in the case:

```
import("stdfaust.lib");
s = nentry("Signal[style:menu{'Noise':0;'Sawtooth':1}]",0,0,1,1);
process = select2(s,no.noise,os.sawtooth(440));
			
```

**Comment by sletz** [comment]
Usable in FaustLive https://github.com/grame-cncm/faustlive.

**Comment by Digital-Larry** [comment]
I was thinking about using this ultimately on Bela, because I'd like to have a sound selector that said e.g. "bass, flute, guitar" instead of "0, 1, 2" on the screen (TBD), but I was also interested in having a way to test things outside of the Bela hardware.

**Comment by Digital-Larry** [comment]
I got it to work OK in faust2caqt.  Cool!

**Comment by sletz** [comment]
The new IDE does solve that: https://faust.grame.fr/ide/
