### ISSUE TITLE
worklets and wasm

### ISSUE THREAD

**Issue by lonce** [grame-cncm/faust#329]
I compile to wasmjs-worklets for using Faust with the WebAudio API.
There was a compiler change recently that seems to have broken things:

Code generated with Faust version 2.15.10
Compilation options: wasm-ib, -scal -ftz 2
used a foo-processor.js file:

            let real_url = (this.baseURL === "") ? "foo-processor.js" : (this.baseURL + "/foo-processor.js");
which was then used as an argument to audioWorklet.addModule()

That has been working just fine until quite recently.

Now I see that loading is being done differently.
Code generated with Faust version 2.17.12
Compilation options: -lang wasm-ib -scal -ftz 2

It looks like foo.js no longer uses foo-processor.js, and  tries to fetch foo.wasm
then create an arrayBuffer, call WebAssembly.compile, then instantiate.

However, there is no foo.wasm file to be found and fetched. Should FaustLive now be exporting a wasm file rather than the foo-processor.js file?

Thanks for creating the fumazing environment.
- lonce

**Comment by sletz** [comment]
How are you compiling? Which platform?

**Comment by lonce** [comment]
Faust Live exporting to web/wasmjs-worklet.

**Comment by sletz** [comment]
Until we fix the problem, I guess you'll have to install GitHub master-dev for now and directly use the script, like: `faust2wasm -worklet foo.dsp`

**Comment by lonce** [comment]
Sweet - that produces the wasm file missing from the FaustLive output. Thanks.

**Comment by sletz** [comment]
Remote compiler should be working again.
