### ISSUE TITLE
OSC: root path is 0x00 instead of application name

### ISSUE THREAD

**Issue by cyberic99** [grame-cncm/faust#33]
Hi
I'm following instructions in the tutorial here: http://faust.grame.fr/docs/faust-quick-reference.pdf, on page 52:
`$ cat noise.dsp`
```
declare name "noise";
process = library("music.lib").noise*hslider("level", 0, 0, 1, 0.01);
```
I'm using faust version 3cd7b7c

`faust2jaqt -midi -httpd -osc noise.dsp`

`./noise -xmit 1`

If I use oscdump:
`$ oscdump 5511`
and if I move the slider, I get:
```
Faust OSC version ssssiii "0.96" "-" "'0x00'" "is running on UDP ports " 5510 5511 5512
/0x00/level f 0.000000
/0x00/level f 0.030000
/0x00/level f 0.054700
```
With ```$ oscsend localhost 5510 "/*" s get```
I get:
```
/0x00 si "xmit" 1
/0x00 ss "desthost" "127.0.0.1"
/0x00 si "outport" 5511
/0x00 si "errport" 5512
/0x00/level fff 0.000000 0.000000 1.000000
```
If I try to send OSC messages with the /noise root path, I get nothing back. but with /0x00, it works:

`oscsend localhost 5510 "/noise/level" s get`:
nothing

`oscsend localhost 5510 "/0x00/level" s get`:
```
/0x00/level fff 0.000000 0.000000 1.000000
```

The tutorial states that the root OSC path should be 'noise'

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/c34956ba0af7587df68da2cd53d56481845295b2

**Comment by cyberic99** [comment]
I confirm it is fixed, thanks!
