### ISSUE TITLE
faust2wasm baseURL

### ISSUE THREAD

**Issue by lonce** [grame-cncm/faust#330]
Faust version 2.17.13 
faust2wasm -worklet foo.dsp

the wasmfile fetched in foo.js:

'''const dspFile = await fetch(wasmfile);

needs to be concatenated with 

'''this.baseURL 

in order to fetch from the baseURL argument passed to the constructor.

**Comment by sletz** [comment]
Can you prepare a pull request? Thanks

**Comment by lonce** [comment]
I see you fixed it already. Thanks.
