### ISSUE TITLE
add Faust support for Pyo library

### ISSUE THREAD

**Issue by JeremyKeenan** [grame-cncm/faust#332]
There are instructions here for adding manually:

https://github.com/belangeo/pyo/tree/master/externals

But it would be great to have support for Pyo externals in Faust.

**Comment by sonejostudios** [comment]
oh yes, that would be amazing! :)

**Comment by sletz** [comment]
Do you guys think someone for the Pyo developer community would be willing to help?

**Comment by JeremyKeenan** [comment]
As far as I know Pyo is created and maintained solely by Olivier Bélanger. I did put in a request at the Pyo google group, but I think he is quite busy with adding a new sequencing framework and other things to Pyo. 

Might be worth a Faust developer contacting him directly - I guess he intended the above linked 'externals' folder to facilitate this kind of possibility but unfortunately I don't know what else needs to happen to make this work!
