### ISSUE TITLE
Bugs in the Rust code generation

### ISSUE THREAD

**Issue by programLyrique** [grame-cncm/faust#334]
Rust code generation generates sometimes invalid code:

- `f32::fmod` does not exist anymore in the stdandard library
- `(0..4).rev()` (in some `compute` functions) actually iterates on 3, 2, 1, 0 whereas we actually want 4, 3, 2,1.

For instance in:
```
for j0 in (0..4).rev()  {
	self.fRec27[j0 as usize] = self.fRec27[(j0 - 1) as usize];
}
```
- too many parentheses lead to numerous warnings when compiling
- variable names should be snake case to prevent numerous warnings as well

**Comment by sletz** [comment]
Can you fix that and prepare a PR? Thanks.

**Comment by programLyrique** [comment]
Yes, I have actually fixed it in my version and now I need to clean it a bit.

How I have done it for the first two ones:
- `f32::fmod` : embedour own version. I have transcribed the `fmodf` of the musl C library
- `(0..4).rev()` : just replace it by `4..0` 

I need to work on the two last points.

**Comment by sletz** [comment]
"variable names should be snake case to prevent numerous warnings as well" => if fixed, this has to be a RUST backend only modification
