### ISSUE TITLE
Webaudio worklets: registerProcessor should only be called once

### ISSUE THREAD

**Issue by lonce** [grame-cncm/faust#336]
Regarding: Compiling for the Web with worklets.

Issue: load()ing multiple nodes with the same factory causes a DomException.

Currently, the call to registerProcessor() is made inside the Blob passed to the worklet addModule() which is inside the sound factory load() function. That means that if you call the factory load() function more than once (to create different instances of a node), then registerProcessor() will be called more than once which causes an uncaught DomException.

You can duplicate this behavior if you export a model as FOO from Faust Live for 
webaudiowasm-worklet
then change the FOO.html code to call startNewFOO() twice. 
 
I believe the registerProcessor() method should be called once when the factory code is first imported rather than in response to a function call.

I know .... "pull request." Actually, I could do that for a  "work-around" fix which would would be just to check if AddModule() has been called already and only call if it has not, then await 
its Promise to be resolved. 

- lonce

**Comment by sletz** [comment]
"check if AddModule() has been called already" seems Ok for now. Do you have a PR for that ? ((-;
