### ISSUE TITLE
openFrameworks -of argument returns 'wrong argument'

### ISSUE THREAD

**Issue by JeremyKeenan** [grame-cncm/faust#348]
Running this: faust2api -of exfaust15.dsp
returns 'wrong argument' on OS X 10.13.6

It creates an empty 'dsp-faust' folder.

I have confirmed that with the '-ios' argument it generates a zip file which contains C++  for example - it's the '-of' argument that seems not to work.

**Comment by sletz** [comment]
Hum, I cannot reproduce the use here on 10.11.
The **faust2api**   (https://github.com/grame-cncm/faust/blob/master-dev/tools/faust2appls/faust2api) has quite a similar structure for any `-of,` `-ios` .etc. kind of parameter, that is the one that choose the audio driver. You may have to hack faust2api trying to understand what happens on your system?

**Comment by JeremyKeenan** [comment]
I finally got back to this and reinstalled and tried on another computer - I get this now:

faust2api -of raw_djembe.dsp 

returns:

Your dsp-faust.zip API package for OpenFramework is being created
/usr/local/bin/faust2api: line 119: faust: command not found

Not sure if this gives any clue about what might be happening.

**Comment by sletz** [comment]
"faust: command not found" : it seems faust is not installed correctly, how did you install Faust?
