### ISSUE TITLE
Missing functions with '-lang c'

### ISSUE THREAD

**Issue by mephistopheles-8** [grame-cncm/faust#353]
I'm having issues with code generation using `-lang c` after a recent build: types and functions suffixed with `SIG0` appear to be missing (eg, such as the ones referenced in `classInitmydsp`).   

These types / functions did appear in c code generated with an older version of Faust (`2.17.12`).  The one I'm using is `2.19.1`.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/2e5356b9286e48d2ae2427a321ba1b6f996517fc.

**Comment by mephistopheles-8** [comment]
That was quick -- thanks!
