### ISSUE TITLE
LLV backends with homebrew

### ISSUE THREAD

**Issue by thibaudk** [grame-cncm/faust#355]
trying to build with llvm backends returns the folowing error:

```
 CMake Error at misc/llvm.cmake:70 (string):
   string sub-command STRIP requires two arguments.
 Call Stack (most recent call first):
   CMakeLists.txt:78 (llvm_config)

 CMake Error at CMakeLists.txt:83 (string):
   string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
   command.
```

I am trying to folow the same building steps scritpted here
https://github.com/OSSIA/sdk/blob/master/macOS/faust.sh

but with llvm installed with homebrew.

here is my cmake invocation
```
cmake -C ../backends/llvm.cmake ..   -DCMAKE_BUILD_TYPE=Release   -DINCLUDE_OSC=0   -DINCLUDE_HTTP=0   -DINCLUDE_EXECUTABLE=0   -DINCLUDE_STATIC=1 -DCL=/usr/local/opt/llvm/bin
```

tested on osx 10.14.6

**Comment by dfober** [comment]
Make sure you have llvm-config on your command line. It might be that llvm-config is suffixed with a version number. In this case you can either renamed it or call cmake with `-DLLVM_CONFIG=llvm_config_name_or_path`. In your case, it looks like you need `-DLLVM_CONFIG=/usr/local/opt/llvm/bin/llvm-config` but it's probably more convenient to add /usr/local/opt/llvm/bin to your path.
Regarding your cmake invocation, it's an old way of doing things that has been very temporary and I'm not sure all the parameters are still supported. You should read the faust [building instructions](https://github.com/grame-cncm/faust/wiki).
