### ISSUE TITLE
`make uninstall` leaves files installed

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#36]
at least the `faustbench` executable is not removed when doing a `make uninstall`.

### steps to reproduce
```sh
$ git clone --branch faust2 https://github.com/grame-cncm/faust
$ cd faust
$ make
$ make install DESTDIR=/tmp/faustinstall
$ make uninstall DESTDIR=/tmp/faustinstall
$ find /tmp/faustinstall -type f
/tmp/faustinstall/usr/local/bin/faustbench
$
```

**Comment by sletz** [comment]
At least? : do you see more of them?

**Comment by umlaeute** [comment]
no, *I* don't see more leftovers. the result of the `find` command in my step-by-step instructions is complete.

However, I don't know whether there are any compile-options that I have missed (e.g. `make httpd`,...) and which might create more not-uninstalled files.
