### ISSUE TITLE
faust2api -juce errors on macosx

### ISSUE THREAD

**Issue by jamesstoneco** [grame-cncm/faust#364]
Versions tried: latest macosx binary, master, master-dev

When running the command from the faust juce tutorial `faust2api -juce synth.dsp` I get the following output:

```
Your dsp-faust.zip API package for JUCE is being created
ld: warning: directory not found for option '-L/usr/local/Cellar/flac/1.3.2/lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/libogg/1.3.2/lib'
ld: warning: directory not found for option '-L/usr/local/Cellar/libvorbis/1.3.5_1/lib'
```

On my machine I have installed flac through brew. I have 1.3.3 installed for flac, 1.3.3 and 1.3.4 for libogg, and 1.3.6 installed for libvorbis. I am running MacOSX 10.14.6 and zsh.

**Comment by sletz** [comment]
It's a warning ? Does the produced JUCE project actually works later on ?
