### ISSUE TITLE
Wrong license in architecture/faust/gui/meta.h

### ISSUE THREAD

**Issue by AstralStorm** [grame-cncm/faust#37]
Header architecture/faust/gui/meta.h is licensed under plain GPL v3 without exception and is a part of faust UI architecture required to actually compile Faust files.

While the header is small enough to allow fair use replacement to work, this is still a minor licensing problem as it means non-GPL3 projects cannot directly include it and in the future it might change alongside code generated by the compiler.

**Comment by sletz** [comment]
Reworked here https://github.com/grame-cncm/faust/commit/449374d234b5f78280ddb0551025d0e683dfe797
