### ISSUE TITLE
Semver for tagging

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#371]
It would be great, if the releases could be tagged in accordance with [semver](https://semver.org), so that it becomes clear, that some releases are pre-releases (e.g. `2.20.2` doesn't identify as a beta release and only by going to the releases page on github one can read, that the release is meant as a `prerelease`).

This would make the process more clear for users in general and for package maintainers in particular.

One could e.g. use `2.20.2-beta1`, followed by `2.20.2-beta2` and finishing with `2.20.2`.

**Comment by dvzrv** [comment]
@sletz You have added [another release](https://github.com/grame-cncm/faust/releases/tag/2.27.1), that adheres to semver but is marked as a pre-release.

Can this ticket please be considered? I can't spend my time clicking around on various code hosting platforms to find and evaluate the current notion of what a *stable release* means for all of them. That's what semver is for!

**Comment by sletz** [comment]
Forget that... a bit later for this one I guess.
