### ISSUE TITLE
os.osc doesn't always work with the interpreter backend (faust HEAD 2019-04-12)

### ISSUE THREAD

**Issue by kmatheussen** [grame-cncm/faust#373]
In Radium, this program doesn't produce correct sound when using the interpreter backend:

```
import("stdfaust.lib");

freq = nentry("h:Basic_Parameters/freq [1][unit:Hz] [tooltip:Tone frequency]",440,20,20000,1) : si.smooth(0.999);
gain = nentry("h:Basic_Parameters/gain [1][tooltip:Gain (value between 0 and 1)]",1,0,1,0.01);
gate = button("h:Basic_Parameters/gate [1][tooltip:noteOn = 1, noteOff = 0]") : int;

envelope = gain * gate : si.smooth(0.99);

process = os.osc(freq) * envelope <: (_,_);
```

If I use the llvm backend, sound is correct. When replacing os.osc with os.sawtooth, the sound is also correct. This program also sounds correct:

```
import("stdfaust.lib");

freq = nentry("h:Basic_Parameters/freq [1][unit:Hz] [tooltip:Tone frequency]",440,20,20000,1) : si.smooth(0.999);

process = os.osc(freq);
``` 

Maybe this bug has been fixed since April 2019? It's a big job updating Faust in Radium, or at least it has been earlier, but I will try to update Faust in Radium if the example works for you or if you don't have a quick way to check if this bug has been fixed since then.

It could of course also be a bug in Radium, but I can't think of any reason why it should be.

**Comment by kmatheussen** [comment]
Step by step:
1. Download Radium Demo here: http://users.notam02.no/~kjetism/radium/download.php
2. Start Radium
3. Load this song: [oscfaustinterpbug.rad.gz](https://github.com/grame-cncm/faust/files/3991695/oscfaustinterpbug.rad.gz)
4. Press AltGr to play.
5. Incorrect sound is heard.
6. Press F9 to show instrument widget
7. Press "Faust Dev 1" to select the faust instrument.
8. Replace "os.osc" with "os.sawtooth".
9. Sound is correct.

**Comment by sletz** [comment]
It works correctly here.

You can use the **dynamic-jack-gtk** tool too test with the LLVM or Interp backend, see https://github.com/grame-cncm/faust/tree/master-dev/tools/benchmark.

**Comment by kmatheussen** [comment]
Thank you. It doesn't work with dynamic-jack-gtk from april 2019. I guess the bug has been fixed. Downloading current HEAD now and closes the issue if it works now.

**Comment by kmatheussen** [comment]
(Had to run "make world" before "make benchmark" in order to build libHTTPDFaust and libOSCFaust needed by dynamic-jack-gtk)

**Comment by kmatheussen** [comment]
Needed to do this to build the programs in tools/benchmarks:

```
--- tools/benchmark/Makefile~   2019-12-21 09:49:58.000000000 +0100
+++ tools/benchmark/Makefile    2019-12-21 20:47:24.910315976 +0100
@@ -8,9 +8,17 @@
 DESTDIR ?=
 PREFIX ?= /usr/local
 
+OS_NAME := $(shell uname -s | tr A-Z a-z)
+
 prefix := $(DESTDIR)$(PREFIX)
 
-all: dynamic-faust faustbench-llvm faustbench-llvm-interp faustbench-interp dynamic-jack-gtk dynamic-machine-jack-gtk poly-dynamic-jack-gtk interp-tracer fastmath faust-osc-controller
+ALL = dynamic-faust faustbench-llvm faustbench-llvm-interp faustbench-interp dynamic-jack-gtk dynamic-machine-jack-gtk interp-tracer fastmath faust-osc-controller
+ifeq ($(UNAME_S),Darwin)
+       ALL += poly-dynamic-jack-gtk
+endif
+
+all: $(ALL)
+
 
 faustbench-llvm: faustbench-llvm.cpp $(LIB)/libfaust.a
        $(CXX) -std=c++11 -O3 faustbench-llvm.cpp -I $(INC) $(LIB)/libfaust.a `llvm-config --ldflags --libs all --system-libs` -dead_strip -lz -lncurses -lpthread -o faustbench-llvm
@@ -25,16 +33,16 @@
        $(CXX) -std=c++11 -O3 dynamic-faust.cpp -I $(INC) $(LIB)/libfaust.a `llvm-config --ldflags --libs all --system-libs` -dead_strip -o dynamic-faust
 
 dynamic-jack-gtk: dynamic-jack-gtk.cpp $(LIB)/libfaust.a
-       $(CXX) -std=c++11 -O3 dynamic-jack-gtk.cpp -I $(INC) $(LIB)/libfaust.a  `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack sndfile samplerate gtk+-2.0` -dead_strip -lOSCFaust -lHTTPDFaust -lmicrohttpd -o dynamic-jack-gtk
+       $(CXX) -std=c++11 -O3 dynamic-jack-gtk.cpp -I $(INC) $(LIB)/libfaust.a  `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack sndfile samplerate gtk+-2.0` -dead_strip $(LIB)/libOSCFaust.a $(LIB)/libHTTPDFaust.a -lmicrohttpd -o dynamic-jack-gtk
 
 dynamic-machine-jack-gtk: dynamic-machine-jack-gtk.cpp $(LIB)/libfaustmachine.a
-       $(CXX) -std=c++11 -O3 dynamic-machine-jack-gtk.cpp -I $(INC1) $(LIB)/libfaustmachine.a `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack gtk+-2.0` -dead_strip -lOSCFaust -lHTTPDFaust -lmicrohttpd -o dynamic-machine-jack-gtk
+       $(CXX) -std=c++11 -O3 dynamic-machine-jack-gtk.cpp -I $(INC) -I $(INC1) $(LIB)/libfaustmachine.a `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack gtk+-2.0` -dead_strip $(LIB)/libOSCFaust.a $(LIB)/libHTTPDFaust.a -lmicrohttpd -o dynamic-machine-jack-gtk
 
 poly-dynamic-jack-gtk: poly-dynamic-jack-gtk.cpp
-       $(CXX) -std=c++11 -O3 poly-dynamic-jack-gtk.cpp -I $(INC) $(LIB)/libfaust.a `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack gtk+-2.0 sndfile samplerate` -dead_strip -lz -lncurses -lpthread -lOSCFaust -lHTTPDFaust -lmicrohttpd -framework CoreAudio -framework AudioUnit -framework CoreServices -framework CoreMIDI -framework CoreFoundation -o poly-dynamic-jack-gtk
+       $(CXX) -std=c++11 -O3 poly-dynamic-jack-gtk.cpp -I $(INC) $(LIB)/libfaust.a `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs jack gtk+-2.0 sndfile samplerate` -dead_strip -lz -lncurses -lpthread $(LIB)/libOSCFaust.a $(LIB)/libHTTPDFaust.a -lmicrohttpd -framework CoreAudio -framework AudioUnit -framework CoreServices -framework CoreMIDI -framework CoreFoundation -o poly-dynamic-jack-gtk
 
 faust-osc-controller: faust-osc-controller.cpp
-       $(CXX) -std=c++11 -O3 faust-osc-controller.cpp -I $(INC) `pkg-config --cflags --libs gtk+-2.0` -dead_strip -lOSCFaust -llo -o faust-osc-controller
+       $(CXX) -std=c++11 -O3 faust-osc-controller.cpp -I $(INC) `pkg-config --cflags --libs gtk+-2.0` -dead_strip $(LIB)/libOSCFaust.a -llo -o faust-osc-controller
 
 interp-tracer: interp-tracer.cpp $(LIB)/libfaust.a
        $(CXX) -std=c++11 -O3 interp-tracer.cpp -I $(INC) $(LIB)/libfaust.a `llvm-config --ldflags --libs all --system-libs` `pkg-config --cflags --libs gtk+-2.0` -dead_strip -lz -lncurses -lpthread -o interp-tracer
```

**Comment by kmatheussen** [comment]
Yes, it works with latest faust.

**Comment by sletz** [comment]
Patch does not apply. Can you possibly prepare a PR? Thanks.

**Comment by kmatheussen** [comment]
I've updated Faust in Radium, but the example is still not working.

dynamic-jack-gtk works though, so something has happened since april that has caused the interpreter in dynamic-jack-gtk to work, but not in Radium. I want to bisect Faust to find out when dynamic-jack-gtk started working, but unfortunately I only have a slow laptop right now so I'll do it later instead when having a faster computer. With the laptop I might spend the whole day just bisecting.

In the mean time, any idea what the reason could be? The sound is almost completely gone, I only hear something that sounds like low-pass filtered click-sounds when turning on a note, and those are almost completely silent. There's no tones.

**Comment by sletz** [comment]
Are you running in float ? i double ?
What argument are you giving to `createInterpreterDSPFactoryFromString`?

**Comment by kmatheussen** [comment]
I'm running float. Any chance I'm accidentally running double sometimes?


```
      if (opts.use_interpreter) {
        for(int i=0;i<args.get_argc();i++)
          printf("%d: \"%s\"\n",i, args.get_argv()[i]);
        
        reply.interpreter_factory =
          createInterpreterDSPFactoryFromString(
                                                "FaustDev",
                                                opts.code.toUtf8().constData(),
                                                args.get_argc(),
                                                args.get_argv(),
                                                error_message
                                                );
        reply.factory = reply.interpreter_factory;
```
Outputs:
```
0: "-I"
1: "/home/kjetil/radium/bin/packages/faust/libraries"
2: "-svg"
3: "-O"
4: "/tmp/radium_faust_svg_100001"
```

**Comment by kmatheussen** [comment]
Turning off svg generation made no difference.

**Comment by sletz** [comment]
Nothing seems wrong here. Could it be the way controllers are handled? Are you defining your own UI subclass when using `buildUserInterface`?

**Comment by sletz** [comment]
It see here https://github.com/kmatheussen/radium/blob/dc207eda2a7fc8484208436b4a1f10993301f0d8/audio/Faust_factory_factory.cpp
that your are using your own MemoryManger (with `setMemoryManager`). Could it be related ? Can you test not using it ?

**Comment by kmatheussen** [comment]
Commenting out "reply.factory->setMemoryManager(&g_v_calloc_memory_manager);" made no difference.

**Comment by kmatheussen** [comment]
Yes, I use my own UI class: https://github.com/kmatheussen/radium/blob/dc207eda2a7fc8484208436b4a1f10993301f0d8/audio/Faust_plugins_template2.cpp#L23

gate/freq/gain is set like this when playing new note:
```
  *(voice->myUI._gate_control) = 1.0f;
  *(voice->myUI._freq_control) = midi_to_hz(note.pitch);
  *(voice->myUI._gain_control) = velocity2gain(note.velocity);
```
https://github.com/kmatheussen/radium/blob/dc207eda2a7fc8484208436b4a1f10993301f0d8/audio/Faust_plugins_template2.cpp#L470

**Comment by kmatheussen** [comment]
adding this line to play_note2:

```
  printf("        Setting freq to %f. gate: %f. gain: %f\n", *(voice->myUI._freq_control), *(voice->myUI._gate_control), *(voice->myUI._gain_control));
```

displays:

```
        Setting freq to 261.625549. gate: 1.000000. gain: 0.251167
```

which seems correct.

**Comment by kmatheussen** [comment]
Seems like there could be a name clash if a library adds a controller with the name "freq", "gain" or "gate". There isn't an assertion either for this. Investigating.

**Comment by kmatheussen** [comment]
No, the name clash thing isn't an issue. But I found the problem. It works if I do this:
```
- dsps[i]->instanceInit(MIXER_get_sample_rate());
+ dsps[i]->init(MIXER_get_sample_rate());
```

at https://github.com/kmatheussen/radium/blob/dc207eda2a7fc8484208436b4a1f10993301f0d8/audio/Faust_factory_factory.cpp#L358

classInit() has already been called on the class (https://github.com/kmatheussen/radium/blob/dc207eda2a7fc8484208436b4a1f10993301f0d8/audio/Faust_factory_factory.cpp#L319), so the Radium code looks correct to me.

It seems like you currently have to call classInit() as on every new dsp instance when using the interpreter.

**Comment by sletz** [comment]
OK, this is a limitation in Interp backend that actually does not share tables between instances, and then appears a a bug in the API use.  I'll fix that in Interp backend then.

**Comment by kmatheussen** [comment]
Thanks.

**Comment by kmatheussen** [comment]
To make things clearer, and to automatically prevent things being added to init() that actually belongs in classInit(), how about changing the main dsp class like this:

```
index e12194a..0cef40e 100644
--- a/architecture/faust/dsp/dsp.h
+++ b/architecture/faust/dsp/dsp.h
@@ -83,7 +83,18 @@ class dsp {
          *
          * @param sample_rate - the sampling rate in Hertz
          */
-        virtual void init(int sample_rate) = 0;
+        void init(int sample_rate){
+          classInit(sample_rate);
+          instanceInit(sampe_rate);
+        }
+
+        /**
+         * Init class state
+         *
+         * @param sample_rate - the sampling rate in Hertz
+         */
+        virtual void classInit(int sample_rate){
+        }
 
         /**
          * Init instance state
```
?

**Comment by sletz** [comment]
`classInit` has to stay a static method of the `dsp` class. I'll better fix the Interp backend, wihich is "special" in some areas.

**Comment by kmatheussen** [comment]
Can't `classInit` just be overridden to call a custom static method when needed?

**Comment by kmatheussen** [comment]
Sorry, I guess changing something like this would bring lots of headaches various places.

**Comment by sletz** [comment]
Indeed ((-; and the fix in Interp backend is 2 lines change... I'm updating the automatic tests to detect this kind of problem.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/f07d2f0315e14fceab67beadbebdceb6333d2c8d.

**Comment by kmatheussen** [comment]
Tested and working. Thanks!
