### ISSUE TITLE
buildUserInterfaceCDSPInstance in 2.20.2 broken

### ISSUE THREAD

**Issue by ventosus** [grame-cncm/faust#378]
buildUserInterfaceCDSPInstance in 2.20.2 seems broken, e.g. it does never call any of the callbacks in the UIGlue structure.

Example source attached.

When run in 2.15.11 the expected output is:

    $ (./faust_llvm_bug && echo ok) || echo nok
    [_meta_declare] filename : sketch
    [_meta_declare] maths.lib/author : GRAME
    [_meta_declare] maths.lib/copyright : GRAME
    [_meta_declare] maths.lib/license : LGPL with exception
    [_meta_declare] maths.lib/name : Faust Math Library
    [_meta_declare] maths.lib/version : 2.1
    [_meta_declare] name : sketch
    [_meta_declare] oscillators.lib/name : Faust Oscillator Library
    [_meta_declare] oscillators.lib/version : 0.0
    [_ui_declare] 0 : 
    [_ui_add_horizontal_slider] f0 : 110.000000 110.000000 880.000000 1.000000
    ok

When run in 2.20.2 the non-expected output is:

    $ (./faust_llvm_bug && echo ok) || echo nok
    [_meta_declare] filename : sketch
    [_meta_declare] maths.lib/author : GRAME
    [_meta_declare] maths.lib/copyright : GRAME
    [_meta_declare] maths.lib/license : LGPL with exception
    [_meta_declare] maths.lib/name : Faust Math Library
    [_meta_declare] maths.lib/version : 2.1
    [_meta_declare] name : sketch
    [_meta_declare] oscillators.lib/name : Faust Oscillator Library
    [_meta_declare] oscillators.lib/version : 0.0
    faust_llvm_bug: faust_llvm_bug.c:175: int main(int, char **): Assertion `hslider_visited' failed.
    nok

[faust_llvm_bug.c.txt](https://github.com/grame-cncm/faust/files/4008421/faust_llvm_bug.c.txt)
[Makefile.txt](https://github.com/grame-cncm/faust/files/4008422/Makefile.txt)

**Comment by sletz** [comment]
On which platform ?

**Comment by ventosus** [comment]
> On which platform ?

$ uname -a
Linux melamori 4.19.72-gnu-1-rt-rt #1 SMP PREEMPT @1573081950 x86_64 GNU/Linux

**Comment by sletz** [comment]
Well right... the code is just missing : https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/gui/JSONUIDecoder.h#L402
I'll fix that ASAP.

**Comment by ventosus** [comment]
:-)

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/0bbc3e4b605d3cec5e8fa17162b342e761ae9a1a.
