### ISSUE TITLE
libfaust: "-svg" option doesn't work in createDSPFactoryFromString.

### ISSUE THREAD

**Issue by kmatheussen** [grame-cncm/faust#379]
When running this code:

```
        const char *opts[] = {"-svg", "-O", "/tmp/"};
        createDSPFactoryFromString(
                                   "FaustDev",
                                   "process = +;",
                                   3,
                                   opts,
                                   "x86_64-pc-linux-gnu",
                                   error_message,
                                   3);
```

No svg files are created in /tmp/. `createInterpreterDSPFactoryFromString` works.

**Comment by kmatheussen** [comment]
`generateAuxFilesFromString` works too, but it is (or at least was) much slower to call both `createDspFactoryFromString` and `generateAuxFilesFromString` than it was to only calling `generateDspFactoryFromString` and let it generate the svg files.

**Comment by sletz** [comment]
Auxiliary files generation ("-tg", "-sg", "-ps", "-svg", "-mdoc", "-mdlang", "-stripdoc", "-sd", "-xml", "-json") are filtered in `createDSPFactoryFromString`. They should also be in  `createInterpreterDSPFactoryFromString` for coherency. The `generateAuxFilesFromString` is usually faster because it does not complete the whole compilation path.

**Comment by kmatheussen** [comment]
You mean they are explicitly filtered out? Would it be hard to reverse that? It's not that generateAuxFilesFromString isn't working, it's just that it takes a lot more time to call both createDSPFactoryFromString and generateAuxFilesFromString than it takes to add "-svg" option to createDSPFactoryFromString. In Radium, both factory and svg files are created automatically when writing code.

**Comment by sletz** [comment]
There was a reason to filter those arguments, but I don't remember it ((-;. So filtering removed in https://github.com/grame-cncm/faust/commit/6b84f486095a5b0c3506b721e48cdf739b9eaae3

**Comment by kmatheussen** [comment]
Thanks! Works now.
