### ISSUE TITLE
microhttpd.h not found during compilation

### ISSUE THREAD

**Issue by jdsierral** [grame-cncm/faust#381]
I was getting this error during compilation of Faust in OSx Mojave. As far as I could tell, this was because the MakeFile points to 

/usr/local/Cellar/libmicrohttpd/0.9.62_1/include

but the latest version of microhttpd library creates this folder structure

/usr/local/Cellar/libmicrohttpd/0.9.63/include

I was able to solve it by creating a symlink 0.9.62_1 -> 0.9.63 but my guess would be that the Makefiles would have to be updated or modified to accommodate the different versions?

Just posting in case someone else has the same problem ;)

JuanS

**Comment by sletz** [comment]
Which MakeFile are you speaking of ?

**Comment by jdsierral** [comment]
Humm... maybe I posted this rushing a bit :/...

So this is what I understand although I might be very wrong XD... So when you first run make on the base folder of the repo, CMake figures out the version of `microhttpd` and creates some files which I think aid the compilation process. For example:

`build/faustdir/http/CMakeFiles/httpstatic.dir/flags.make`

which internally has the following line 

`-I/usr/local/Cellar/libmicrohttpd/0.9.63/include`

Obviously this is used at some point by the compiler to include those header files and so on.

My problem was that I was trying to recompile Faust as I saw some new commits on the branch and thought it could be a good time to update my versions of Faust and faustlive. By running `make clean` and `make all` I was getting an error related to not finding `microhttpd.h` in file `architecture/httpdlib/src/httpd/HTTPDServer.h `.

I believe this was happening because the makefile was not editing these files

```
build/faustdir/http/CMakeFiles/httpstatic.dir/flags.make
build/faustdir/http/CMakeFiles/httpdynamic.dir/link.txt
build/faustdir/http/CMakeFiles/httpdynamic.dir/flags.make
build/faustdir/CMakeCache.txt
```

even after `make clean` so the compiler was still expecting the path of version 0.9.62_1 even though I had updated microhttpd to 0.9.63. (which was the first thing I thought after seeing `microhttpd.h` not found).

Today I erased my copy of the repo and cloned it again and now it was fine :). My understanding is that all of this happened because when I first built Faust several months ago I had microhttpd@0.9.62_1 then I updated it to microhttpd@0.9.63 but then even though I did `make clean` some files created during the first compilation process got stuck with 0.9.62_1. After a while I was able to hack it by doing a symlink 0.9.62_1 -> 0.9.63 on the path so that the old path could work, but now I see that if the repo is new then it writes the files with the correct path.

On a second thought I think its also possible that the files were correctly modified but the way the compiler queries for the path was somehow still returning the old path. This could be related to the way microhttpd was installed (in my case through home-brew) but honestly I don't think I understand enough about that part to be helpful :/... 

In any case I wouldn't consider this an big deal or anything, It was more in case someone stumbled on a similar situation :) ... Nonetheless, thanks for the responsiveness 👍, and sorry if I was completely off and it was something particular to my own installation ;)

JuanS

**Comment by sletz** [comment]
Thanks. The "make clean" maybe needs some improvements. We'll have a look.

**Comment by jdsierral** [comment]
Just FYI, I have another system with similar history... In this one I had microhttpd@0.9.59 and attempting the same procedure got the same error...

The same 4 files kept pointing to the old path

`/usr/local/Cellar/libmicrohttpd/0.9.59/...`

instead of

`/usr/local/Cellar/libmicrohttpd/0.9.63/...`

after `make clean && make all` 

However I realized that inside the build folders in there's another Makefile with a target called distclean. Running that solved my problem as it deletes all faustdir folder :). Maybe adding that "deep clean" target to the Makefile would be enough? Just guessing here and trying to provide more info but you guys know better ;)

Thanks once again
JuanS

**Comment by sletz** [comment]
You can also do`  make cmake` in the build folder, to regenerate cmake related files.
