### ISSUE TITLE
problem with original value of rwtable

### ISSUE THREAD

**Issue by Petruselgrande** [grame-cncm/faust#383]
I want a variable than starts at a some value. I think that maybe  I am understanding something bad.
the second input of rwtable is the table 's initial value, isn't it?

Thank you so much.

```
import("stdfaust.lib");



//Funciones para probar sin sonido de fuera
power1 = hslider("value1", 0, 0, 5, 1);
visualizeHz1 = _ <: attach(_, hbargraph("hz 1",0,5000));
herzios1 = 170*2^power1: visualizeHz1;

tabla = rwtable(1, 1000.0,int(pulsos),_,int(pulsos)) : si.smooth(ba.tau2pole(2))with{
    pulsos = os.lf_rawsaw(44100) < 0;
    initValue = 1000.0;
};

process = herzios1 : hbargraph("hz antes tabla",0,5000):tabla : hbargraph("hz finales",0,5000);
```

**Comment by sletz** [comment]
Can you possibly come on the Faust Slack channel : https://join.slack.com/t/faustaudio/shared_invite/enQtNzk2ODMxMzM4MzExLTdjYmUyZmQ4MzRkMWY5OTFhNTIzYmMwMDQ2YmM5M2VlYjU1YjBlYjg4OTQxM2RjMGM5Njc0NjVmZGJjY2E3MDI

It will be easier to discuss your problem there.
