### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#40]
For the benefit of all distro packagers, please consider doing a release.
Thank you!

ping @sletz @umlaeute 

see: http://faudiostream-devel.narkive.com/YNSYzyss/faust2-release-tags

**Comment by sletz** [comment]
In progress...

**Comment by sletz** [comment]
To be tested here : https://github.com/grame-cncm/faust/releases

**Comment by magnetophon** [comment]
@sletz Great, thanks!
