### ISSUE TITLE
Adding a debug/single-stepped DSP modality for Faust programs

### ISSUE THREAD

**Issue by dariosanfilippo** [grame-cncm/faust#400]
Hello.

The outputs of some algorithms need to be inspected sample by sample to make sure that the behaviour is correct. When these algorithms do not work, it is sometimes necessary to also inspect sample by sample areas of the network far from the output stage.

In large networks, the code may require major changes to route whatever signal needs to be inspected to the output and use tools such as the CSV plot.

Bargraphs are bounded to block calculations and, even if not so, they couldn't be inspected if running at samplerate.

Would it be possible to have a faust2debug target generating a program that can be single-stepped on-demand, and where bargraphs can be used to inspect signals sample by sample?

Alternatively, would it be possible to have a function whose dedicated task, when placed somewhere in the code, is to take the incoming signal, route it to the first available output channel, and pass forward the same signal unaltered?

Thanks,
Dario

**Comment by sletz** [comment]
I've added -bs (buffer-size) and -s (start-sample) options in `faust2cvsplot` and print of bargraph  values in https://github.com/grame-cncm/faust/commit/55a86fe01b14dca6b7e69ec13e6798caab03a975.

So adding some bargraph based sensors in the DSP code + using the single-step mode (using -bs 1) should allow to see what you need.

**Comment by dariosanfilippo** [comment]
That's fantastic. Thank you so much, Stéphane.

Dario
