### ISSUE TITLE
si.lag_ud(2,0); causes division by 0

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#406]
When I compile:
```
process = si.lag_ud(2,0);
```
I get:
```
ERROR : division by 0 in -1 / 0
```

This used to work just fine, and is in fact used in the libraries, in RMS_compression_gain_mono.

**Comment by sletz** [comment]
Works here with Faust 2.23.0.  It seems a compiler or library issue in Faust Web IDE, that we need to update. In the meantime you can use the old Web Faust Editor, but which has been recently updated with libfaust 2.22.5: https://fausteditor.grame.fr

**Comment by magnetophon** [comment]
I used faust 2.20.2.
I'm building the latest commit now, to see if that helps.

**Comment by magnetophon** [comment]
The latest commit indeed fixes that issue, but it surfaces another bug, making me unable to compile old code:
``
ERROR : path '/autoComp/fast_rel' is already used
``

Let me find a minimal failing example, bbl.

**Comment by sletz** [comment]
It's not a bug, it a more restrictive behaviour of the compiler: all paths should be distinct now. You'll have to fix your DSP source.

**Comment by magnetophon** [comment]
OK, fair enough.  Where can I read about what has changed in that respect?
IOW I haven't figured out what the error means yet.

Can you do a release that fixes the divide by 0 bug?
Distro packagers (like me) would rejoice!  :)

**Comment by sletz** [comment]
TBH I don't remember the this path issue was fixed ))-; 

The point is that the compiler now refuses to compile code that cause several identical UI path (like`/foo/bar/ui_item`) to be produced, since identical paths cannot be distinguished when controlled with OSC for instance. 

Yes, we'll have to prepare a new release soon.

**Comment by magnetophon** [comment]
NixOS just merged my pkg for 2.20.2.
Any idea how long a new release would take?

**Comment by sletz** [comment]
We really need to make our testing machinery more robust (like this library related issue that was not seen...). Automatically testing libraries is not so easy.

A release should be done before IFC for sure...

**Comment by magnetophon** [comment]
OK, thanks.
Would you mind if we keep this issue open till the release?

**Comment by sletz** [comment]
Yes, sure.

**Comment by magnetophon** [comment]
Fixed in latest release.
Thanks!
