### ISSUE TITLE
Documentation on compiling libfaust

### ISSUE THREAD

**Issue by mgunyho** [grame-cncm/faust#408]
Hi! I wanted to compile libfaust to use it in my application, but it was hard
to get started because I found the documentation a bit confusing.

Looks like the instructions for compiling Faust (and libfaust in particular)
are spread out across at least three places:

- The `compiling` section in the manual
- The `build/README.md` file
- The wiki

These three places seem to have more or less the same information, but with
some minor differences, and also some outdated information (they mention commands
like `make configstatic`, which don't exist in the makefiles anymore). It was
(and to some extent still is) unclear to me which of these guides to follow.
The documentation should be all in one place.

The wiki seems to have the most comprehensive information. What is its role in
relation to the manual? If the wiki is the right place for the build
instructions, I think the manual and `build/README.md` should be updated to
just point to it. The manual could have maybe a few sentences on the basic
compilation, but I think having the detailed instructions there (related to
MSVC and whatnot) is unnecessary.

If this sounds right, I could make the above changes to the documentation and
README, and try to write them so that they are easy to follow for someone who is not very
familiar with the Faust ecosystem (like me).

**Comment by sletz** [comment]
Thanks, @dfober may have a look at some point.

**Comment by dfober** [comment]
> If the wiki is the right place for the build instructions, I think the manual and build/README.md should be updated to just point to it.

I agree, having a single source for documentation is undoubtedly the best way to keep it up to date.

> If this sounds right, I could make the above changes to the documentation and
README

your contribution is welcome!

**Comment by mgunyho** [comment]
I looked a bit into this today. I don't have editing rights to the wiki but I'm writing some markdown files that combine all information from the aforementioned sources, which can then be copied to the wiki (if that's their final place).

I found compilation instructions in yet another place, the quick reference manual. How up to date is that?

Also, looks like the documentation is being migrated to `faustdoc`, is this right?

**Comment by dfober** [comment]
Yes, please send your MD files. 
Otherwise, that's right, the quick ref does also contains instructions for compilation. The sources are included in the faust repository, in documentation folder.
`faustdoc` is intended to document the faust language and does not include anything regarding the compilation process.
