### ISSUE TITLE
Rust: `UI<T>::declare()` and borrow

### ISSUE THREAD

**Issue by bkfox** [grame-cncm/faust#409]
Rust code provides `UI<T>::declare(&mut self, zone: &mut T, key: &str, value: &str) -> ()` used to declare variables accessible from user interface.

The parameter `zone` is a mutable borrow to member variable of the generated DSP, which is not really usable: an UI implementation can't keep the provided member reference in order to update it when a control event occurs, because of borrow and ownership rules.

Potential solution would assign an index for each generated variable that can be used to retrieve or update members' values. On the generated DSP struct, two accessor methods: `fn get_var(&self, index: Index) -> &f32`, `fn get_var_mut(&mut self, index: Index) -> &mut f32` returning actual reference to DSP's variables by index. This index is passed down to `UI::declare()` as the `zone` instead of the reference.
Although there still is an undefined part on how concrete implementation of UI access the DSP instance (and more or less related thing is the ownership model used here), it leaves users freedom to choose how to integrate DSP and UI in their applications.

**Comment by sletz** [comment]
TBH the Rust backend is still very experimental. So I understand you propose to adapt the https://github.com/grame-cncm/faust/blob/master-dev/architecture/minimal.rs file and the generated code? Can you prepare a pull-request ?

**Comment by sletz** [comment]
There is also something to keep in mind: in the C++ model several UI can be connected to a same DSP so that each of them can possibly update the `zones`. Does your proposal solve this issue?

**Comment by bkfox** [comment]
Sorry I could not answer sooner. I'm actually working on a similar problem for an audio project using a DSP graph, where multiple UI should be able to update dsp's parameters. I'll however make more progress into this direction before I actually can give you a more concrete answer.

Here are some thoughs:
- DSP reference passed to `UI::declare` should be generic and passed down to `buildUserInterface` from the caller. This avoid to force generated DSP to take care of such implementation detail as how to refer to themselves and opens possibilities to multiple UI backends.
- Using variables references for zones poses the problem of ownership, lifetime and multithread (maybe): multiple UI keeping direct reference to a DSP variable means that they can't outlive the DSP. A UI would probably keep theses references in a map, such as:

    ```rust
    UI<'a> {
        zones: BTreeMap<&'a mut f32, Metadata>,
        //... 
    } 
    ```

    Where it becomes difficult it when UI has to handle multiple DSP.
- If we resume what a zone has to contains it is: plugin/variable metadata (through `declare`), variable value (through `add*` widget); variable can potentially be of any type in different situation, although in Faust they likely be f32 -- maybe we should think of an enum for variable type.
- I was thinking of a method on generated DSP such as `updateValue(key: Key, value: Value)`; where Key is also an index. I think using an enum as Key while it might seems a beautiful solution would not especially be usefull in case a UI has to handle different dsp instances (what would be the type of `zones`' key in the previous example?);

I'll keep you in touch when I've got something more probant. I actually plan to include dsp generated by Faust in my project so it'll gives me space to make tests.

Other question not directly linked to this issue but I won't mind to take a look too is that: is there a way to distinguish what has to be computed realtime and not when DSP variables change?

**Comment by sletz** [comment]
Thanks for the explanations. 

When DSP controllers change, the `compute` method sample the current value of all controllers in stack local variables, then these local variables are used in the DSP loop. See for instance: 

```
pub fn compute(&mut self, count: i32, inputs: &[&[f32]], outputs: &mut[&mut[f32]]) {
		let mut fSlow0: f32 = (4.65661287e-10 * (self.fHslider0 as f32));
		let mut fSlow1: f32 = (4.65661287e-10 * (self.fHslider1 as f32));
		for i in 0..count {
			self.iRec0[0] = ((1103515245 * self.iRec0[1]) + 12345);
			let mut fTemp0: f32 = (self.iRec0[0] as f32);
			outputs[0][i as usize] = ((fSlow0 * fTemp0) as f32);
			outputs[1][i as usize] = ((fSlow1 * fTemp0) as f32);
			self.iRec0[1] = self.iRec0[0];
		}
	}
```
`fSlow0, fSlow1` are computed using `self.fHslider0, self.fHslider1` then used in the DSP for loop.

**Comment by bkfox** [comment]
Okay, I've have a working example of implementation in my project's [controller module](https://github.com/bkfox/foxlive/blob/master/libfoxlive/src/dsp/controller.rs) - it however has extra boilerplate in regards to faust usage because it handles different values type - I'll just reproduce some code:

```rust
/// Metadata (key, value)
pub type Metadata = (String,String);
/// Metadata for controller and its controls
pub type Metadatas = Vec<Metadata>;

/// Map information to a control
pub struct ControlMap {
    pub control: ControlIndex,
    pub control_type: ControlType,
    pub metadata: Metadatas,
}

/// Trait providing interface to declare controls
pub trait ControlsMapper {
    /// Add a new control to the controls' map
    fn declare(&mut self, control: ControlIndex, control_type: ControlType,
               metadata: Metadatas);
}


/// A Controller provides mapping to some of its values in order to allow them to be changed.
/// Exposed values of a controller are called *Controls*, which can be set/get by index.
/// Controller and controls can also provide extra information through their `Metadata`.
pub trait Controller {
    /// Return Controller's metadata
    fn get_metadata(&mut self) -> Metadatas;

    /// Get value of a control
    fn get_control(&self, control: ControlIndex) -> Option<ControlValue>;

    /// Set value of a control
    fn set_control(&mut self, control: ControlIndex, value: ControlValue) -> Result<ControlValue, ()>;

    /// Init a control mapper declaring all available controls
    fn map_controls(&self, mapper: &mut dyn ControlsMapper);
}
```

- Controller is a trait providing 4 methods: `get_metadata()` (return controller's metadata), `set_control()` (set a value by control index), `get_control()` (get a value by control index), `map_controls()` (map controls using a provided mapper - as `ControlMapper`);
- There is no need to pass references between the DSP itself and the mapper, this can be handled at higher levels (example in the [graph implementation](https://github.com/bkfox/foxlive/blob/master/libfoxlive/src/dsp/graph.rs#L287); which itself implement the Controller trait in order to be reused by multiple UI);
- If we think of potential lock-free and multi-thread, maybe the use of atomics for controllers' values would be a good idea (in such case, if i'm not wrong, `set_control` will take self as non-mutable reference);
- Traits should be declared in a different module than the generated DSP's because it makes modularity much more difficult: in current faust work, if we have 3 DSP, 3 different UI trait will be generated that both will have to be implemented for each used UI backend, although the traits provide same interfaces.

I've taken a look to generated C++ code too; regarding to multiple UI for a single DSP instance (and more generally), we have to take in account that Rust really enforce ideas of data ownership and values borrowing (which is a important for safe implementation), so we can't have pointers being thrown everywhere in the code as in C++.

**Comment by bkfox** [comment]
I've been digging up a bit the faust compiler code, especially for rust generator; its quiete complex so I couldn't resolve few issues such as generating an enum as global declaration and that kind of things.

Here is an example of the expected generated code in order to give you an idea, based on manual's "Quistart > Building a user interface":


```rust
//! UI trait and used generic interface.

/// Index used to designate a zone, whose value is handled by specific Controller implementations (aka dsp)
pub type ZoneIndex = u32;

/// UI trait implemented by actual user interfaces
pub trait UI {
    /// example function 
    fn declare(zone: ZoneIndex, a: String, b: String);
}


/// Interface implemented by dsp in order to update their value generically since there is not
/// such thing as C++'s struct/class inheritance
pub trait Zone {
    /// Get zone value by index
    get_zone(&self, index: ZoneIndex) -> Option<f32>;

    /// Returns a `Result` since index may be out of range
    set_zone(&mut self, index: ZoneIndex, value: f32) -> Result<(),()>;

    // Provide metadata
    // metadata(&self, metadata: Metadata);

    /// Build the user interface
    buildUserInterface(&self, ui: &dyn UI);
}

```

```rust
//! Generated dsp file.
use ui::*;


/// Represent zones as an integer value, it is used for clarity when manipulating
/// zones.
#[repr(u32)]
pub enum MydspZones {
    None = 0,
    HSlider0,
    Button0,
    HSlider1,
}

impl Into<ZoneIndex> for MydspZones {
    fn into(self) -> ZoneIndex {
        self as ZoneIndex
    }
}

impl From<ZoneIndex> for MydspZones {
    fn from(index: ZoneIndex) -> MydspZones {
        // i'm not sure wether direct casting is possible or not, so use a match
        match index {
            1 => MydspZones::HSlider0,
            2 => MydspZones::Button0,
            3 => MydspZones::HSlider1,
            _ => MydspZones::None,
        }
    }
}

//...

pub struct mydsp {
    fDummy: f32,
    fHslider0: f32,
    fHslider1: f32,
    fHslider2: f32,
    //...
}

impl mydsp {
        
    pub fn new() -> mydsp { 
        mydsp {
            fHslider0: 0.0,
            fButton0: 0.0,
            fHslider1: 0.0,
            fHslider2: 0.0,
            // ...
        }
    }

    /// ... all methods but buildUserInterface and metadata  which are in Zone trait.
}

/// Implement Zone, this is the interface used to interact with UI generically
impl Zone for mydsp {
    /// Get zone value by index
    get_zone(self, index: ZoneIndex) -> Option<f32> {
        match index.into() {
            MydspZones::HSlider0 => Some(self.fHslider0),
            MydspZones::HButton0 => Some(self.fButton0),
            MydspZones::HSlider1 => Some(self.fHslider1),
            MydspZones::None => None,
        }
    }

    /// Returns a `Result` since index may be out of range
    set_zone(&mut self, index: ZoneIndex, value: f32) -> Result<(),()> {
        match index.into() {
            MydspZones::HSlider0 => { self.fHslider0 = value; },
            MydspZones::Button0 => { self.fButton0 = value; },
            MydspZones::HSlider1 => { self.fHslider1 = value; },
            MydspZones::None => return Err(()),
        }
        Ok(())
    }

    /// Build the user interface
    buildUserInterface(self, ui: &dyn UI) {
        ui_interface.openVerticalBox("test");
        ui_interface.declare(MydspZones::Hslider2.into(), "0", "");
        ui_interface.addHorizontalSlider("cutoffFrequency", MydspZones::Hslider2.into(), 500.0, 50.0, 10000.0, 0.01);
        ui_interface.declare(MydspZones::Hslider1.into(), "1", "");
        ui_interface.addHorizontalSlider("q", MydspZones::Hslider1.into(), 5.0, 1.0, 30.0, 0.10000000000000001);
        ui_interface.declare(MydspZones::Hslider0.into(), "2", "");
        ui_interface.addHorizontalSlider("gain", MydspZones::Hslider0.into(), 1.0, 0.0, 1.0, 0.01);
        ui_interface.declare(MydspZones::Button0.into(), "3", "");
        ui_interface.addButton("gate", MydspZones::Button0.into());
        ui_interface.closeBox();
    }
}
```

In this example, an enum is used, which require conversion from and into `ZoneIndex` for clarity but it is not required: `ZoneIndex` values can directly be used.

**Comment by sletz** [comment]
Thanks. The way the final; Rust code is generated is:
- part of the code is generated by the Rust backend
- part of the code is generic, using the so-called "architecture files" like https://github.com/grame-cncm/faust/blob/master-dev/architecture/minimal-portaudio.rs or https://github.com/grame-cncm/faust/blob/master-dev/architecture/minimal-jack.rs
- the final code is produced using the `faust2portaudiorust` or `faust2jackrust` scripts. 
So you could possibly start by compiling a real example using a command like `faust2portaudiorust  foo.dsp`, the manually hack it with you proposed change to make it work? It would help then to distinguish what has to be generated versus what can be coded in the architecture files.

**Comment by bkfox** [comment]
Here is an example using `faust2jackrust`, still based on the same example. I've added few notes, although I imagine for some of them it is due to how faust compiler internal works (about `mut` variables).

```rust
/************************************************************************
import("stdfaust.lib");
ctFreq = hslider("[0]cutoffFrequency",500,50,10000,0.01);
q = hslider("[1]q",5,1,30,0.1);
gain = hslider("[2]gain",1,0,1,0.01);
t = button("[3]gate");
process = no.noise : fi.resonlp(ctFreq,q,gain)*t;
************************************************************************/

#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

//! Faust JACK architecture file
extern crate jack;
use jack::prelude as j;
use std::io;
extern crate libm;

pub trait Meta {

    // -- metadata declarations

    fn declare(&mut self, key: &str, value: &str) -> ();

}


type ZoneIndex = u32;

pub trait UI {
    /// Use associated type instead of generic parameter on traits is generally a better idea.
    type Value;

    // -- widget's layouts

    fn openTabBox(&mut self, label: &str) -> ();
    fn openHorizontalBox(&mut self, label: &str) -> ();
    fn openVerticalBox(&mut self, label: &str) -> ();
    fn closeBox(&mut self) -> ();

    // -- active widgets

    fn addButton(&mut self, label: &str, zone: ZoneIndex) -> ();
    fn addCheckButton(&mut self, label: &str, zone: ZoneIndex) -> ();
    fn addVerticalSlider(&mut self, label: &str, zone: ZoneIndex, init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> ();
    fn addHorizontalSlider(&mut self, label: &str, zone: ZoneIndex , init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> ();
    fn addNumEntry(&mut self, label: &str, zone: ZoneIndex, init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> ();

    // -- passive widgets

    fn addHorizontalBargraph(&mut self, label: &str, zone: ZoneIndex, min: Self::Value, max: Self::Value) -> ();
    fn addVerticalBargraph(&mut self, label: &str, zone: ZoneIndex, min: Self::Value, max: Self::Value) -> ();

    // -- metadata declarations

    fn declare(&mut self, zone: ZoneIndex, key: &str, value: &str) -> ();

}


/// Implement Zone, this is the interface used to interact with UI generically
pub trait Zone {
    type Value;

    /// Get zone value by index
    fn get_zone(&self, index: ZoneIndex) -> Option<f32>;

    /// Returns a `Result` since index may be out of range
    fn set_zone(&mut self, index: ZoneIndex, value: Self::Value) -> Result<(),()>;

    /// Build the user interface
    fn buildUserInterface(&self, ui: &mut dyn UI<Value=Self::Value>);
}


// ---- dsp

pub fn mydsp_faustpower2_f(value: f32) -> f32 {
	return (value * value);
}



pub struct mydsp {
	fDummy: f32,
	fHslider0: f32,
	fButton0: f32,
	fHslider1: f32,
	fSampleRate: i32,
	fConst0: f32,
	fHslider2: f32,
	iRec1: [i32;2],
	fRec0: [f32;3],
}

impl mydsp {
		
	pub fn new() -> mydsp { 
		mydsp {
			fDummy: 0 as f32,
			fHslider0: 0.0,
			fButton0: 0.0,
			fHslider1: 0.0,
			fSampleRate: 0,
			fConst0: 0.0,
			fHslider2: 0.0,
			iRec1: [0;2],
			fRec0: [0.0;3],
		}
	}

        // Note: new rust syntax for taking traits uses "dyn" keyword
	pub fn metadata(&mut self, m: &mut dyn Meta) { 
		m.declare("filename", "test.dsp");
		m.declare("filters.lib/fir:author", "Julius O. Smith III");
		m.declare("filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	}

	pub fn getSampleRatemydsp(&mut self) -> i32 {
		return self.fSampleRate;
	}
	pub fn getNumInputs(&mut self) -> i32 {
		return 0;
	}
	pub fn getNumOutputs(&mut self) -> i32 {
		return 1;
	}
	pub fn getInputRate(&mut self, channel: i32) -> i32 {
                // Note: no need to be mutable
		let mut rate: i32;
		match (channel) {
			_ => {
				rate = -1;
			},
		} 
		return rate;
	}
	pub fn getOutputRate(&mut self, channel: i32) -> i32 {
                // Note: no need to be mutable
		let mut rate: i32;
		match (channel) {
			0 => {
				rate = 1;
			},
			_ => {
				rate = -1;
			},
		} 
		return rate;
	}
	
	pub fn classInit(sample_rate: i32) {
	}

	pub fn instanceResetUserInterface(&mut self) {
		self.fHslider0 = 1.0;
		self.fButton0 = 0.0;
		self.fHslider1 = 5.0;
		self.fHslider2 = 500.0;
	}
	pub fn instanceClear(&mut self) {
		for l0 in 0..2 {
			self.iRec1[l0 as usize] = 0;
		}
		for l1 in 0..3 {
			self.fRec0[l1 as usize] = 0.0;
		}
	}
	pub fn instanceConstants(&mut self, sample_rate: i32) {
		self.fSampleRate = sample_rate;
		self.fConst0 = (3.14159274 / f32::min(192000.0, f32::max(1.0, (self.fSampleRate as f32))));
	}
	pub fn instanceInit(&mut self, sample_rate: i32) {
		self.instanceConstants(sample_rate);
		self.instanceResetUserInterface();
		self.instanceClear();
	}
	pub fn init(&mut self, sample_rate: i32) {
		mydsp::classInit(sample_rate);
		self.instanceInit(sample_rate);
	}
	
	pub fn compute(&mut self, count: i32, inputs: &[&[f32]], outputs: &mut[&mut[f32]]) {
                // Note: all following variable bindings don't actually need to be mutable,
                //       as rust compiler warns us
		let mut fSlow0: f32 = (1.0 / (self.fHslider1 as f32));
		let mut fSlow1: f32 = f32::tan((self.fConst0 * (self.fHslider2 as f32)));
		let mut fSlow2: f32 = (1.0 / fSlow1);
		let mut fSlow3: f32 = (((fSlow0 + fSlow2) / fSlow1) + 1.0);
		let mut fSlow4: f32 = (((self.fHslider0 as f32) * (self.fButton0 as f32)) / fSlow3);
		let mut fSlow5: f32 = (1.0 / fSlow3);
		let mut fSlow6: f32 = (((fSlow2 - fSlow0) / fSlow1) + 1.0);
		let mut fSlow7: f32 = (2.0 * (1.0 - (1.0 / mydsp_faustpower2_f(fSlow1))));
		for i in 0..count {
                        // Note: Runtime error: thread '<unnamed>' panicked at 'attempt to multiply with overflow', src/main.rs:218:30
			self.iRec1[0] = ((1103515245 * self.iRec1[1]) + 12345);
			self.fRec0[0] = ((4.65661287e-10 * (self.iRec1[0] as f32)) - (fSlow5 * ((fSlow6 * self.fRec0[2]) + (fSlow7 * self.fRec0[1]))));
			outputs[0][i as usize] = ((fSlow4 * (self.fRec0[2] + (self.fRec0[0] + (2.0 * self.fRec0[1])))) as f32);
			self.iRec1[1] = self.iRec1[0];
			self.fRec0[2] = self.fRec0[1];
			self.fRec0[1] = self.fRec0[0];
		}
	}

}


/// Implement Zone, this is the interface used to interact with UI generically
impl Zone for mydsp {
    type Value = f32;

    fn get_zone(&self, index: ZoneIndex) -> Option<f32> {
        match index {
            0 => Some(self.fHslider0),
            1 => Some(self.fButton0),
            2 => Some(self.fHslider1),
            _ => None,
        }
    }

    fn set_zone(&mut self, index: ZoneIndex, value: f32) -> Result<(),()> {
        match index {
            0 => { self.fHslider0 = value; },
            1 => { self.fButton0 = value; },
            2 => { self.fHslider1 = value; },
            _ => return Err(()),
        }
        Ok(())
    }

    fn buildUserInterface(&self, ui_interface: &mut dyn UI<Value=Self::Value>) {
        ui_interface.openVerticalBox("test");
        ui_interface.declare(2, "0", "");
        ui_interface.addHorizontalSlider("cutoffFrequency", 2, 500.0, 50.0, 10000.0, 0.01);
        ui_interface.declare(2, "1", "");
        ui_interface.addHorizontalSlider("q", 2, 5.0, 1.0, 30.0, 0.10000000000000001);
        ui_interface.declare(0, "2", "");
        ui_interface.addHorizontalSlider("gain", 0, 1.0, 0.0, 1.0, 0.01);
        ui_interface.declare(1, "3", "");
        ui_interface.addButton("gate", 1);
        ui_interface.closeBox();
    }
}



/// Example UI
struct PrintUI;

impl UI for PrintUI {
    type Value = f32;

    fn openTabBox(&mut self, label: &str) -> () {
        println!("openTabBox - {}", label);
    }

    fn openHorizontalBox(&mut self, label: &str) -> () {
        println!("openHorizontalBox - {}", label);
    }

    fn openVerticalBox(&mut self, label: &str) -> () {
        println!("openVerticalBox - {}", label);
    }

    fn closeBox(&mut self) -> () {
        println!("closeBox");
    }

    fn addButton(&mut self, label: &str, zone: ZoneIndex) -> () {
        println!("addButton - {} {}", label, zone);
    }

    fn addCheckButton(&mut self, label: &str, zone: ZoneIndex) -> () {
        println!("addCheckButton - {} {}", label, zone);
    }

    fn addVerticalSlider(&mut self, label: &str, zone: ZoneIndex, init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> () {
        println!("addVerticalSlider - {} {} {} {} {} {}", label, zone, init, min, max, step);
    }

    fn addHorizontalSlider(&mut self, label: &str, zone: ZoneIndex , init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> () {
        println!("addHorizontalSlider - {} {} {} {} {} {}", label, zone, init, min, max, step);
    }

    fn addNumEntry(&mut self, label: &str, zone: ZoneIndex, init: Self::Value, min: Self::Value, max: Self::Value, step: Self::Value) -> () {
        println!("addNumEntry - {} {} {} {} {} {}", label, zone, init, min, max, step);
    }

    fn addHorizontalBargraph(&mut self, label: &str, zone: ZoneIndex, min: Self::Value, max: Self::Value) -> () {
        println!("addHorizontalBargraph - {} {} {} {}", label, zone, min, max);
    }

    fn addVerticalBargraph(&mut self, label: &str, zone: ZoneIndex, min: Self::Value, max: Self::Value) -> () {
        println!("addVerticalBargraph - {} {} {} {}", label, zone, min, max);
    }

    fn declare(&mut self, zone: ZoneIndex, key: &str, value: &str) -> () {
        println!("declare - {} {} {}", zone, key, value);
    }
}



fn main() {
    let (client, _status) = j::Client::new("faust_rust", j::client_options::NO_START_SERVER).unwrap();
    let mut dsp = Box::new(mydsp::new());

    println!("Faust Rust code running with JACK: sample-rate = {} buffer-size = {}", client.sample_rate(), client.buffer_size());
    println!("getNumInputs: {}", dsp.getNumInputs());
    println!("getNumOutputs: {}", dsp.getNumOutputs());

    dsp.init(client.sample_rate() as i32);

    // Test user interface mechanism
    let mut ui = PrintUI;
    dsp.buildUserInterface(&mut ui);
    println!("set gain: {:?}", dsp.set_zone(0, 1312.0));
    println!("get gain: {:?}", dsp.get_zone(0));

    let in_a = client.register_port("in1", j::AudioInSpec::default()).unwrap();
    let in_b = client.register_port("in2", j::AudioInSpec::default()).unwrap();
    let mut out_a = client.register_port("out1", j::AudioOutSpec::default()).unwrap();
    let mut out_b = client.register_port("out2", j::AudioOutSpec::default()).unwrap();

    let process_callback = move |_: &j::Client, ps: &j::ProcessScope| -> j::JackControl {
        let mut out_a_p = j::AudioOutPort::new(&mut out_a, ps);
        let mut out_b_p = j::AudioOutPort::new(&mut out_b, ps);

        let in_a_p = j::AudioInPort::new(&in_a, ps);
        let in_b_p = j::AudioInPort::new(&in_b, ps);

        let input0: &[f32] = &in_a_p;
        let input1: &[f32] = &in_b_p;

        let output0: &mut[f32] = &mut out_a_p;
        let output1: &mut[f32] = &mut out_b_p;

        let inputs = &[input0, input1];
        let outputs = &mut[output0, output1];

        dsp.compute(in_a_p.len() as i32, inputs, outputs);

        j::JackControl::Continue
    };
    let process = j::ClosureProcessHandler::new(process_callback);

    let active_client = j::AsyncClient::new(client, (), process).unwrap();

    println!("Press enter/return to quit...");
    let mut user_input = String::new();
    io::stdin().read_line(&mut user_input).ok();

    active_client.deactivate().unwrap();
}
```

**Comment by sletz** [comment]
Thanks for the code. Two remarks:
- `UI` trait is supposed to be able to `set/get` the Zones, but since the Zone index only is given as argument in `addHorizontalSlider` kind of method, how can an actual `UI` access the zone content?
- why is `buildUserInterface` part of the `pub trait Zone` then ?

**Comment by bkfox** [comment]
The main problem is that with the current system, reference to a zone is borrowed as reference, but it can only be borrowed as mutable once (and in this case [*can't be borrowed as immutable*](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#mutable-references)). This means that if a mutable reference of a zone is kept as mutable in the UI struct (in order for the ui to change it according to user's actions). Then the dsp's methods can't be called since they take `&self` or `&mut self` as argument and that the borrowed zone is under `self`. I'll eventually provide you an example to explain what I mean later.

So we can't take a reference and keep as we could in C++: its against language and safety rules.

Either UI implementation should own dsp in order to access its value (or share it through an shared pointer), or use intermediate accessor. Imagine that UI is implemented as followed:

```rust
pub struct SomeUI {
    zones: Arc<RwLock<Zone>>,
    // ui data
}

impl SomeUI {
    fn new(zones: Arc<RwLock<Zone>>) -> Self {
        let self = Self { zones: zones /* , ... */ }
    }

    // on event: self.zones.write().unwrap().set_zone(bound_zone_index, value)
}
```

Using Zone trait (which maybe should be rename `Zones`), allows to call methods generically in order to get/update the zones or build the user interface.

**Comment by sletz** [comment]
I've opened a #rust channel on Faust Slack (faustaudio.slack.com), it will be easier to discuss there.

**Comment by bkfox** [comment]
I can't access it, subscription requires an email with an "live.uwe.ac.uk" domain.

**Comment by sletz** [comment]
Give me a mail so that I can try to invite you.

**Comment by sletz** [comment]
Possibly https://discordapp.com/channels/382895736356077570/651037481017409595

**Comment by bluenote10** [comment]
I just wanted to start with UI work as well, and also noticed that the mutable borrow won't help in this case.

@bkfox Thanks a lot for your work here, your index-based proposal looks really good and should avoid shared ownership issues.

I haven't spend too much thought on it yet, and need to read the linked sources with more care, but here are a few random thoughts.

I'm wondering if `buildUserInterface(&self, ui: &dyn UI);` actually can be static instead, i.e., not take `&self` as argument at all. Basically the mapping of UI elements to their index is a static relationship and should not depend on any actual instance state. All that is needed is that the code generator makes sure that the `i`th index in the UI definition is semantically the same as the getter/setter of the `i`th parameter on the DSP instance. A use case for that is to have one UI that controls multiple instances of the same DSP. It would be awkward having to instantiate a DSP first in order create such a meta UI.

> Traits should be declared in a different module than the generated DSP's because it makes modularity much more difficult.

Totally agreed. I think the best solution is to provide all traits via the architecture file. In the simple "single file DSPs" architecture the trait definition can be at the top of the architecture file. In a bigger project with multiple DSPs that are supposed to share traits the architecture file could do `use super::UI` or so to base on the same traits. Basically the code generator would rely on having a few fixed trait names injected by the architecture file. Also I think it is crucial that we add a trait for the DSPs themselves in order to use multiple DSP classes under a unified interface. For instance:

```rust
trait FaustDsp {
    fn new() -> Self;
    fn getNumInputs(&mut self) -> i32;
    fn getNumOutputs(&mut self) -> i32;
    fn getInputRate(&mut self, channel: i32) -> i32;
    fn getOutputRate(&mut self, channel: i32) -> i32;
    fn init(&mut self, sample_rate: i32);
    fn compute(&mut self, count: i32, inputs: &[&[f32]], outputs: &mut[&mut[f32]]);
}

// generated code should then change from
impl MyDsp {
    // ...
}
// to
impl FaustDsp for MyDsp {
    // ...
}
```

This would simplify working with multiple DSPs a lot. Once we have that the functions you have proposed in the `Zone` trait might also be moved into the `FaustDsp` trait directly.

> UI trait is supposed to be able to set/get the Zones, but since the Zone index only is given as argument in addHorizontalSlider kind of method, how can an actual UI access the zone content?

My understanding is: If the UI knows the indices and has access to the DSP instance, it can use the getter/setter to interact with the DSP state. Of course the UI does not necessarily have to own the DSP instance directly, in practice there might be another bigger instance, which owns both the DSP and the UI and syncs data via the getters/setters.

**Comment by sletz** [comment]
No real progress on my side. Fell free to provide a working example possible with multiple UI controlling a same DSP for instance, or even a PR. Then I can adapt the code generator.

**Comment by bkfox** [comment]
@bluenote10  I totally agree on the principle of having a DSP trait. In the project I've linked to this is actually what i've done in order to be able to have a DSP graph (and actually it seems logical to have a generic trait).

I've though of having static methods for the `buildUserInterface` and `metadata`; however static method in traits will make them usable only when their size is known, as generic parameters, such as:

```rust
struct Foo<D: DSP> {
   pub dsp: D,
}

/// MyDsp is Sized, foo will have type `Foo<MyDsp>`
let foo = Foo { dsp: MyDsp::new() }
``` 

In the case of a generic dsp graph/container, we need to box DSP, which requires them to be Sized (while traits with static method can't have their size known):

```
struct Foo {
   pub dsp: Vec<Box<DSP>>
}
```

I also think this would be much more flexible to take iterable/indexable of `mut f32` as param (I'm not sure in which measure it is possible to have generic arguments in trait if we want to keep them boxable).

Here is an example of my implementation of DSP, although not up to date nor complete, it is working: [https://github.com/bkfox/foxlive/blob/master/libfoxlive/src/dsp/dsp.rs](https://github.com/bkfox/foxlive/blob/master/libfoxlive/src/dsp/dsp.rs)

**Comment by bluenote10** [comment]
Good point, we probably should not lose object safety. I think a good trade-off would be to have a static `buildUserInterface` as a free floating function, and the trait impl method would simply forward to that implementation. Or maybe something like this is possible:

```rust
impl MyDsp {
    fn buildUserInterfaceStatic(ui: &mut UI) { ... }
}

impl FaustDsp for MyDsp {
    fn buildUserInterface(&self, ui: &mut UI) {
        self.buildUserInterfaceStatic(ui);
    }
}
```

> I also think this would be much more flexible to take iterable/indexable of mut f32 as param

This part I don't understand yet. Similarly why are the keys in `BTreeMap<&'a mut f32, Metadata>` floats? I would have expected the lookup is "parameter index" => float.

**Comment by bluenote10** [comment]
@bkfox I think the best option is to use `where Self: Sized` annotations on static methods. This makes sure that the trait stays object safe, and the static functions are callable either in a generic/static context, but also on the actual impl structs. [Here is a draft](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4884e1f6d0447084775fae4069d67d0c).

**Comment by bkfox** [comment]
> This part I don't understand yet. Similarly why are the keys in `BTreeMap<&'a mut f32, Metadata>` floats? I would have expected the lookup is "parameter index" => float.

I maybe haven't been explicit, my bad. On "take iterable/indexable of mut f32 as param", I actually was talking about the `compute()` method.

About Metadata, I think we can even return a `Vec<(&'static str, &'static str)>`. This will result in an iterable that does not constraint the UI to use a specific container (such as BTreeMap, which responds to a certain use of key-value mapping).

I actually didn't though or tried to use the `where Self: Sized` clause on static methods, but this seems a good idea if it works.

**Comment by bluenote10** [comment]
Short note for external readers, because some discussion have taken place internally on Slack: The proposed solution in #454 is now available on the `rust-wip` branch, which also includes the performance optimizations from #466.

**Comment by bluenote10** [comment]
I think this issue can be closed. The `rust-wip` branch has long been integrated into `master-dev` and the issue of the UI declaration being unusable due to borrow limitation should be solved there.
