### ISSUE TITLE
faust2jack doesn't check jack version

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#41]
When running faust2jack with any of the released jack versions, you get:
``'jack_midi_reset_buffer' was not declared in this scope``

The solution is to build jack2 from git, as explained by @sletz [here](https://sourceforge.net/p/faudiostream/mailman/message/34985128/).

It would be nice if faust could check for an appropriate version of jack and give a warning/error if it's not there.

On a related note: a jack2 release would be great too, but that is already being worked on by @falkTX.

**Comment by magnetophon** [comment]
Update: there's been a [release](https://github.com/jackaudio/jack2/releases/tag/v1.9.11-RC1) of jack, but the rest of the above still holds.

**Comment by dvzrv** [comment]
Is this fixed in 1.9.12?

**Comment by sletz** [comment]
Yes.
