### ISSUE TITLE
FAUST_INPUTS and FAUST_OUTPUTS not declared in lib generated for Teensy

### ISSUE THREAD

**Issue by svenemtell** [grame-cncm/faust#413]
I compiled faust2teensy from master-dev commit b9d8cf262 and built an audio lib for Teensy with "faust2teensy -lib my.dsp". When compiling the lib with PlatformIO for Teensy I get errors like this:

lib/Tremolo/Tremolo.cpp: In member function 'virtual void Tremolo::update()':
lib/Tremolo/Tremolo.cpp:5129:40: error: 'FAUST_INPUTS' was not declared in this scope
 void Tremolo::update(void) { updateImp<FAUST_INPUTS, FAUST_OUTPUTS>(); }

When I replace FAUST_INPUTS and FAUST_OUTPUTS with 1 it works nicely.

**Comment by sletz** [comment]
Can you try https://github.com/grame-cncm/faust/commit/160cf2723a363ee14de32bc252ec11e6298f2cfe and report?

**Comment by svenemtell** [comment]
160cf27 fixes the problem.
Thanks for the fast response!
