### ISSUE TITLE
building VST3 plugins

### ISSUE THREAD

**Issue by ahihi** [grame-cncm/faust#415]
hello,

since the VST2 SDK no longer seems to be available anywhere, i am trying to build a VST3 plugin from my Faust code. do i understand correctly that the `faust2vst` and `faust2faustvst` backends only support VST2, and so `faust2juce` is the only option for VST3?

additionally i would like to build my plugin with no GUI at all. is there an easy way to achieve this with `faust2juce` (or any other backend)?

**Comment by sletz** [comment]
- you can produce VST3 plugins using the [iPlug2 framework](https://github.com/iplug2/iplug2) 
- you can use the [faust2pi](https://github.com/grame-cncm/faust/tree/master-dev/architecture/api) tool to create DSP without UI

**Comment by ahihi** [comment]
thank you! iPlug2 was super simple to set up. i'll direct further questions to them :)

**Comment by matthewjumpsoffbuildings** [comment]
I know we can do the iPlug/JUCE route for VST3, but it would be nice if there was a `faust2vst3` tool that was as simple and straightforwards as `faust2vst` and `faust2au`. The `faust2xxx` tools are especially great for iterating quickly on DSP experiments, and since the VST 2 SDK is no longer available it would be really good to have an option for VST 3.

How hard would this be to implement?

**Comment by sletz** [comment]
A bit of work for sure. Are you able to help?

**Comment by matthewjumpsoffbuildings** [comment]
I am happy to help testing, I took a look at the source of `faust2vst` to see if I could understand it enough to try and make `faust2vst3` myself but sadly it's all over my head.

Can the core faust command line compiler generate cpp files that would be VST3 ready? If so perhaps you can point me to an example of how to do that and I can try and cobble something together?

**Comment by sletz** [comment]
The `faust2faustvst` is more recent and complete and should be better adapted to VST3

**Comment by DBraun** [comment]
@joshgura If you don't mind JUCE then use faust2juce to make a VST3. It's probably the more tested way.
