### ISSUE TITLE
bin/ld: cannot find -lOSCFaust

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#419]
This is probably an issue with the way Faust is installed, but I don't know how to troubleshoot it.

When I try to compile with ``-osc``, I get: ``bin/ld: cannot find -lOSCFaust``.

**Comment by dfober** [comment]
Two possibilities:
a) the library has not been compiled (and thus is not installed)
b) or the compiler can't find it

For a), you can check that the library is present: it should be in `build/lib`  
You can also check your compile setup:
~~~~~~~
cd build
make cmake
~~~~~~~
and you should see a line starting with `-- Include targets:` : look is osc is there.
In case no, reconfigure your projects:
~~~~~~~
cd build
make cmake TARGETS=regular.cmake
~~~~~~~

For b), check the faust libraries location:
~~~~~~~
faust --libdir
~~~~~~~
and check that the OSC library is there, at the expected location.

Note that when compiling a project of your own, you're supposed to add the following compile and link flags:
~~~~~~~
-I$(faust --includedir)
-L$(faust --libdir)
~~~~~~~

You can find details about the compilation process and setup in the [faust wiki](https://github.com/grame-cncm/faust/wiki).
Hope that it helps

**Comment by magnetophon** [comment]
Thanks. 
Somehow, using the latest faust resolved it.
