### ISSUE TITLE
duplicate (and different) version of gradle included

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#42]
both `architecture/android/` (for `faust2android`) and `architecture/smartKeyboard/android/` (for `faust2smartkeyb` contain a verbatim copy of [gradle](https://gradle.org)

- the verbatim copies contain binaries (for the JVM). are you sure you want that in git?

- afaiu, gradle is really a build-system. are you sure you want to include a build-system in the faust repository (rather than the input for a build-system; e.g. you have `Makefile`s in your repo, but you usually don't include `make` itself)

- since there is no separate license for the included copies of gradle, one must really assume that this is © GRAME and GPL-2+; since you are distributing GPL binaries, you also should (well: must) distribute the source code as well.

- should the two gradle-wrappers be the same? Both `gradle-wrapper.properties` mention https://services.gradle.org/distributions/gradle-2.14.1-all.zip as the distribution but the jar-files do not match with the one that can be downloaded from that URL (and are different from each other as well). It's totally unclear what these jar-files contain (which brings us back to: please provide the sources)

From my naive point of view, I would prefer if gradle was not included at all, and instead the README.md (of `faust2android` and `faust2smartkeyb`) would contain instructions on how to get it from upstream (there's already a lengthy prerequisites section in the READMEs).

I have to admit that I don't know much about *gradle* and it might well be, that the only way to use it is to include the `gradle-wrapper`. If this is indeed the case, please add full license and copyright information (and if the license requires it, the source code).
If possible use the same versions for both *faust2android* and *faust2smartkeyb* (ideally don't duplicate but use only one copy for both architectures).

**Comment by rmichon** [comment]
Although there are lots of conversations around this topic (e.g., https://stackoverflow.com/questions/20348451/why-should-the-gradle-wrapper-be-committed-to-vcs suggests a few alternatives), the "standard"/recommended way of doing this is to include the Gradle wrapper: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html

As far as providing the source, this binary file gets automatically generated by Android Studio when a new project is created, so I'm not really sure where to find it... For now, we could may be just include a separate licence in the gradle folder of the template project? Also, I guess using the same gradle wrapper for faust2android and faust2smartkeyb is a good idea. 

It'd be great if this could wait a few weeks: I'm insanely busy these days and I'm teaching a workshop in 1.5 weeks that completely relies on these tools, and it'd be great not to break anything until then :).

**Comment by umlaeute** [comment]
has this been resolved?
