### ISSUE TITLE
Sliders get reset at the start of each note

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#421]
When I compile the following code:
```
import("stdfaust.lib");
level = hslider("level", -20, -60, 0, 1):si.smoo:ba.db2linear;
process = level;
```
with ``faust2jack -time -midi -nvoices 1 bug.dsp``, it resets the slider to 0 at the start of each note.
``faust2jaqt`` nor a different number of voices changes anything.

**Comment by sletz** [comment]
I don't understand: this is not a polyphonic aware DSP, so what is the point ?

**Comment by magnetophon** [comment]
Oh, sorry, I wasn't clear.
Forget the remark about number of voices.

The point is that at the start of each note, the output of the slider goes to 0 for a moment, then snaps back to it's actual value.

**Comment by sletz** [comment]
I still don't understand the problem, the DSP does not use the "freq, gate, gain" convention, so how does it answer to "notes" ?

**Comment by magnetophon** [comment]
It shouldn't, but it does.
When I don't touch the slider, it should just output a steady value.
Instead, it shortly outputs 0 at the start of each note, and then go back to the actual value.

Of course there is no point in compiling this example dsp with midi support.
This is just a minimal example to demonstrate the problem.

**Comment by magnetophon** [comment]
@sletz Is the above clear?

**Comment by magnetophon** [comment]
I figured out the issue:
I just needed to use polySmooth instead of smooth.
