### ISSUE TITLE
Unclear where effects do and do not work. 

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#422]
It seems that the ``effect =`` construction does not work on all platforms.

The manual has example code with [a link to the online compiler](https://faust.grame.fr/tools/editor?code=https://faust.grame.fr/doc/manual/img/src/exfaust149/exfaust149.dsp) that compiles it without the effect. 
The new online ide has no problem with [the same code](https://faust.grame.fr/ide/?autorun=1&voices=16&name=test1&inline=CmRlY2xhcmUgb3B0aW9ucyAiW21pZGk6b25dW252b2ljZXM6MTJdIjsKaW1wb3J0KCJzdGRmYXVzdC5saWIiKTsKZnJlcSA9IGhzbGlkZXIoImZyZXEiLDIwMCw1MCwxMDAwLDAuMDEpOwpnYWluID0gaHNsaWRlcigiZ2FpbiIsMC41LDAsMSwwLjAxKTsKZ2F0ZSA9IGJ1dHRvbigiZ2F0ZSIpOwplbnZlbG9wZSA9IGVuLmFkc3IoMC4wMSwwLjAxLDAuOCwwLjEsZ2F0ZSkqZ2FpbjsKcHJvY2VzcyA9IG9zLnNhd3Rvb3RoKGZyZXEpKmVudmVsb3BlIDw6IF8sXzsKZWZmZWN0ID0gZG0ueml0YV9saWdodDsK).

faust2jack and faust2jaqt also compile without the effect.

**Comment by sletz** [comment]
On the Faust Editor, you'll have to explicitly activate MIDI and choose number of voices in "Settings" (see [documentation](https://github.com/grame-cncm/fausteditor)). 

With `faust2jack` or `faust2jaqt` use -effect audio (see `faust2jaqt -h`)

**Comment by magnetophon** [comment]
Ah, yes. Thanks.
