### ISSUE TITLE
Unexpected "parameter must be a constant value"

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#425]
The code below gives me: ``ERROR : the parameter must be a constant value known at compile time (the node of the tree is not a float nor an int)``
￼
```
import("stdfaust.lib");
maxSeconds = 5;

process = ramp(yVal,reset);
ramp(n,reset) = select2(reset,_+(1/n):min(1),0)~_;
reset = button("reset");
// this one breaks:
yVal = hslider("yVal", 0, 0, maxSeconds*ma.SR, 1):int;
// this one works:
// yVal = hslider("yVal", 0, 0, maxSeconds*48000, 1):int;
```

**Comment by sletz** [comment]
Yes because `hslider` parameters must be constant and  `maxSeconds*ma.SR `is not known at compile time.

**Comment by magnetophon** [comment]
Ah, right. Thank you!
