### ISSUE TITLE
error: 'UI' has not been declared with faust2api -teensy

### ISSUE THREAD

**Issue by modularev** [grame-cncm/faust#436]
When trying to compile the code in the Arduino environment, I get the following message:

> 'UI' has not been declared void buildUserInterface(UI*);

 Also it is not clear how to initiate a new object and further I get the message

> 'class DspFaust' has no member named 'setDevice'

which would be necessary for communication with the audio shield.

What is the correct way of creating a new Object of the type DspFaust? I'm not sure that the description of this _Real Time Audio Digital Signal Processing With Faust and the Teensy_ matches the requirements to set this up

**Comment by sletz** [comment]
It appears that `faust2api -teensy foo.dsp `generates too heavy code. Prefer the `faust2teensy -lib foo.dsp` approach.

**Comment by modularev** [comment]
This was my alternative of trying to run a program which doesn't run with the Audio Library approach (note: it worked when the code was less heavy, after I implemented more features, the code compiled, but the teensy didn't even get to the setup() method)

Are there any possibilities to get the required memory, or at least the optimised buffer sizes from the faust code?

**Comment by sletz** [comment]
`'UI' has not been declared void buildUserInterface(UI*); ` this has just been fixed in master-dev branch

**Comment by sletz** [comment]
_"Are there any possibilities to get the required memory, or at least the optimised buffer sizes from the faust code? " ==>_ I don't understand that? Nite that the Faust Slack channel  (faustaudio.slack.com) can be simpler to use.

**Comment by modularev** [comment]
> `'UI' has not been declared void buildUserInterface(UI*); ` this has just been fixed in master-dev branch

great thanks. Regarding to compilation with the `faust2api -teensy`, the error is gone but now followed by
```
error: 'dynamic_cast' not permitted with -fno-rtti
         uiOwnedItem* owned = dynamic_cast<uiOwnedItem*>(it);
```

**Comment by sletz** [comment]
See https://github.com/grame-cncm/faust/issues/428
