### ISSUE TITLE
MAXSDK path cannot include space

### ISSUE THREAD

**Issue by modularev** [grame-cncm/faust#438]
When trying to set the path to the MAXSDK folder, having a space inside path (which is usually the case, as the max-sdk is installed into the packages folder inside of "Max 8") doesn't work when compiling with faust2max6 with following options `.../"Max 8"/... ` `.../'Max 8'/... ` or `.../Max\ 8/... `

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/252bae29ddee2d660fddfbdbbb42229d65accc6f.

**Comment by modularev** [comment]
Works now as expected.
