### ISSUE TITLE
faust2ios: BUILD FAILED

### ISSUE THREAD

**Issue by oshibka404** [grame-cncm/faust#440]
Running `faust2ios` with any `.dsp` files, I get not a very informative error:
```
$ faust2ios untitled.dsp
Compile with CoreAudio support in 64/32 bits
** BUILD FAILED **
```

Tried it with different `.dsp` files: no matter basic or sophisticated ones, result is always the same.

`faust2api -ios` works well (as well as `faust2api -android`).

macOS 10.15 Catalina, latest XCode installed.
Not sure what else details I should provide.

**Comment by sletz** [comment]
Run :  ` faust2ios -xcodeproj foo.dsp ` to generate the Xcode project. Then try to build it to understand what happens.

**Comment by oshibka404** [comment]
This way it works!

The project is created, opened, and app is successfully built (with 88 buildtime warnings, but with no fatal errors) and running on iOS simulation.

Although it doesn't give an idea of why it fails from command line, it solves my problem.

Thank you :)

**Comment by sletz** [comment]
One possible cause of error is when the generated project does not have the proper developer key or other setting.  In this case you will have to open the "template" iOS project here https://github.com/grame-cncm/faust/tree/master-dev/architecture/iOS, correct the settings, then install it again with "sudo make install". Then try `faust2ios` again.

**Comment by oshibka404** [comment]
Yes, you are right, it is an issue with code signing, thank you.

Apparently, one must have a provisioning profile in order to be able to build a package or test an app on an iPhone.

To have a provisioning profile and sign applications with a certificate one must be a member of Apple Developer Program and then create a certificate in [Certificates, Identifiers & Profiles](https://developer.apple.com/account/ios/certificate/) and register a device and do a lot of other apple-development-bullshit.

`faust2ios` itself works correctly. However, it would be handy to include the output of `xcodebuild` in the output of the script, at least in case of errors.

That's it, case solved. The issue can be closed, thank you.
