### ISSUE TITLE
location of pd.dll when cross-compiling

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#45]
are you [really promoting](https://github.com/grame-cncm/faust/blob/191656e8fc97a4cf3a381b9e9c126c63c57c50be/tools/faust2appls/faust2w32puredata#L25) to install the `pd.dll` required for compiling Pd-externals for W32 into `/usr/include/pd/` when cross-compiling?

a more appropriate (default) location would be `/usr/lib/i686-w64-mingw32/` (when using `i686-w64-mingw32-gcc` as cross-compiler). at least on a Debian system this is the designated are for "foreign arch" libraries (other distros may vary)

**Comment by sletz** [comment]
So if "other distros may vary" what are we supposed to do? Is there any real generic location that would be more appropriate?

**Comment by umlaeute** [comment]
no, I don't think that there is a generic installation directory for w32 dlls on linux systems (which is fair enough: there isn't even a generic installation directory for w32 dlls on *windows* systems).

however, there are a few places which I think are definitely **wrong**, and `/usr/include` is quite on top of this list.

- use a directory that is not in contradiction to the [Filesytem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)
- possibly use a directory that matches the location of other dlls on your linux system.
- make it configurable (either via some configuration file or via an environment variable, or both)

**Comment by sletz** [comment]
Thanks but well... either you can can send us a patch to do all this stuff, or just forget packaging this faust2w32puredata script...

**Comment by umlaeute** [comment]
i'll come up with a patch...
