### ISSUE TITLE
Compilation fails when ba.slidingMaxN is used

### ISSUE THREAD

**Issue by oshibka404** [grame-cncm/faust#451]
Not sure where I should report it to: here or in `fausteditor`.

Trying to run a program in Faust Editor, I got this alert:
<img width="496" alt="Screenshot 2020-06-20 at 20 03 03" src="https://user-images.githubusercontent.com/1549756/85208539-aae31680-b331-11ea-8db8-f25acb87902e.png">
Attempts to build using any other architecture also fail.

It seems to fall on this line:
```faust
levelGraph = abs : ba.slidingMaxN(32, 32) : ba.lin2LogGain : vbargraph("Level", 0, 1);
```

Without `ba.slidingMaxN(32, 32)` the program compiles successfully:
```faust
levelGraph = abs : ba.lin2LogGain : vbargraph("Level", 0, 1);
```
works fine.

_Side note: I've just realized that I should have used `an.amp_follower` instead, which works just fine._

**Comment by sletz** [comment]
Can you try with latest editor version: https://fausteditor.grame.fr or IDE https://faustide.grame.fr ? Thanks.

**Comment by sletz** [comment]
This compils on latest editor and IDE :

```
import("stdfaust.lib");
levelGraph = abs : ba.slidingMax(32, 32) : ba.lin2LogGain : vbargraph("Level", 0, 1);

process = levelGraph;
```
