### ISSUE TITLE
Need Help esp32 ttgo board can run effects like echo,delay,...

### ISSUE THREAD

**Issue by mahavoice** [grame-cncm/faust#452]
Hi,
You may guide me to solve my problems.
I have both ttgo and as thinker boards
And I am beginner with esp but I can run sawtooth example on both boards.
First problem is, I can not run effects like echo flange ,delay,.... On ttgo but I can run filters easily,when I run effects there is nothing to hear 
Second problem is , for ac101 I can just run sawtooth example I can not run even filters.
Third problem, I use just on line editor for compiling and I use Arduino IDE for programing and uploadind(esp devs boards for both boards),how can I run faustesp32 or faustesp32 ac101 on cmd window in windows10?
Any help will appricited 
Thank you in advance

**Comment by sletz** [comment]
Can you come on the Faust Slack channel here https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g ?
You will find more people to help you.

**Comment by mahavoice** [comment]
Hi Stephen,
Thank you for your help,but I cant go to slack because I am living in Iran
and slack did not let me to come in.
Is there any way to help?
Thank you.

**Comment by sletz** [comment]
The better use the Faust users mailing list, see https://lists.sourceforge.net/lists/listinfo/faudiostream-users
More people can help.

**Comment by mahavoice** [comment]
Thank you.
