### ISSUE TITLE
faust2jaqt wants alsa

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#473]
When I run `faust2jaqt test.dsp` I get:
```
/nix/store/k6rnzlmcvm37d0nw4fkz6ivmykmrdn39-binutils-2.31.1/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
make: *** [Makefile:105: test] Error 1
```

When I run `faust2jaqt -midi  test.dsp`, I get:
```
test_tmp.cpp:15259:10: fatal error: alsa/asoundlib.h: No such file or directory
15259 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:223: test_tmp.o] Error 1
```

When I make alsa available, it works.

Does that make sense?
I thought jack fully wraps alsa?

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/b6045f4592384076d3b383d116e602a95a000eb3.

**Comment by magnetophon** [comment]
Wow, that was a lot more work than I expected!
Thank you very much!

I'm building it as we speak.
