### ISSUE TITLE
MIDI glitches

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#474]
Hi @sletz, while working on the MIDI support for @pierreguillot's pd-faustgen, I noticed that although channel pressure seems to be supported, class MidiUI in MidiUI.h has the following wrong implementation at architecture/faust/gui/MidiUI.h, line 663:

~~~c++
                        } else if (gsscanf(fMetaAux[i].second.c_str(), "chanpress %u %u", &num, &chan) == 2) {
                            fChanPressTable[num].push_back(new uiMidiChanPress(fMidiHandler, num, this, zone, input, chan));
                        } else if (gsscanf(fMetaAux[i].second.c_str(), "chanpress %u", &num) == 1) {
                            fChanPressTable[num].push_back(new uiMidiChanPress(fMidiHandler, num, this, zone, input));
~~~

This is obviously an editing blunder (copy-paste from keypress, I assume), since channel pressure has a single data byte, i.e., no num (note number) argument, just a velocity value.

Also, the Faust manual doesn't seem to mention the `midi:chanpress` meta data in https://faust.grame.fr/doc/manual/#midi-and-polyphony-support. Neither does it mention the optional extra channel argument that can be seen in MidiUI.h. So it would be nice if this could be updated at some point (Section 9.2 in the Faust Quick Reference also needs to be fixed so that it matches the current implementation; that section seems to be badly outdated).

**Comment by sletz** [comment]
Well I think the implementation is correct (one value (`= press)` is parsed) but I'm not sure anymore it really makes sense at all.  The MIDI `press` is supposed to be mapped to the UI element range, do you see a valid use-case for it?

Note that the most recent documentation (not deployed yet) is here: https://github.com/grame-cncm/faustdoc/blob/master/src/manual/midi.md

**Comment by agraef** [comment]
Ok, so this *matches* against the data byte of the incoming value? And on the output side it will only ever produce this single value? I can't think of a single use case for that, I'm afraid.

Button controls are much better mapped to CCs where the convention is that anything >= 64 means "on", and anything less than that is off (but >=1 as on, 0 = off also makes sense to me). You might also conceivably use MIDI notes in that fashion, if it doesn't interfere with polyphony.

At least that is what I assume would be in line with the semantics of MIDI. But what do I know? ;-)

**Comment by agraef** [comment]
BTW, thanks for the link, I'm going to read the new doc asap.

**Comment by sletz** [comment]
I just reworked the whole thing. Now `[midi:chanpress] `or `[midi:chanpress chan]` can be used and the [0, 127] value range will be mapped to the slider/nentry actual range. See https://github.com/grame-cncm/faust/commit/0531bb50558b12a930cfa5820c9095fdc153c985.

The documentation has been updated, see https://github.com/grame-cncm/faustdoc/blob/master/src/manual/midi.md

**Comment by agraef** [comment]
Thanks!
