### ISSUE TITLE
faustgen-1.45-win64.zip released without faustgen\externals\msp\faustgen-resources

### ISSUE THREAD

**Issue by AlexanderPavlenko** [grame-cncm/faust#481]
This seems to cause an error in Max.

**Comment by sletz** [comment]
Right ))-:

 In the meantime you'll have to manually create the faustgen-resources folder and put the libraries in there (from https://github.com/grame-cncm/faustlibraries/tree/cde57d76dd8c4b124998a5490164e4b58ae9495f)
