### ISSUE TITLE
Remove faust-manual for Faust repo (moved in faustdoc)

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faust#488]
This folder https://github.com/grame-cncm/faust/tree/master-dev/documentation/faust-manual should be removed, since it is now separated in https://github.com/grame-cncm/faustdoc

**Comment by rmichon** [comment]
Good point, it's been done here: https://github.com/grame-cncm/faust/commit/9fd177e9ca99228aa0324445bdcc66864135b0b4
