### ISSUE TITLE
Faust installer didn't come with faust2esp32. Is there a precomipled w32 binary available. 

### ISSUE THREAD

**Issue by mrSilkie** [grame-cncm/faust#490]
I'm struggling to compile the faust2esp32 so that i can run _faust2esp32 -lib my.dsp_ but it's not working. I'm doing the following in power shell.
```
PS C:\dev\Faust\faust\architecture\esp32> cd C:\dev\Faust\faust\architecture\
PS C:\dev\Faust\faust\architecture> cmake esp32
```

make doesn't work on my system, when I try, I get the following.
`make: *** No targets specified and no makefile found.  Stop.`

cmake is a bit more useful and instead returns;

> -- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
> CMake Error at CMakeLists.txt:3 (idf_component_register):
>   Unknown CMake command "idf_component_register".
> 
> 
> CMake Warning (dev) in CMakeLists.txt:
>   No cmake_minimum_required command is present.  A line of code such as
> 
>     cmake_minimum_required(VERSION 3.16)
> 
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/dev/Faust/faust/architecture/CMakeFiles/CMakeOutput.log".
> 

Could somebody please explain what changes i need to make to the [supplied makefiles ](https://github.com/grame-cncm/faust/blob/master-dev/architecture/esp32/CMakeLists.txt) to get this to compile? I don't understand cmake files enough to solve this on my own. the idf_component_register is especially confusing as I'm assuming it's related the the esp_idf? correct me if I'm wrong.

**Comment by sletz** [comment]
`faust2esp32` is a pure bash script, so you don't have to _compile_ it. What you'll need is to have the Faust compiler installed on your machine.

But note that using Unix like script on Windows is more difficult by nature.  

Have you tried to simply use the [Faust Web IDE](https://faustide.grame.fr/) where you can compile  for ESP32 ? 

<img width="1288" alt="Capture d’écran 2020-09-10 à 08 40 48" src="https://user-images.githubusercontent.com/1430487/92690720-c44c9b00-f341-11ea-823d-c13755f0740c.png">

**Comment by mrSilkie** [comment]
I'd like to use the online compiler if possible. However, how do I make use of the **midi, nvoices** and most importantly, **-es8388** for the following?

> faust2esp32 [-lib] [-gramophone] [-multi] [-midi] [-nvoices <num>] [-wm8978 or -ac101] <file.dsp>

I may be approaching this the wrong way however. If I am, please let me know.

**Comment by sletz** [comment]
Then better install a Linux VM on your Windows system (or use the Linux that is already there?) ans start from that.
