### ISSUE TITLE
Please add cmake variables to enable language backends

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#495]
For example, the ```CPP_BUILD``` define should be enabled by the cmake variable, ex. ```ENABLE_BACKEND_CPP```, along with adding the ```c_code_container.cpp ``` file to C++ files to compile.

Currently I have to define ```CPP_BUILD``` and also add this patch:
```
--- build/CMakeLists.txt.orig   2020-08-03 13:32:44 UTC
+++ build/CMakeLists.txt
@@ -53,7 +53,7 @@ endif()
 
 ####################################
 # source and headers files
-file (GLOB SRC ${SRCDIR}/*.cpp ${SRCDIR}/*/*.cpp ${SRCDIR}/draw/*/*.cpp ${SRCDIR}/generator/fir/*.cpp)
+file (GLOB SRC ${SRCDIR}/*.cpp ${SRCDIR}/*/*.cpp ${SRCDIR}/draw/*/*.cpp ${SRCDIR}/generator/fir/*.cpp ${SRCDIR}/generator/cpp/*.cpp)
 file (GLOB HH  ${SRCDIR}/*.hh  ${SRCDIR}/*/*.hh  ${SRCDIR}/generator/fir/*.hh)
  
 ####################################
```

This would also fix https://github.com/grame-cncm/faust/issues/458

**Comment by sletz** [comment]
` c_code_container.cpp`  is part of the C backend, not the C++ one.  Or do you mean `cpp_code_container.cpp`  file ?

**Comment by yurivict** [comment]
Sorry, I meant ```cpp_code_container.cpp```.

**Comment by sletz** [comment]
Can you prepare a Pull Request?

**Comment by yurivict** [comment]
Sorry, I am only a port maintainer, and don't have resources to create pull requests.

**Comment by sletz** [comment]
I don't understand why?

**Comment by yurivict** [comment]
Because I do this in my free time, and have my own projects and a $JOB to work on.

I also do not believe in the model when the project extensively depends on external contributions. I don't think that this can ever lead to a quality project.

**Comment by sletz** [comment]
I suggest you now stop this kind of contribution.

**Comment by yurivict** [comment]
Why did you close this bug? Is it fixed?
