### ISSUE TITLE
Faust to CodeBlocks converter

### ISSUE THREAD

**Issue by fewtubefx** [grame-cncm/faust#496]
Hello, I've tried to convert faust dsp code to juce, than in code blocks, but it is not working perfect, also plugin too huge (about 50 mb).
Is it possible to make module that convert faust dsp code to Code Blocks directly?
Code Blocks - open source powerful and cross platform IDE.

**Comment by sletz** [comment]
I'm not sure to understand, I suggest you come on the Faust Slack channel here: https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g
