### ISSUE TITLE
ir2dsp error

### ISSUE THREAD

**Issue by MacroMachines** [grame-cncm/faust#498]
I am getting the following error:
`
NICHOLASs-MacBook-Pro:ir2dsp nicholascraftisiii$ python3 ir2dsp.py /Users/nicholascraftisiii/Dropbox/FAUST/Modal\ Reference/Gon
g/GO2_SoFi_ff_A3.wav GONG_IR.dsp 0.001 12
Reading wav file...
ir2dsp.py:31: WavFileWarning: Chunk (non-data) not understood, skipping it.
  (fs, x) = read(soundFile)
Computing FFT...
Detecting FFT peaks...
Traceback (most recent call last):
  File "ir2dsp.py", line 65, in <module>
    peaksGains = peaksGains/(np.max(peaksGains))
  File "<__array_function__ internals>", line 5, in amax
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
`

**Comment by sletz** [comment]
hugh? What are you trying to do in the first place ?

**Comment by MacroMachines** [comment]
I think I got it working by adjusting my input parameters, I suggest the solution of a simple example file and expected ranges for the values / formatting of how to run it, and steps to install required libraries, that would make this more accessible

`NICHOLASs-MacBook-Pro:ir2dsp nicholascraftisiii$ python3 ir2dsp.py /Users/nicholascraftisiii/Dropbox/FAUST/Modal\ Reference/Gon
g/GO2_SoFi_ff_A3.wav GONG_IR.dsp -30 1
Reading wav file...
ir2dsp.py:31: WavFileWarning: Chunk (non-data) not understood, skipping it.
  (fs, x) = read(soundFile)
Computing FFT...
Detecting FFT peaks...
Calculating T60 values...
Frequency peaks and corresponding gains and T60 has been successfully calculated.
Writing the dsp file...
GONG_IR.dsp.dsp has been successfully created!
NICHOLASs-MacBook-Pro:ir2dsp nicholascraftisiii$ `

**Comment by MacroMachines** [comment]
Ok, I generated a model, but the model only played the input click because the scaling of the T60s was way too low, so I scaled them up.. It may be worth adding a "DECAY MULTIPLIER" variable and slider into the generated code, I had to multiply it by at least a hundred to get something like the input.  Going to try some others.

**Comment by sletz** [comment]
Are you able yo fix that and propose a Pull request?

**Comment by MacroMachines** [comment]
> Are you able yo fix that and propose a Pull request?

I realized there were a few things wrong with the generated .dsp file, and a few improvements as well.  it appears that maybe the pm.modeFilter may have changed since this was made, as the structure of the generated modalModel had the gain as a multiplier where it is now a 3rd parameter of pm.modeFilter.  I changed this and multiplied the t60 by 100. and it sounds a fair bit like my original input file.

I would love to fix and propose a Pull request, but I haven't done that yet, as I understand it, I fork the repo, clone it to my drive, make a branch, make the change, push it back to my repo, click compare and pull request, and then click Create pull request.  
I will try this, however, it may be easier, in this case, to just show you what I changed since it's so simple to at least get it functional.

I changed modalModel from:
`modalModel(n,modeFreqs,modeRes,modeGains) = _ <: par(i,n,gain(i)*pm.modeFilter(freqs(i),res(i))) :> _`
to:
`modalModel(n,modeFreqs,modeRes,modeGains) = _ <: par(i,n,pm.modeFilter(freqs(i),res(i)*100.,gain(i))) :> _`

note the addition of the *100. after res(i) and the change of the position of gain(i) to being within the third parameter for pm.modeFilter

I also multiplied the `process = pm.impulseExcitation(gate) ` by 0.1 to keep it from clipping. so now it reads:
`process = pm.impulseExcitation(gate)*0.1 : myModel <: _,_; `

**Comment by MacroMachines** [comment]
I cloned the repository and this looks correct in the python file in the cloned version already, let me double check the version on my mac and see if I was using an old version of faust.  Here is what is in the version of the .py I am finding in my clone as of now:
`file.write("\nmodalModel(n,modeFreqs,modeRes,modeGains) = _ <: par(i,n,pm.modeFilter(freqs(i),res(i),gain(i))) :> _\n")`

**Comment by MacroMachines** [comment]
I submitted a pull request, not sure if it came through

**Comment by sletz** [comment]
See https://github.com/grame-cncm/faust/commits?author=MacroMachines
