### ISSUE TITLE
Mesh2Faust Demos not working

### ISSUE THREAD

**Issue by MacroMachines** [grame-cncm/faust#500]
the files from this page : https://faust.grame.fr/community/made-with-faust/mi-faust/ are giving an error in the editor:
ERROR IN SEQUENTIAL COMPOSITION : RoutingMasstoLink:B the number of outputs must be equal to the number of inputs

this type of error is happening for all of the demos of the mesh2faust examples.

working on some physical modeling instruments would love to be able to try this feature out.

**Comment by sletz** [comment]
Those pages link to old versions. The mi-faust examples included in Faust distribution have been fixed https://github.com/grame-cncm/faust/tree/master-dev/examples/physicalModeling/mi-faust
