### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by Reaper10** [grame-cncm/faust#501]
I want to help by making a piano, epiano, harpsichord and Celesta body resonator for faust. I know about mesh2faust and svg.  Can you help me with learn how  to do this?

**Comment by sletz** [comment]
I'm not sure to understand, I suggest you come on the Faust Slack channel here: https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g our the Faust Audio Programmer discord with a #faust channel (https://theaudioprogrammer.com/community/).
