### ISSUE TITLE
faust2csound faust to cabbage 

### ISSUE THREAD

**Issue by fewtubefx** [grame-cncm/faust#508]
Is it possible to implement faust compiler with faust to csound compiler. For cabbage IDE https://cabbageaudio.com/

**Comment by sletz** [comment]
It seems like Cabbage is really developed around and with Csound. So what is the point?

**Comment by fewtubefx** [comment]
The point is that faust2csound gives *.so file, as I understand
And cabbage need csd

**Comment by sletz** [comment]
Yes, Faust for Sound can only generate the instrument part, and has nothing to to with the score file.

**Comment by fewtubefx** [comment]
And what about effect, not instrument plugin?
There is no tutorial and information how to do that.

**Comment by sletz** [comment]
Same issue: by instrument I mean the DSP part (versus the score part).
