### ISSUE TITLE
createPolyDSPFactoryFromString, how to set controls ? 

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#509]
Hello,

given a synth loaded with createPolyDSPFactoryFromString (for instance KarplusStrong from the library), setting the controls that were retrieved through the UI discovery mechanism don't seem to work - whatever I set in the float* does not seem to affect the sound in any way... e.g. in the following, setting damping or sustain to 0 or 1 does not affect the sound in any meaningful way.

```
import("stdfaust.lib");
process = pm.ks_ui_MIDI <: _,_;
```
Upon loading, I'm getting `llvm_dsp_poly_factory : fEffectFactory score : 80 : ERROR : undefined symbol : effect` errors with all the patches that I'm trying to load, is that related maybe ? (i'm still getting sound out of it though)

Thanks !

**Comment by sletz** [comment]
- this `createPolyDSPFactoryFromString`  API use is tested in https://github.com/grame-cncm/faust/blob/master-dev/tools/benchmark/poly-dynamic-jack-gtk.cpp  and works normally. So  `poly-dynamic-jack-gtk -llvm -midi -nvoices 8 jmc.dsp` with your provided code opens a GUI where controls allow to change the state of all voices. How do you control the DSP ?
- polyphonic ready DSP code (using the` freq/gate/gain` convention) can also have a global effect defined in the same DSP (see https://faustdoc.grame.fr/manual/midi/ _Audio Effects and Polyphonic Synthesizer_ section). This error occurs when the DSP does not actually contain any effect, but can still be used as a pure polyphonic instrument.

**Comment by jcelerier** [comment]
hm, I tested the poly-dynamic-jack-gtk, is this how it is supposed to work ?  (the sound is me sending some midi notes)

https://streamable.com/ynkavj

- gate, gain, freq and sustain don't seem to do anything
- damping and bend do work however


i seem to remember that "gate" used to trigger a note but now I'm not sure and maybe this is all expected... in any case I have some issues in my own code as in mine changing "damping" does not work, investigating...

**Comment by jcelerier** [comment]
(I'm on linux, on 2dfed13413c741f6cdf905e4db20d512bb535d17 with llvm 10.0.1)

**Comment by sletz** [comment]
Yes in polyphonic mode`  gate, gain, freq, sustain` are connected to MIDI et and are not really supposed so be controlled "manually". But other parameters can be controlled globally.

**Comment by jcelerier** [comment]
ah, think I found the issue - I was not calling GUI::updateAllGuis();

but looking at it, this does not look thread safe as in my case it could very well be that one thread creates new Faust objects, while another thread processes the audio for existing Faust objects (and thus calls `updateAllGuis()` after setting the zones to their latest values) - is there a way to get the object on which I should call GUI::updateAllZones() as that one does not seem to depend on global state ? 

(sorry for the noise)

**Comment by sletz** [comment]
Not sure to understand the last sentence, but yes in general this model is not thread-safe. You will have to protect against calling `updateAllGuis() ` while doing new DSP creation with possibly adding stuff in `GUI::fGuiList`

**Comment by jcelerier** [comment]
I'm also noticing something a bit weird: 

I do: 

    auto factory = createPolyDSPFactoryFromString(...);
    auto instance = factory->createPolyDSPInstance(...);

which ends up calling 

    new mydsp_poly(fProcessFactory->createDSPInstance(), nvoices, control, group);

and then during the voice allocation (I allocate a static, fixed number of voices in this case)

    dsp_voice(dsp* dsp):decorator_dsp(dsp)
    {
        // ...
        // here the sample rate hasn't been initialized as we could not call init(theSampleRate) on the dsp yet since it is being constructed 
        fMaxRelease = dsp->getSampleRate()/2; // One 1/2 sec used in release mode to detect end of note
    }

**Comment by jcelerier** [comment]
okay, what I had hoped is that I could get access to the specific UI object of my dsp instances in order to bypass that global vector

**Comment by sletz** [comment]
```
 fMaxRelease = dsp->getSampleRate()/2; // One 1/2 sec used in release mode to detect end of note
 ```
Seems a bug yes.. not sure I saw it in my specific use case, I'll have to do a test. In the meantime I guess using 44100 for  SR should be OK in most cases.

**Comment by jcelerier** [comment]
yep. thanks for the help !
