### ISSUE TITLE
Make SR limit much higher

### ISSUE THREAD

**Issue by dariosanfilippo** [grame-cncm/faust#513]
Hello.

Since Faust can also be used to generate raw data offline, for example using faust2csvplot, it would be nice to be able to work with arbitrary sample-rates. 

Specifically, I would need this to simulate 1bit processing on FPGAs with sample-rates as high as ~100 MHz.

I would also consider that some RME devices are now providing sample-rates up to 768 kHz, hence the current sample-rate limit could be pushed even to just cover such online configurations.

If the SR limit is changed to a much higher number, then perhaps the limits for the number of generated samples (-n), and the starting position of the generated samples (-s), could be changed too in targets such as faust2csvplot.

Best,
Dario

**Comment by sletz** [comment]
We'll not raise the max SR value, since it is used internally to set the max size of delay lines. Better setup platform.lib value for your own need.

**Comment by sletz** [comment]
@dariosanfilippo can we close this one ?

**Comment by dariosanfilippo** [comment]
Yes, thank you.
