### ISSUE TITLE
voice stealing generate click

### ISSUE THREAD

**Issue by clementTal** [grame-cncm/faust#518]
In midi polyphonic, if all voices are playing, playing a new note will stop the fist played note immediatly, generating a "click".
Is there a way to inprove that in my DSP or should it be in the faust compiler (maybe adding a tiny release on the sealed note) ?

Thanks

**Comment by sletz** [comment]
The voice stealing algorithm code is done in the C++ wrapper, see: https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/dsp/poly-dsp.h, stealing the older voice in release mode, than then the older playing note (if first part fails). Stealing a voice may indeed cause a click. Do you have a limitation in the  number of voices you can preallocate ?

**Comment by clementTal** [comment]
I've set 'declare options "[midi:on][nvoices:4]";' and I call the compiler with 'faust2jaqt -midi -nvoices 4' to limit to 4 voices.
Is it what you mean ? Or do I missed somethings ?

Thanks

**Comment by sletz** [comment]
You can possibly allocate more voices by raising `nvoices` to whoever you need.

**Comment by clementTal** [comment]
Sure, but voice stealing will always click.
I'll looked at a solution whether in faust compiler or in a midicontroller code I'll add.

**Comment by sletz** [comment]
Discussion the issue on Faust Slack can be easier: Join me on Slack — it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g
