### ISSUE TITLE
Faust2Teensy Tutorial

### ISSUE THREAD

**Issue by jnehring** [grame-cncm/faust#523]
Hello,

unfortunately the Faust2Teensy Tutorial disappeared. This page is linked from many different places:

https://faust.grame.fr/doc/tutorials/index.html#dsp-on-the-teensy-with-faust

Sorry but where can I find the tutorial?

Thank you :)

**Comment by sletz** [comment]
Here now : https://faustdoc.grame.fr/tutorials/teensy/
