### ISSUE TITLE
Documentation missing for ma.decimal

### ISSUE THREAD

**Issue by jnehring** [grame-cncm/faust#526]
Hi, 

Im trying to learn Faust. In the example code I found the expression ma.decimal in the [faust manual](https://faustdoc.grame.fr/manual/syntax/), but neither the manual nor the documentation of [math library](https://faustlibraries.grame.fr/libs/maths/) state what ma.decimal does.

I hope I am not asking a stupid question because I have no idea about Faust. Can you update the documentation or tell me where to find information about ma.decimal?

Thank you Jan

**Comment by sletz** [comment]
`ma.decimal` has actually been replaced by `ma.frac `, see https://faustlibraries.grame.fr/libs/maths/#mafrac
