### ISSUE TITLE
Keyword __restrict__ not recognized by compilers

### ISSUE THREAD

**Issue by jpcima** [grame-cncm/faust#532]
Faust generates the `__restrict__` attribute, not recognized by the Microsoft compiler.
The attribute `__restrict` is recognized by Microsoft, as well as GCC and Clang up to some very old versions.
(at least the versions 4.1.2 and 3.0.0, respectively)

**Comment by sletz** [comment]
https://github.com/grame-cncm/faust/commit/1336f5a58c4384c1acd189f701252b3d3c6667b2 should fix that.
