### ISSUE TITLE
faust-mode.el needs to be updated in new release

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#533]
This is just a quick reminder that the faust-mode.el in the latest release (2.27.2) doesn't work on systems like Arch which already have Emacs 27. This was thankfully fixed upstream by @magnetophon and ported over by @sletz already in October, but a new release is still in order so that @dvzrv can update the Arch package in the official repositories.

**Comment by sletz** [comment]
A new release will be done in january hopefully.

**Comment by agraef** [comment]
Thanks!
