### ISSUE TITLE
How to costumize the UI?

### ISSUE THREAD

**Issue by nicolalandro** [grame-cncm/faust#541]
Is it possible to specify custom .qss style sheet when export qt5 lv2 plugin? Or Exist any other way to customize the UI of faust application?

**Comment by sletz** [comment]
AFAICS qt5 lv2 is the work of @agraef and/or ont of his student. Hopefully Albert can answer here.

**Comment by sletz** [comment]
And got the Faust `QTUI` architecture (https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/gui/QTUI.h), that is the one used with `faust2caqt`, `faust2jaqt`, it is using some stye here: https://github.com/grame-cncm/faust/tree/master-dev/architecture/faust/gui/Styles

**Comment by nicolalandro** [comment]
It is not possible to use in lv2 plugin the created GUI with the GUI Builder?

**Comment by sletz** [comment]
Not sure to understand since I did not write this code. Can you explain more?

**Comment by nicolalandro** [comment]
I speack aboutt the Gui Builder feature into the web IDE, it is possible to export the lv2 plugin with this gui?

**Comment by sletz** [comment]
In the Web IDE: the LV2 target is available in the _linux_ platform only for now.

**Comment by sletz** [comment]
Ah sorry: the Gui builder is to export pure WebAssembly plugins. It is a tool developed by @micbuffa and his team for [WAP plugins](https://github.com/micbuffa/WebAudioPlugins). Right now it is more a research project than a really usable product.

**Comment by nicolalandro** [comment]
Ok thanks!
