### ISSUE TITLE
Feature request: load rc file in faust2sndfile

### ISSUE THREAD

**Issue by magnetophon** [grame-cncm/faust#542]
It would be great if there was a way to interactively tweak the parameters of a dsp and then use those to create a `.wav` with a specified length, synced to `ba.time`.

Context: I am making wavetables for another synth.

Note from @sletz on slack:

> A piece of C++ hacking in https://github.com/grame-cncm/faust/blob/master-dev/architecture/synthfile.cpp and https://github.com/grame-cncm/faust/blob/master-dev/architecture/synthfile.cpp

**Comment by sletz** [comment]
Added in https://github.com/grame-cncm/faust/commit/fbd7ce677487781cc5fead572704f7cb37c356ee
In order to keep the old behaviour (and not breaking other possible use-cases), you'll have to explicitly add `-rc 1` to use the .rc file.

**Comment by magnetophon** [comment]
Awesome, I will go try it now!
Thank you very much!

The cherry on the cake would be if `-rc` with no arguments would use the default rc file, and `- rc ~/my-file` would load that my-file.

**Comment by magnetophon** [comment]
Sorry for not getting back to you.
This works great, thank you!
