### ISSUE TITLE
Text is illegible when compiling to web platform

### ISSUE THREAD

**Issue by darkoverlordofdata** [grame-cncm/faust#544]
A project I’m working on is to create a guitar amplifier in the browser using the Web Audio api. It’s actually similar to the example SAM/effects/effectsForBrowser.dsp, so I’ve been playing with that, and though I’m not loving the gui, I do like the sound. So I compiled to the web platform using the webaudiowasm architecture.
The problem is that then the fonts are illegible. It is fine when I just click on Run, but when I build it and run the output html, the fonts are the same color as the background, and I can’t read them. I can edit the html, and modify the css, but that seems like the wrong way to go about this. Is there a template I can tweak to make the output legible?

**Comment by sletz** [comment]
Hi Bruce,

The automatically generated HTML page uses old rendering GUI code that is not really easy to tweak for your own needs. For now there is no really other solution than trying to do it anyway..., or completely remove the audio GUI and use something else (likeFaustUI : https://github.com/grame-cncm/faust-ui which is actually use din the Faust Web IDE) or design something from scratch which is obviously a bit of work.

Stéphane

**Comment by darkoverlordofdata** [comment]
I'll take a look at the faust-ui repo. Thanks!
