### ISSUE TITLE
Please add support for pcm5102  on ESP32 or point me into proper direction.

### ISSUE THREAD

**Issue by reverbrick** [grame-cncm/faust#545]
Hello I am digging into Faust and like it very much.
I have ESP32 (ESP32 DevKitC v4 wrover) and few cheap dacs called CJMCU-5102
I thought it is a matter of correct pins and I am good to go, but I am unable to get any sound.
For now I only succeeded with following arduino example https://github.com/dvxlab/esp32_bt_music_receiver
Looking at existing dac drivers for Faust (ex. wm8978) I see only this definitions:
#define I2C_MASTER_NUM 1 /*!< I2C port number for master dev */
#define I2C_MASTER_SCL_IO 18
#define I2C_MASTER_SDA_IO 19
How can I find which gpios are used for LCK, DIN and LCK.
Any help from experts would be nice.

**Comment by sletz** [comment]
I've sent you an invite link for the Faust Slack channel. You'll probably get more help there.

**Comment by reverbrick** [comment]
Thanks, I'll have a look as soon as I get it.

**Comment by sletz** [comment]
Or use this one: https://join.slack.com/t/faustaudio/shared_invite/zt-a624szlz-fL4v2DTR~ZGlI7wARryT7g
