### ISSUE TITLE
INCLUDE_DYNAMIC or INCLUDE_STATIC should be enabled by default, otherwise only headers are installed and not library

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#553]
Here: https://github.com/grame-cncm/faust/blob/master-dev/build/CMakeLists.txt#L35

Version: 2.30.5

**Comment by dfober** [comment]
Would a specific target do the trick?

**Comment by yurivict** [comment]
> Would a specific target do the trick?

Yes.

**Comment by dfober** [comment]
there is now a 'libsall' target, available from the main Makefile, that builds all the libraries in static and dynamic form.
That's available from the master-dev branch. Could you check that it's what you need?

**Comment by yurivict** [comment]
> Could you check that it's what you need?

I am fine now, I just thought that cmake should not allow to install headers without any libraries enabled.
