### ISSUE TITLE
faust2supercollider "Audio Rate inputs"

### ISSUE THREAD

**Issue by Hyppasus** [grame-cncm/faust#565]
Is it possible to implement the choice of rates (Audio, Control) for the inputs of the produced Ugen?
The UGen generated by the script assumes Control Rate (kr) inputs. Audio Rate (ar) inputs are crucial for audio rate modulations such as FM. To illustrate the point see the SuperCollider code below.

```
/*
faust2supercollider -noprefix SimpleOsc.dsp
*/

/*
//SimpleOsc.dsp
import("stdfaust.lib");
decimalpart(x) = x-int(x);
phase(f) = f/ma.SR : (+ : decimalpart) ~_;
osc(f) = phase(f) * 2 * ma.PI : sin;
out = osc(hslider("freq", 440, 0, 10000, 1) )* hslider("gain", 0.961, 0.0, 1.0, 0.001);
process = out <: _,_;
*/

{SimpleOsc.ar(200)}.play

x={arg freq=1, amp=0.5;SimpleOsc.ar(SinOsc.ar(freq,0,400,400)!2)*amp}.play
y={arg freq=1, amp=0.5;SinOsc.ar(SinOsc.ar(freq,0,400,400)!2)*amp}.play

x.set(\freq, 200);
y.set(\freq, 200);

**Comment by sletz** [comment]
> The UGen generated by the script assumes Control Rate (kr) inputs. 

Not sure to understand here. Where do you see that?

BTW discussion the issue on Faust Slack channel (see https://faust.grame.fr/community/help/) will probably be easier.

**Comment by Hyppasus** [comment]
When the resulting Ugen is modulated at the audio rate it can be heard that the input is calculated at a lower rate.
Moving towards Slack. Thnak you.

**Comment by Hyppasus** [comment]
The solution is to use an audio input with `si.bus`

````
import("stdfaust.lib");
decimalpart(x) = x-int(x);
phase(f) = f/ma.SR : (+ : decimalpart) ~_;
osc(f) = phase(f) * 2 * ma.PI : sin;
out = osc(si.bus(1) )* hslider("gain", 0.961, 0.0, 1.0, 0.001);
process = out <: _,_;`````

Then in supercollider the input should be AR such as
`{SimpleOsc.ar(DC.ar(1200),0.1)}.play`
