### ISSUE TITLE
faust2supercollider/faust2sc breaks with ruby > 2.7

### ISSUE THREAD

**Issue by madskjeldgaard** [grame-cncm/faust#572]
Hi all

Recently ran into a nasty issue with `faust2supercollider` and `faust2sc` both creating empty `.sc` files. 

When i added the `-d` flag, I got this output: 

```
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadErro
r)
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/bin/faust2sc:26:in `<main>'
Retaining intermediate products directory 'faust.o3Bubx'
```

As you can see, this happens on Ruby 3.0.0. 

I downgraded to 2.7 and now it seems to work again.

**Comment by sletz** [comment]
No experience in Ruby here (those SC related tools were an external contribution). Do you think you can fix the [faust2sc code](https://github.com/grame-cncm/faust/blob/66cdb528642fdf3d607fec1b7ea7f386d7b709a4/tools/faust2sc-1.0.0/faust2sc) ?

**Comment by salkin-mada** [comment]
@madskjeldgaard and I will have a look at the faust2supercollider code tomorrow. Maybe we will learn something :)

**Comment by madskjeldgaard** [comment]
Hi again. Sorry, it wasn't the faust2supercollider tool it seems. In my system's ruby upgrade from 2.7 to 3.0 the `rexml` ruby module seems to have been removed. Installing via `yay -S ruby-rexml` fixed this issue and it now works with 3.0. Sorry for the confusion.

**Comment by madskjeldgaard** [comment]
@dvzrv we may need to include `ruby-rexml` as an optional dependency for `faust2sc` on arch.

**Comment by salkin-mada** [comment]
or wouldn't it be a dependency of `faust2sc` if ruby is version 3.0? 
you cant use `faust2supercollider`/ `faust2sc` without it

**Comment by salkin-mada** [comment]
ah yeah sure. optional would be enough. 
possibly not everyone who need/want to use `fast2supercollider` heh :)
