### ISSUE TITLE
`faust osc.dsp` generates a 64k entry lookup table; why?

### ISSUE THREAD

**Issue by JayFoxRox** [grame-cncm/faust#580]
I'm experimenting with faust, on a *very* limited platform with only about 16k of RAM (with a much larger main RAM, but I'd have to page-in and -out data manually).

However, even a trivial case like `faust /usr/share/faust/examples/generator/osc.dsp` will generate `static float ftbl0mydspSIG0[65536];` which is filled at application startup.

I even see this in the `--one-sample` mode.

- ~~Is this table only for final output, or will there be some large arrays in certain DSP libraries, too?~~ *(Edit: Yes, part of DSP libraries: https://faustdoc.grame.fr/tutorials/esp32/)*
- ~~Where is this coming from?~~ *(Edit: Sine lookup table https://faustdoc.grame.fr/tutorials/esp32/)*
- How can I control buffer / output sizes ahead of time?
- Can these tables be avoided, at expense of realtime calculation?
- Can I fine tune faust so it uses the least amount of memory available?

Just to be clear: I'd be making my own code-generator / backend for my platform anyway. I just want to figure out wether it's even feasible before I sink too much time into it.

**Comment by sletz** [comment]
- table base algorithms can be adapted for embedded devices, see: https://faustdoc.grame.fr/manual/optimizing/#specializing-the-dsp-code
- and a lot of different algorithms can be used to generate oscillator, see https://faustlibraries.grame.fr/libs/oscillators/ and the code https://github.com/grame-cncm/faustlibraries/blob/master/oscillators.lib
