### ISSUE TITLE
faust2supercollider: Feature requests/ideas

### ISSUE THREAD

**Issue by madskjeldgaard** [grame-cncm/faust#582]
Hello!

There's been some talk about the faust2supercollider tool on the scsynth.org forum (https://scsynth.org/t/getting-started-with-faust-for-supercollider/3601/11) floating around ideas for improvements to the script. This issue is an attempt to centralize some of those ideas here. Some of these features have probably become a lot easier to resolve since the json export features was implemented in faust. 

Ideas:
- Allow for custom names for input arguments
- Make input rate handling more flexible (https://scsynth.org/t/getting-started-with-faust-for-supercollider/3601/13)
- Generate a help file to accompany the `.sc`-file (see https://github.com/madskjeldgaard/faust2supercollider2 for a seperate script for that)

Any other ideas floating around?

And to the faust devs: How would you prefer to receive contributions on this topic? I personally won't be messing around with the Ruby code of the original script I think but I've started work on a lua version of it that could work (but would then create a different dependency and be non backwards compatible I guess (which is why I've named it faust2supercollider2 for now).

Best!

**Comment by madskjeldgaard** [comment]
Reworking/rewriting the script would also be a good opportunity to squash the bugs that @lfsaw and others have pointed out:
https://github.com/grame-cncm/faust/issues/520
https://github.com/grame-cncm/faust/issues/521

**Comment by sletz** [comment]
`faust2supercollider` was written by Stefan Kersten years again, and TBH we don't have the expertise or time (Ruby..etc.) to make it evolve anymore. So if a new `faust2supercollider2` version is rewritten, keeping all the current tools options and adding new ones,  this would be great ! How complex to deal with is the LUA dependency?

**Comment by madskjeldgaard** [comment]
> `faust2supercollider` was written by Stefan Kersten years again, and TBH we don't have the expertise or time (Ruby..etc.) to make it evolve anymore. So if a new `faust2supercollider2` version is rewritten, keeping all the current tools options and adding new ones, this would be great ! How complex to deal with is the LUA dependency?

Having thought about this for a while, maybe writing it in python would be the most future proof way? 

I think I will try a rewrite in Python if I get the time

**Comment by madskjeldgaard** [comment]
Okay I am actually pretty far in this and I think I can open a PR fairly soon

**Comment by madskjeldgaard** [comment]
I've now finished the first version of my rewrite. It seems to work quite well but if @LFSaw or anyone else wants to test it out before I make a PR, please do so here. I think it fixes most problems I have had with faust2sc and faust2supercollider but I haven't tested it on other systems than my own (a linux system). But basically, it combines the two scripts into one, is a bit smarter about looking for header files, generates SuperCollider help files as well as Class files in the correct folder structure etc etc. Lots of nice little improvements IMO.

https://github.com/madskjeldgaard/faust2sc.py

PS. Admittedly I am not a Python wizard so if anyone out there is such a thing - a python wizard - then feel free to PR etc.

**Comment by sletz** [comment]
Fixed in 2fcb7aa81cfc9c453b63eb7ff4993e5c9594cc60.
