### ISSUE TITLE
Trouble creating VST3 via faust2juce with JUCE 6.0.8

### ISSUE THREAD

**Issue by Digital-Larry** [grame-cncm/faust#585]
You're in luck, I discovered the fix.

Edit the .jucer file which is created by faust2juce (I exported from the online Faust IDE to juce->plugin).

In the \<JUCERPROJECT\> section:
#1 set buildVST="0", buildVST3="1"
#2 change "buildVST" in \<pluginFormats\> section to "buildVST3".

In the \<JUCEOPTIONS\> section:
#3 add JUCE_VST3_CAN_REPLACE_VST2="0".

**Comment by sletz** [comment]
Can you they with the ones in master-dev branch ? And fix them with a Pull Request ?

**Comment by Digital-Larry** [comment]
@sletz I probably would want to try this by building the code first as I don't understand all of the possibilities of people wanting to build VSTs which replace VST2 format DLLs.  That said, I did some web searching for Faust/VST and didn't find a lot, so if you're willing to abandon VST2 completely in favor of today's JUCE and VST3, I could make the changes.   I don't know how you handle CI/regression testing so I really don't want to break anything without being able to test it.

**Comment by sletz** [comment]
Can you possibly test with a local version of Faust?

**Comment by Digital-Larry** [comment]
I'm sure I can, you'll just need to be a little patient.  But I'll do it.

**Comment by Digital-Larry** [comment]
Was resolved by https://github.com/grame-cncm/faust/pull/587
