### ISSUE TITLE
Missing include for limits, but commit introduces too many changes

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#586]
When rebuilding faust 2.30.5 against llvm 12 I noticed, that `architecture/faust/gui/JSONUI.h` lacks an include for `<limits>`.

This has apparently already been fixed in  https://github.com/grame-cncm/faust/commit/81683c5d7f052941368908a1de30b462204edcc2#diff-25b34ad466346be9b12ce5135b2266d68566cafe4bd1949f4e714d3b41dcc7e5. However, this small change to fix the build of faust is done in a commit that introduces a *large set* of other unrelated changes. It would be great if these changes could be introduced in smaller commits (e.g. one to only fix this particular issue), as those would apply cleanly downstream, without backporting or introducing potentially undesired behavior.

**Comment by sletz** [comment]
Sure... but thinking as each consequence of each commit can start to be quite cumbersome.
