### ISSUE TITLE
feature request: ability to compile from stdin

### ISSUE THREAD

**Issue by mbylstra** [grame-cncm/faust#6]
For example, I'd like to be able to do this:

```
faust < cat ./example.dsp
```

A bit of background:

- I want to set up a REST server for generating SVG diagrams for Faust code
- I want to use Docker for no-fuss deployments of the faust executable

At present the only way to read a file is to specify one or more files with file paths (in the current filesystem). Docker makes this awkward as by default it only has access to the container's filesystem (not the host's, where the file you want to compile will reside).

It can be done, but it is awkward. Eg:

`docker run -v /home/:/home/ mbylstra/faust /home/michael/code/current/faust-docker/test.dsp`

What this does is mount the host's `/home/` directory as `/home` in the container. You then need to use full paths for the file you want to compile (`~` or `.` won't work).

With stdin, you'd be able to do the following, which is nicer:

`docker run mbylstra/faust < cat ./test.dsp`

Has this been considered?

**Comment by gierschv** [comment]
Hey @mbylstra,

You can do this:

```
docker run -i faust /dev/stdin < [path-on-your-host].dsp
```

Cheers,
Vincent

**Comment by mbylstra** [comment]
Great idea! Thanks.
