### ISSUE TITLE
faust2portaudiorust gives compile errors

### ISSUE THREAD

**Issue by pschatzmann** [grame-cncm/faust#624]
error: use of deprecated `try` macro
   --> src/main.rs:275:14
    |
275 |     let pa = try!(pa::PortAudio::new());
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: in the 2018 edition `try` is a reserved keyword, and the `try!()` macro is deprecated
help: you can use the `?` operator instead

...
error: aborting due to 9 previous errors; 2 warnings emitted

**Comment by sletz** [comment]
What where of Faust are you using ? The current master-dev branch code https://github.com/grame-cncm/faust/blob/master-dev/architecture/minimal-portaudio.rs#L108 send correct (and so the recently [published 2.33.1](https://github.com/grame-cncm/faust/releases/tag/2.33.1)

**Comment by pschatzmann** [comment]
Thanks a lot!

I have installed it in Raspian with apt and I am getting: FAUST Version 2.14.4

So I guess I have to build it from source...

**Comment by sletz** [comment]
Yes 2.14.4 2 years an a half old now!.
