### ISSUE TITLE
Access Faust code for the example models

### ISSUE THREAD

**Issue by arturmic** [grame-cncm/faust#625]
Hi,

this is not really an issue with the Library itself. I wanted to know if it's possible to access the code of the
example model processes somehow? I can access the diagrams of course but for some parts I have a problem to understand how they are implemented just by the diagram. Is there a way to generate the corresponding code from the diagram?
(I havent found anything)

**Comment by sletz** [comment]
Which examples are you speaking about?

**Comment by arturmic** [comment]
Hi, 
thanks for getting back. Sorry I didn't specify. I was talking about the physical modelling library.

**Comment by sletz** [comment]
Here: https://github.com/grame-cncm/faustlibraries/blob/master/physmodels.lib

**Comment by arturmic** [comment]
ah perfect thanks!
