### ISSUE TITLE
libfaust: polyphonic vars don't work when voices are grouped but otherwise do 

### ISSUE THREAD

**Issue by DBraun** [grame-cncm/faust#629]
I'm using APIUI and this DSP code (with `ALGORITHM = 0;` uncommented): https://github.com/DBraun/DawDreamer/blob/cd1887b4789f8d45c7d875d7dc159b96a609af00/tests/faust_dsp/dx7.dsp#L56

First I'll describe what happens when voices are ungrouped, which works correctly.
```c++
m_dsp_poly = m_poly_factory->createPolyDSPInstance(8, true, m_groupVoices);
m_ui = new APIUI();
m_dsp_poly ->buildUserInterface(m_ui);
```
The APIUI has an [fPaths](https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/gui/APIUI.h#L50) variable, which will have 
`/Sequencer/DSP1/Polyphonic/Voices/Panic`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/freq`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/gain`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/gate`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/global/feedback`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/op0/egL1`
`/Sequencer/DSP1/Polyphonic/Voices/dx7/op0/egL2`
...
`/Sequencer/DSP1/Polyphonic/V1/dx7/freq`
`/Sequencer/DSP1/Polyphonic/V1/dx7/gain`
`/Sequencer/DSP1/Polyphonic/V1/dx7/gate`
`/Sequencer/DSP1/Polyphonic/V1/dx7/global/feedback`
`/Sequencer/DSP1/Polyphonic/V1/dx7/op0/egL1`
...
`/Sequencer/DSP1/Polyphonic/V8/dx7/freq`
`/Sequencer/DSP1/Polyphonic/V8/dx7/gain`
`/Sequencer/DSP1/Polyphonic/V8/dx7/gate`
`/Sequencer/DSP1/Polyphonic/V8/dx7/global/feedback`
`/Sequencer/DSP1/Polyphonic/V8/dx7/op0/egL1`
...

I chose 8 voices of polyphony, so the prefixes V1, V2.. V8 make sense. If the voices are ungrouped, why does the first section `/Voices/*` exist? It sounds fine though. I get different sounds by doing code like
`m_ui->setParamValue("/Sequencer/DSP1/Polyphonic/V1/dx7/op0/egL1", 0.1234)`

The issue is when voices are grouped. In that case, APIUI's fPaths only has the `/Voices/*` section, not `V1/*`, `/V2/*` etc.

If I do many random combinations of changing the available parameters, I don't hear different sounds.
`m_ui->setParamValue("/Sequencer/DSP1/Polyphonic/Voices/dx7/op0/egL1", 0.1234)`

**Comment by sletz** [comment]
When voices are grouped, all of them will be changed with a same controller.

**Comment by DBraun** [comment]
Right, but I don't think this same controller that is supposed to control multiple voices is having an effect.

I'm looking at
https://github.com/grame-cncm/faust/blob/c10910171a197066f15679631d71ed346ccb1751/architecture/faust/dsp/poly-dsp.h#L356-L371

Since group control is on, maybe the **fVoiceTable** voices aren't sharing the parameters from the **fVoiceGroup** (the same controller)?

**Comment by DBraun** [comment]
D'oh, I needed to call `GUI::updateAllGuis();` after changing the parameters. It's mentioned all over in poly-dsp.h.

**Comment by sletz** [comment]
Yes, this is explained in https://faustdoc.grame.fr/manual/architectures/#multi-controller-and-synchronization

**Comment by DBraun** [comment]
Thanks. Is there a threading risk if I have a DLL that declares https://github.com/DBraun/DawDreamer/blob/8ef8b8c92b58987e4217cdf9840a0aa7231d1c00/Source/FaustProcessor.cpp#L8 ? Multiple threads load this DLL, use classes such as FaustProcesssor and call gui::updateAllGuis();

**Comment by sletz** [comment]
Yes probably, calling `gui::updateAllGuis();` from multiply threads will cause problems. You'll probably have to use a mutex.
