### ISSUE TITLE
Add the copysign function

### ISSUE THREAD

**Issue by jpcima** [grame-cncm/faust#633]
Hi. The `copysign` function is missing, and for instance the file `tubes.lib` implements its own,
by the following definition: `ccopysign(f, x) = abs(f) * sign(x);`

This reimplementation would produce suboptimal code, compared to the bitwise version of C.
https://godbolt.org/z/YfK74GMee

One can substitute it
`copysign = ffunction(float copysignf|copysign|copysignl(float,float),<math.h>,"");`

But this version cannot run in the JIT; so this request is to have it recognized as mathlib function.

**Comment by sletz** [comment]
I think fast `copysign` would be OK for C, C++, LLVM, Interp backend, but would have to be "manually" implemented for other ones. @orlarey what do you think?

**Comment by sletz** [comment]
In progress:
-  on the library side, see https://github.com/grame-cncm/faustlibraries/commit/62dd0e8a0ea9e36fe1cb5eac72a401390c5e6856
- currently adding/emulating it in the different backends

**Comment by sletz** [comment]
Added in https://github.com/grame-cncm/faust/commit/0d435331f6303aad993fe1e85da6afb1d25427f7
