### ISSUE TITLE
Web IDE - Browser support

### ISSUE THREAD

**Issue by suyashjoshi** [grame-cncm/faust#640]
Please support Safari browser for Web IDE. Which browser does it currently run on, Chrome?

**Comment by sletz** [comment]
Is runs on Chrome with MIDI support and FireFox. Both of then correctly support AudioWorklet.
Safari still has a [bug in AudioWorklet support](https://bugs.webkit.org/show_bug.cgi?id=220038), but can run in the older ScriptProcessor mode.
