### ISSUE TITLE
[coreaudio] coreaudio doesn't work as expected when the chosen input device has outputs

### ISSUE THREAD

**Issue by nuchi** [grame-cncm/faust#645]
I'm trying to send input from [BlackHole](https://github.com/ExistentialAudio/BlackHole/) (16 inputs and 16 outputs) to my external headphones (2 outputs). The problem is that the aggregate device created from the input and output device has a combined 16 inputs but _18_ outputs, not the 2 I'd expect. The headphones' outputs are the _last_ two channels, but the coreaudio driver is trying to send the output to the _first_ two channels.

To reproduce:
`test.dsp`:
```
process = _,_;
```
and then:
```
% faust2api -coreaudio test.dsp -nozip
% clang++ DspFaust.cpp -DBUILD -std=c++11 -o DspFaust -framework CoreAudio -framework CoreServices -framework AudioUnit
% ./DspFaust
Type 'q' to quit
```
and playing sound to the BlackHole output produces nothing audible. Trying the same passthrough in AU Lab (going from BlackHole input to headphone output) works correctly.

Editing the following line in the generated `DspFaust.cpp` causes audio to be passed through as expected, seeming to confirm that the headphones' two outputs are being stuck after the input device's outputs:
```diff
  if (outChan < fPhysicalOutputs) {
      SInt32 chanArr[fPhysicalOutputs];
      for (int i = 0; i < fPhysicalOutputs; i++) {
          chanArr[i] = -1;
      }
      for (int i = 0; i < outChan; i++) {
-         chanArr[i] = i;
+         chanArr[i + 16] = i;
      }
      err = AudioUnitSetProperty(fAUHAL, kAudioOutputUnitProperty_ChannelMap, kAudioUnitScope_Output, 0, chanArr, sizeof(SInt32) * fPhysicalOutputs);
      if (err != noErr) {
          printf("Error calling AudioUnitSetProperty - kAudioOutputUnitProperty_ChannelMap 0\n");
          printError(err);
      }
  }
```
The original is [here](https://github.com/grame-cncm/faust/blob/71b7a3fca50ca2a949bda015d2b3b460f7722a57/architecture/faust/audio/coreaudio-dsp.h#L1258) and it looks like there was [a commit a little while back](https://github.com/grame-cncm/faust/commit/dbe9fffb566cc85bdf469018849dab1d6ba617d3#diff-df360344a8dcdfad6c8bd9ffc2db236a8c9c2caf11b152e344b87208c81b0fa7L1286) that changed something related, but I'm not sure.

**Comment by sletz** [comment]
The same issue (AFAICS) was reported then https://github.com/grame-cncm/faust/issues/268 and a fix was tried in https://github.com/grame-cncm/faust/commit/80bfc926e77cbdb5b08b8fed44902145caec4714
But later on I saw it was even worse, so reverted that in some way. I guess creating the appropriate Aggregate Device for your setup is a possible workaround. Or you you have time and competence to understand what should be done in all possible setup... then PR is welcome!

**Comment by nuchi** [comment]
Thanks, I missed that issue when searching for duplicates. Do you have any context written down somewhere for why you had to revert? I may take a look to see if I can fix it, and it'd be helpful to know why the commit you mention wasn't quite right. (I can't see anything obviously going obviously wrong there, but I haven't looked in detail)

**Comment by sletz** [comment]
https://github.com/grame-cncm/faust/commit/80bfc926e77cbdb5b08b8fed44902145caec4714 was the "fix"

and this one was the "revert"

https://github.com/grame-cncm/faust/commit/dbe9fffb566cc85bdf469018849dab1d6ba617d3#diff-df360344a8dcdfad6c8bd9ffc2db236a8c9c2caf11b152e344b87208c81b0fa7L1286

**Comment by nuchi** [comment]
Thank you —
> later on I saw it was even worse

I was wondering what was worse about it? If I do take a look it'd be helpful to know what traps to avoid. I didn't see any comments in the revert commit about what the problem was.

**Comment by sletz** [comment]
Sorry no comment in the commits, but the vague memory I have was that simpler cases (so without complex multi-device aggregation) where not always working anymore.

**Comment by nuchi** [comment]
Ok, that helps. Thank you.
