### ISSUE TITLE
Create new DSP factory when imports changed

### ISSUE THREAD

**Issue by RaoulHC** [grame-cncm/faust#649]
As it stands DSP factories are cached based on their name, file content and compilation options, but not imports or libraries that might have changed. In order to reload this with changes you would have to delete the factory and create it again.

It would be good if the SHA1 incorporated the file content of imports, or there was an option / alternative function for this behaviour.

**Comment by sletz** [comment]
You can possibly use the [expandDSPFromString](https://github.com/grame-cncm/faust/blob/master-dev/compiler/generator/libfaust.h#L71) function to generate a version of the DSP string where all libraries have been included, then give this version to `createDSPFactoryFromString`, to have the expanded version be use din the SHA1 key compilation. 
This is not done by default since `expandDSPFromString` may be time-consuming. So you'll have to test the feasibility of this method in your use-case.

**Comment by RaoulHC** [comment]
Will it not be reading all the imports any time it does actually reload? Seems like if you're loading it all anyway it would be good to identify the DSP more precisely.

Ideally it would be good to be able to just reload specific files and generate a new DSP by just swapping out that part, but I'm not familiar enough with how faust works (at least not yet), to know how feasible that is.

**Comment by sletz** [comment]
Faust actually parse all libraries + DSP and the entire compilation has to be done again each time something (any definition in the libraries or the DSP code) changes. The  expanded DSP version will only contain what is actually needed for the actual compilation.

**Comment by RaoulHC** [comment]
Missed this reply, I'm having a go writing my own TUI version of FaustLive, mainly just to learn a bit more about how it works and practice my rust (lives [here](https://gitlab.com/raoulhc/fl-tui) if you're interested).

I've had some luck with the `expandDSPFromString` approach, but you lose information about the locations of the imports which I would like, in order to watch for changes in these files.

FaustLive also has this issue, where if you change an import it doesn't reload the change (it does reload, but not the changed import, at least on v2.5.5). I think if working with a multi file project you ideally want any change to an imported file to cause it to be reloaded, but the current API doesn't seem to allow this to be easily done.

**Comment by sletz** [comment]
Could the [getLibraryList](https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/dsp/llvm-dsp.h#L119) method help?

**Comment by RaoulHC** [comment]
I may be missing something, but it seems like when you change the creation into two steps with `expandDSPFromString` and `createDSPFactoryFromString` you lose this information and `getLibraryList` returns nothing.

I would guess normally `createDSPFactoryFromString` populates the the library lists as it deals with imports, but if you're starting with a string that has this all expanded out you've lost that information.

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/fa15b59b0cc47e33f2461a051986a683a80f7128. Does it help?

**Comment by RaoulHC** [comment]
Yep, that seemed to have done the trick, thank you!

Fyi one of the recent changes (looks like fba9b3ce6bface09fee20480cd8b9c0d1a9e510e's changes to build/httpd/CMakeLists.txt), seems to have broken the HTTPDFaust build on linux, with ld giving the error `cannot find -lws2_32`, a library which seems to be a windows only. Turned off the build of that to test this change but probably should be fixed (and maybe not skipped in CI as it appears to be [here](https://github.com/grame-cncm/faust/runs/3794149786))

**Comment by sletz** [comment]
> Yep, that seemed to have done the trick, thank you!
> 
> Fyi one of the recent changes (looks like [fba9b3c](https://github.com/grame-cncm/faust/commit/fba9b3ce6bface09fee20480cd8b9c0d1a9e510e)'s changes to build/httpd/CMakeLists.txt), seems to have broken the HTTPDFaust build on linux, with ld giving the error `cannot find -lws2_32`, a library which seems to be a windows only. Turned off the build of that to test this change but probably should be fixed (and maybe not skipped in CI as it appears to be [here](https://github.com/grame-cncm/faust/runs/3794149786))

Can you prepare a PR for that? Thank.

**Comment by RaoulHC** [comment]
Raised a PR in #658 (think it should build httpd in the ubuntu CI, but needs to be run to check).

I'll close this issue given the original problem was fixed.
