### ISSUE TITLE
Why are some control names showing up as 0x00 ?

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#651]
e.g.

```
import("stdfaust.lib");
process = *(vslider("[1]", 0, 0, 1, 0.5));
```

gives me the string "0x00" in the label in the UI creation. I guess I should be doing something specific in that case but I do not really know what, and the `MetaDataUI` does not seem to add more information

**Comment by sletz** [comment]
This is because you don't have any label in the slider definition. In can be fixed with :

```
import("stdfaust.lib");
process = *(vslider("Foo [1]", 0, 0, 1, 0.5));
```

**Comment by jcelerier** [comment]
thanks, that answers the question ! (in my case I don't control the faust programs, but I had users wonder if that 0x00 was a bug, I'll replace it by some generic "Control" text on my side)
