### ISSUE TITLE
Compilation errors on Windows 10, Msys2 MinGW64

### ISSUE THREAD

**Issue by jpnielsen** [grame-cncm/faust#652]
I'm following the written procedures for compiling Rack and it's plugins here:

https://vcvrack.com/manual/Building

As written in the closed issue referenced here, I get errors building on Windows 10, msys2 MinGW64

https://github.com/VCVRack/VCV-Prototype/issues/55

It's not a high priority issue. I build and run Faust generated plugins on ubuntu.

**Comment by HEXmodular** [comment]
I had the same problem today (Windows 10, Msys2 MinGW64)
I fixed this addind 

```
#ifdef _WIN32
typedef unsigned int uint;
#endif
```

This was the solution from the link. I just added ; to the end of the line :))

**Comment by jpnielsen** [comment]
Thank you all,

I can confirm that it works.

**Comment by jpnielsen** [comment]
I will follow the project, perhaps it will be usefull some day.

![image](https://user-images.githubusercontent.com/27916597/133912794-9da407de-152e-40c8-b55e-f4761c74caad.png)

Gives this

![image](https://user-images.githubusercontent.com/27916597/133912777-eb6f778f-3350-44f8-8fb6-38d7ec0a4fb5.png)

**Comment by sletz** [comment]
Yes, the automatically generate GUI can be ugly, this is a known problem!  Contribution welcome!
