### ISSUE TITLE
Bela build fails when using MIDI

### ISSUE THREAD

**Issue by robinrosenberger** [grame-cncm/faust#660]
Building on Bela fails if render.cpp is created with `faust2bela -midi`
Output is:
[bela-error.txt](https://github.com/grame-cncm/faust/files/7365674/bela-error.txt)
Faust version is 2.33.1-1 on Arch
Bela is the latest github-commit (4d704a0) on image 0.3.8b

**Comment by sletz** [comment]
This  <dummy.h> issue should be fixed in https://github.com/grame-cncm/faust/commit/ee2cefdb0594eb355079de8c8c9cf8b9d8635470. Can you test and report? Thanks.

**Comment by robinrosenberger** [comment]
The dummy error is gone with the latest commit. Thanks a lot!
