### ISSUE TITLE
logical & and | in generated c code

### ISSUE THREAD

**Issue by jmckernon** [grame-cncm/faust#661]
I find that faust generates some surprising c when using the & and | operators.

```
process = &;
```
leads to the following compute function:
```
virtual void compute(int count, FAUSTFLOAT** inputs, FAUSTFLOAT** outputs) {
	// ...
	for (int i0 = 0; (i0 < count); i0 = (i0 + 1)) {
		output0[i0] = FAUSTFLOAT((int(float(input0[i0])) & int(float(input1[i0]))));
	}
}
```
This uses c's bitwise and operator (&) rather than its logical and (&&). The same is the case for |. Is this a bug? It does seem to contradict the docs, which state "Logical AND can be expressed in Faust with the & primitive" (and similarly for OR).

It seems that either & should be changed to generate && in c or the docs should be brought in line with the actual behaviour. (I would prefer the first.)

I haven't tested the behaviour with other backends.

I thought there might be && and || in faust, but it seems not.

**Comment by sletz** [comment]
Documentation fixed.
