### ISSUE TITLE
example reverb/greyhole.dsp broken

### ISSUE THREAD

**Issue by hiqualityh2o** [grame-cncm/faust#668]
I am working in Faust IDE. Examples/reverb/greyhole.dsp is broken: trying to compile throws
`FaustDSP : 8 : ERROR : undefined symbol : greyhole_demo
`

**Comment by sletz** [comment]
Are you suer? Tested and working here. How are you testing ?

**Comment by hiqualityh2o** [comment]
Strange.
I open faustide.grame.fr with Chrome, open the examples dropdown -> reverb -> greyhole.dsp and get the error message
<img width="1672" alt="Bildschirmfoto 2021-10-30 um 12 17 34" src="https://user-images.githubusercontent.com/16322802/139529030-58c44b85-bafe-4dd5-b730-bb9cb65cd369.png">
e

**Comment by sletz** [comment]
Try to clear the cache.

**Comment by hiqualityh2o** [comment]
I tried. Didn't help.

**Comment by sletz** [comment]
Chrome ? FF ? On which OS ?

**Comment by hiqualityh2o** [comment]
Chrome, MacOS 11.2.3

**Comment by sletz** [comment]
Where does this gives:

```
import("stdfaust.lib");
process = vl.version;	
```

**Comment by hiqualityh2o** [comment]
Sorry, i don't understand what you propose to try.
I tried compiling your code and it does not throw any errors.

**Comment by sletz** [comment]
What version number dot you see ? It should be 2.4.4. 
<img width="558" alt="Capture d’écran 2021-10-30 à 15 20 08" src="https://user-images.githubusercontent.com/1430487/139534348-29bbe5cf-f657-4ea8-80d2-1e31e5c1ae33.png">

**Comment by hiqualityh2o** [comment]
Gotcha. Yes, it's 2.4.4

**Comment by sletz** [comment]
Have you tried with Firefox? Or Safari?

**Comment by hiqualityh2o** [comment]
I just tried Safari and while it doesn't throw any errors, it doesn't compile. But so does every other example in Safari.

I do not have Firefox installed so i cannot try it, sorry.

**Comment by sletz** [comment]
Concerning Safari, see: https://github.com/grame-cncm/faustide#known-problems-and-solutions.
And testing with Firefox would help...
