### ISSUE TITLE
key function for alternative tuning doesn't work

### ISSUE THREAD

**Issue by etiennedemoulin** [grame-cncm/faust#675]
Hi,
I'm trying to run this example to catch RAW midi note in faust for alternative tuning : 

import("stdfaust.lib");
freq = hslider("key",60,36,96,1) : midikey2hz 
with {
    // quarter tone tuning
    midikey2hz(mk) = 440.0*pow(2.0, (mk-69.0)/48.0); 
}; 
gain = hslider("gain",0.5,0,1,0.01);
gate = button("gate");
process = os.sawtooth(freq)*gain*gate;

It doesn't seems to work because I can always hear the same note.
I'm on MacOS 11.6 with the last version of Google Chrome.

**Comment by sletz** [comment]
A bug in the Faust Web IDE (reporter here https://github.com/grame-cncm/faustide/issues/48). It works on native code.
