### ISSUE TITLE
Juce VSTs state isn't kept when closing and reopening GUI

### ISSUE THREAD

**Issue by xaviergodart** [grame-cncm/faust#68]
Hi there,

I'm using faust2juce a lot these days, and so far it works pretty well.
I've noticed an annoying bug on compiled VSTs: the state of the plugin controls are lost each time I reopen the plugin GUI in a DAW. All controls are setted back to the default values.

I can reproduce this bug on Linux with Carla host or on Windows 7 with the last version of Reaper.
I'm using the master-dev branch.

I'm not really sure what's happening, but it looks like the uiSlider components are always recreated with the default value, without taking care of the current value.

Thanks for your help.

**Comment by sletz** [comment]
State management is done using the **JuceStateUI** auxiliary class. This class is used in the juce-plugin.cpp architecture file. A **fStateUI** object of type **JuceStateUI** is created, then "connected" to be actual controllers (using the **buildUserInterface** method). The state is then saved in  **FaustPlugInAudioProcessor::getStateInformation**  and restored in  **FaustPlugInAudioProcessor::setStateInformation**.

Can you possibly trace what happens? And see if **getStateInformation/setStateInformation** are correctly called ?

**Comment by xaviergodart** [comment]
Thanks for your help.
I used the Juce **DBG** function to check if **getStateInformation**/**setStateInformation** are called, and it's not the case when closing the plugin GUI. I guess that's why the state is lost when reopening the GUI.

On the other hand, if I use the preset system in Carla, save a preset, then recall it, these methods are called. The preset system works well.

Should the host call these method when closing the GUI as well? Looks like every vst host have a different way of dealing with this...
I just found this old topic on the juce forum : https://forum.juce.com/t/problems-recalling-plugin-state-versus-current-preset/5895

**Comment by sletz** [comment]
Hie do you use Juce DBG function ? Where do you see the resulting trace ?

**Comment by xaviergodart** [comment]
I just added the **DBG** function to the methods like this:
```
//==============================================================================
void FaustPlugInAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
    DBG("GETSTATE");
    fStateUI.getStateInformation(destData);
}

void FaustPlugInAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.

    DBG("SETSTATE");
    fStateUI.setStateInformation(data, sizeInBytes);
}
```

And then in Carla, you have a **Logs** tab where you can trace the plugin output:
![carla_logs](https://user-images.githubusercontent.com/968860/28327846-eafe925e-6be4-11e7-94f6-313591450a81.png)

Here I just recalled a saved preset in Carla, and you can see a **SETSTATE** call in the log.

**Comment by sletz** [comment]
Can you test possibly fix here ? https://github.com/grame-cncm/faust/commit/9ccfc1c59b4c74260cdf0a9d8cf0ad7fd76eb7a0

**Comment by xaviergodart** [comment]
Just tried the fix, it does not work. It seems normal as the **setStateInformation** is not called by the host when I close the gui.
I made a quick change that fix a part of the problem. I added a **setUseDefault** to the **JuceStateUI** class:
```
void setUseDefault(bool value) { fUseDefault = value; }
```
And then, at the end of the **FaustPlugInAudioProcessor** constructor, just after the **buildUserInterface** calls, I added:
```
fStateUI.setUseDefault(false);
```
It fixes the problem when closing and reopening the gui, but the controls are still returning to default value when I bypass and unbypass the plugin in the DAW.
I guess it should never use the default values after the dsp class instantiation.

In the meantime, I fixed the problem for my use case (not sure what it would break for other use cases) by hacking only the dsp class. In the **buildUserInterface** method, I now add sliders like this:
```
ui_interface->addHorizontalSlider("Gain", &fslider0, fslider0, 0.0f, 1.0f, 0.01f);
```
In the **instanceResetUserInterface**, I commented the slider default value affectation:
```
// fslider0 = 0.5f;
```
and finally, I changed the slider declaration to add the default value there:
```
FAUSTFLOAT 	fslider0 = 0.5f;
```

It now use the default values only when the dsp class is instantiated for the first time. And for next **buildUserInterface** calls, it uses the already setted values. Maybe this hack will help understanding the problem...

**Comment by sletz** [comment]
It would really help to understand at why time the **buildUserInterface ** method is called in each use case you describe. Could you possibly add DBG trace and report them ? Thanks

**Comment by xaviergodart** [comment]
For the case when I reopen the gui after closing it, the **createEditor()** method that instantiate the **FaustPlugInAudioProcessorEditor** class is called (weirdly) 2 times. The **buildUserInterface** is called once in this class constructor. 

For the case when I bypass and unbypass the plugin, the **buildUserInterface** is never called. The **FaustPlugInAudioProcessor::prepareToPlay** method is called instead, that call the **init** method of the dsp class, which call **instanceResetUserInterface** that restore the default values.

**Comment by sletz** [comment]
OK, so we have two different problems here:
- the fact that **buildUserInterface** possibly reset to default values (the JuceUI Class for instance)
- the fact that **init** also is possible called several time during the DSP lifetime

Since we have to **init** the DSP as some time, the difficult thing is to understand **when** we have to do it, and when we have to use a lighter version of initialization code at several time points (like this  bypass and unbypass  sequence...) of the DSP plugin lifetime.

**Comment by sletz** [comment]
Second try : can you test the fix here ?
https://github.com/grame-cncm/faust/commit/4bb208b00971af1c1e103c696dd337a9a172321b

**Comment by xaviergodart** [comment]
Well good job, it works for both use cases now.
Thank you very much for your work. I'll continue reporting this kind of bugs if I find others.

**Comment by fewtubefx** [comment]
I have same problem in Juce 6. I'm using faust2juce and sliders resets after closing- opening GUI.

**Comment by sletz** [comment]
When exporting as VST ?

**Comment by fewtubefx** [comment]
Yes, when exporting to VST.

**Comment by sletz** [comment]
In which host ? 
The code what corrected (see xaviergodart commented on 19 Jul 2017 least message). Can you possibly debug following what was described in this thread ?

**Comment by fewtubefx** [comment]
Cakewalk, Reaper and VSTHost - not saved state.

I've tried add strings, but it seems wrong place, VS error - error C2065: 'fStateUI': undeclared identifier
1>Done building project "slamp_beta_SharedCode.vcxproj" -- FAILED.

**Comment by fewtubefx** [comment]
After test I've found, that if default position of slider = 0, than it works ok, not resetting every time,
but if default slider position not =0, than every opening GUI it reset it to default position.

**Comment by jonayoung2003** [comment]
I'm also getting this problem, but I need default parameter values for the plugin I'm developing (when first opened only) and I need the plugin to save its state and not reset to defaults every time the plugin GUI is opened. Before trying to find a workaround myself, has anyone found a fix for this? @fewtubefx did you find a fix for this?

**Comment by fewtubefx** [comment]
Yes, I've set all default parameters to zero, than it works as needed. I'm not sure it will works in your case. Anyway you can try it.21.10.2023, 22:47, "jonayoung2003" ***@***.***>:
I'm also getting this problem, but I need default parameter values for the plugin I'm developing (when first opened only) and I need the plugin to save its state and not reset to defaults every time the plugin GUI is opened. Before trying to find a workaround myself, has anyone found a fix for this? @fewtubefx did you find a fix for this?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Sincerely, FewtubeFXhttps://fewtubefx.blogspot.com/
