### ISSUE TITLE
CSharp backend generating invalid code for "IsInfinity"

### ISSUE THREAD

**Issue by mikeoliphant** [grame-cncm/faust#686]
At some point the "IsInfinity" operator was added, and the C# code generator produces invalid code.

it generates:

`public static bool IsInfinity(double d) { return Double.IsNegativeInfinity(double d) || Double.IsPositiveInfinity(double d); }`

but it should be:

`public static bool IsInfinity(double d) { return Double.IsNegativeInfinity(d) || Double.IsPositiveInfinity(d); }`

Also, this is inserted into the main body of the output file instead of inside the class, which is invalid.

Instead of being generated, the function should probably be put in the base class, **CSharpFaustBase.cs**, like _FMod_ and _FModF_ are.

**Comment by sletz** [comment]
Can you fix it and prepare a PR ? Thanks.
