### ISSUE TITLE
make interp fails

### ISSUE THREAD

**Issue by camuffo** [grame-cncm/faust#693]
I'm working on a port for Alpine Linux.

`make interp -C tests/compile-tests/` fails because `music.lib` and `math.lib` cannot be found inside `libraries/old/`.
Is this expected and am I supposed to move those libs outside `old` before running tests?

The release guidelines say that at least `make interp` should pass. Which parts of the test suite should pass if faust was built with `make world`?

**Comment by sletz** [comment]
Hum, `music.lib `and `math.lib` are here? https://github.com/grame-cncm/faustlibraries/tree/cba66443c603ee0b52c0c6fefdac6f0f29db0135/old

Have you installed faust before running the test?

**Comment by camuffo** [comment]
I did't install it. I'm probably missing something.
Which tests should I run after compiling but before installing (or making the package) to check artifacts built with `make world`?

**Comment by sletz** [comment]
Fixed in  https://github.com/grame-cncm/faust/commit/974d4da02b525261d934a9eb70e41a1c4ee309c3 can you test again?

**Comment by camuffo** [comment]
Thanks. Now `make interp` passes. Do you expect a release soon? If not I'll include the patch during packaging.

**Comment by sletz** [comment]
No release soon, so yes go for the patch.
