### ISSUE TITLE
Proposal - expand console.h to accept a list of control-rate values instead of a single value

### ISSUE THREAD

**Issue by mikesol** [grame-cncm/faust#698]
In [`console.h`](https://github.com/grame-cncm/faust/blob/ffbecadcdcd5e93b7b232ba2c17f97554caf6a95/architecture/faust/gui/console.h#L270), the values passed to the command line are single floats. I'm wondering if it'd be possible, in addition to this, to accept a file with newline-delimited floats. For example:

`./my-dsp-prog --gain /tmp/gain input.wav`

It'd be a bit tricky because there'd have to be a way to fix the control rate, either through a command-line flag (for example, `--krate` or through a setting in the `.dsp` document itself.

Is there interest in this? The PR would be a bit involved as it'd require a new parser step and a new krate interpolation step in the `console` backend, so it'd be good to see if others felt it were useful before I took a crack at it. Thanks!

**Comment by sletz** [comment]
We already have a mechanism that was developed for the `faust2sndfile` tool:

`[-ct <filename>] to use the <filename> control messages file`

The control messages file format:
- uses the OSC Timestamps model to define dates  (see https://docs.juce.com/master/classOSCTimeTag.html for instance) 
- the OSC path for a given parameter 
- the actual value 

This is implemented in [ControlSequenceUI.h](https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/gui/ControlSequenceUI.h) and used in [sndfile.cpp](https://github.com/grame-cncm/faust/blob/master-dev/architecture/sndfile.cpp) architecture.

This ways of down could possibly be reused, and adapted/improved if needed. What do you think ?

**Comment by mikesol** [comment]
Ah, perfect! I can use the sndfile backend for now, thanks!
