### ISSUE TITLE
webaudio wasm processor ReferenceError can't find variable Faustxxxx

### ISSUE THREAD

**Issue by krrnk** [grame-cncm/faust#706]
Hello, 
I am trying to use faust2wasm (processor) to run a faust.dsp on the browser. faust2wasm -worklet works fine on Chrome and Firefox but I also need support for Safari (in macOS & iOS) that is why I am trying to use faust2wasm with processor mode.

I compiled the [noise.dsp](https://github.com/grame-cncm/faust/blob/master-dev/architecture/webaudio/noise.dsp) example using the Faust IDE to faust2wasm (no -worklet) and tried to run the [noise-wasm.html](https://github.com/grame-cncm/faust/blob/master-dev/architecture/webaudio/noise-wasm.html) example. 

When I run the project on Chrome or Safari I get: 
Safari: ReferenceError: Can't find variable: Faustnoise startnoise (127.0.0.1:36)
Chrome: Uncaught ReferenceError: Faustnoise is not defined at startnoise (noise-wasm.html:36:18)

EDIT: the branch mentioned in [#697](https://github.com/grame-cncm/faust/pull/697) works both on Safari & Chrome.

Am I missing something?

Thanks in advance

**Comment by ceelian** [comment]
Hi,

I also can't get it to run on safari mac and ios. I always get the error `An error from synth-processor was detected.` where `synth` is the name of my dsp file. @krrnk could you find a workaround?

**Comment by krrnk** [comment]
> 

Hi @ceelian, 
My solution for Safari & iOS was to:
1.  Uninstall my current version of Faust
2.  Compile Faust from this branch: https://github.com/nuchi/faust/tree/safari-wasm 
3.  Compile your synth with the command `faust2wasm -worklet`
4.  Optional: Once your synth is compiled you can reinstall Faust from their master branch.

**Comment by ceelian** [comment]
@krrnk thank you very much! This workaround works. I forked the newest faust version and applied the patch from nuchi on master and master-dev (https://github.com/ceelian/faust) . Can confirm the workaround still works fine on Faust 2.40.0

**Comment by sletz** [comment]
Use the [austwasm[https://github.com/grame-cncm/faustwasm) project.
