### ISSUE TITLE
Docs to add new driver support

### ISSUE THREAD

**Issue by marchingband** [grame-cncm/faust#710]
I would like to add support to the ESP32 architecture for an i2s DAC, the PCM5100.
Is there any documentation or tutorial that could help me on this?
Would it be useful to make a PR if I succeed?
Thank you! <3

**Comment by sletz** [comment]
There is no specific documentation AFAICS, but you can probably look at how is is currently done: https://github.com/grame-cncm/faust/tree/master-dev/architecture/esp32/drivers. And possibly get help on the Faust Slack channel, see: https://faust.grame.fr/community/help/

**Comment by thopman** [comment]
The PCM5100 does not need a driver per se. No need to set it up via spi or i2c like the other codecs. So just feeding it i2S should suffice. There are some settings that can be changed which you might want. You do that by setting certain pins high or low.

**Comment by marchingband** [comment]
Yes i2s is very simple to configure, and where it's a popular option on ESP32, it would be helpful to have an example or a compiler option available to use an i2s DAC. All the articles online make it sound like only 2 or 3 codecs are "supported".

What's the best way to take the output of a Faust library compiled to C++, and pipe it to my i2s buffer?

**Comment by sletz** [comment]
@marchingband have you read first https://faustdoc.grame.fr/manual/architectures/ ?

**Comment by marchingband** [comment]
Amazing :) thank you so much @sletz !
