### ISSUE TITLE
MIDI “key” parameter not working

### ISSUE THREAD

**Issue by modularev** [grame-cncm/faust#715]
Using the "key" Parameter seems to be broken.

Can be reproduced by trying following example from the faustdoc:
https://faustide.grame.fr/?code=https://faustdoc.grame.fr/manual/midi/exfaust10/exfaust10.dsp

**Comment by sletz** [comment]
Possibly broken in the IDE only. Have you tried elsewhere?

**Comment by modularev** [comment]
yes PR #716 should fix it.
