### ISSUE TITLE
generator/description.cpp:132: possible use of wrong operator ?

### ISSUE THREAD

**Issue by dcb314** [grame-cncm/faust#723]
For version 0.9.46 with new C compiler clang-14, I get

generator/description.cpp:132:13: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]

Source code is

    if (src[i] == '"' & (i==0 | i==src.size()-1)) {

Maybe better code:

    if (src[i] == '"' && (i==0 || i==src.size()-1)) {

It appears that the current version in github has the &&, but not the ||.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/c350e772b314c8feb18aac4e54b859b740b4dcc9
