### ISSUE TITLE
faust2faustvst / arm64 compilation fail

### ISSUE THREAD

**Issue by ValCT** [grame-cncm/faust#727]
Hello,

I'm building a plugin meant to run on a raspberry pi 4 running Elk OS.

Running the faust2faustvst tool on the target machine results in the following errors:

`/usr/local/bin/faust2faustvst: line 182: [:=: expected unary operator`
`c++: error: unrecognized command line option '-mfpmath=sse'`
`c++: error: unrecognized command line option '-msse'`
`c++: error: unrecognized command line option '-msse2'`
`c++: error: unrecognized command line option '-msse3'`

I got rid of these by removing the corresponding flags in the faust2faustvst script:

66 `CXXFLAGS="-O3 -std=c++11 -march=native -ffast-math -ftree-vectorize"`

Compilation succeeds but I'm pretty sure that's not the right way to fix this...

Valentin

**Comment by sletz** [comment]
Should be fixed in https://github.com/grame-cncm/faust/commit/6fd3e4a018819ba097b45c6f0164c22bd2fa8f74.
