### ISSUE TITLE
pitchShift does not seem to work on macOS with -double

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#740]
Hi,
The code: (pitchShift.dsp):

```
import("stdfaust.lib");

pitchshifter = vgroup("Pitch Shifter", ef.transpose(
					hslider("window (samples)", 1000, 50, 10000, 1),
					hslider("xfade (samples)", 10, 1, 10000, 1),
					hslider("shift (semitones) ", 0, -12, +12, 0.1)
				  )
);

process = pitchshifter;
```

- macOS with -single: it works (at current HEAD, a1eb5a78453b8c63518823e7671a48fdb71e96c8)
- macOS with -double: I get a pop and silence (looks like NaNs)
- linux with -single or -double: it works (faust 2.40.0-1.1)

I'll do more experimentations and report

**Comment by sletz** [comment]
Which target?

**Comment by jcelerier** [comment]
On an intel mac, I pass "" as a triple
