### ISSUE TITLE
Exported VST/VSTi crashes FL Studio 20 on Win 10 64

### ISSUE THREAD

**Issue by agdsat134** [grame-cncm/faust#743]
Using FL Studio 20 on Windows 10 Pro 64-Bit:

After exporting to either Windows 32 or Windows 64 VST and VSTI, FL Studio will crash when I try to load any plugin written with the online IDE.

**Comment by sletz** [comment]
Better use the JUUCE export, or the [faust2juce](https://github.com/grame-cncm/faust/tree/master-dev/architecture/juce) tool.
