### ISSUE TITLE
Please replace all 'make' commands in Makefiles with $(MAKE)

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#75]
Some systems have several make utilities.

**Comment by sletz** [comment]
Can you prepare a pull request again master-dev branch ? Thanks.

**Comment by yurivict** [comment]
https://github.com/grame-cncm/faust/pull/108

**Comment by orlarey** [comment]
Unfortunately, $(MAKE) is not predefined in some systems we support (for instance macOS).

**Comment by yurivict** [comment]
How can all other gmake-based projects build when they all use ```$(MAKE)```?

**Comment by orlarey** [comment]
Merged in 397f68d37805d2a5218149eae0e9432a82b993a7
