### ISSUE TITLE
faust2cagtk claims it's Linux

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#763]
`faust2cagtk` claims that the target platform is Linux:

```sh
$  faust2cagtk -h
Usage: faust2cagtk [options] [Faust options] <file.dsp>
Target platform: Linux
Require: Jack
Compiles Faust programs to CoreAudio and GTK
```

my understanding is, that CoreAudio is a macOS *only* thing (and not available on Linux at all).

**Comment by sletz** [comment]
When possible can you better provide a fix as a PR, instead of opening an issue? Thanks.

**Comment by umlaeute** [comment]
sometimes, i'm not sure (e.g. *you* might have a setup that allows cross-compilation of CoreAudio/GTK on Linux to macOS)
