### ISSUE TITLE
faust2raqt fails to build (cannot find rtaudio headers)

### ISSUE THREAD

**Issue by umlaeute** [grame-cncm/faust#767]
```sh
$ faust2raqt freeverb.dsp 
freeverb.cpp:7344:10: fatal error: RtAudio.h: No such file or directory
 7344 | #include <RtAudio.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:454: freeverb.o] Error 1
```

`faust2raqt` assumes that it knows  the linker-flags, that the `<RtAudio.h>` headers are in the default search paths, and that no other special flags are required.
this might not be true.

e.g. on my Debian system is get:
```
$ pkg-config --cflags --libs rtaudio
-pthread -D__LINUX_ALSA__ -D__LINUX_PULSE__ -D__UNIX_JACK__ -D_REENTRANT -I/usr/include/rtaudio -lrtaudio
```

it would therefore be better to use `pkg-config` to determine the flags (if it is available).

a commit is on the way.

**Comment by sletz** [comment]
Better yes, thanks!
