### ISSUE TITLE
Demo colored_noise broken

### ISSUE THREAD

**Issue by 0xchase** [grame-cncm/faust#777]
Hello,

After copying and pasting the `colored_noise` demo into the faust IDE there is no output. The code to copy/paste is below for your convenience. (I copied and pasted some other bits to get it to compile in the IDE.)

```
ma = library("maths.lib");
ba = library("basics.lib");
fi = library("filters.lib");
os = library("oscillators.lib");
no = library("noises.lib");

declare name "Faust Noise Generator Library";
declare version "0.0";

noise = random / RANDMAX
with{
	mask = 4294967295; // 2^32-1
	random = +(12345) ~ *(1103515245) & mask; // "linear congruential"
	RANDMAX	= 2147483647.0; // = 2^31-1 = MAX_SIGNED_INT in 32 bits
};


colored_noise(N,alpha) = no.noise : fi.dcblocker : fi.spectral_tilt(N,fmin,bw,alpha) : *(uniNorm(alpha * 2)) : max(-1.0) : min(1.0)
with {
    fmin = 20.0;
    fmax = 20000.0;
    bw = fmax - fmin;

    uniNorm(alpha) = (a*exp(-alpha*b))+(c*exp(-alpha*d)) : pow(-1)
    with{
        a = ba.if(ma.signum(alpha) > 0, 1, 0.8016);
        b = ba.if(ma.signum(alpha) > 0, -4.28, -2.633);
        c = ba.if(ma.signum(alpha) > 0, 0, 0.1984);
        d = ba.if(ma.signum(alpha) > 0, 0, -0.7196);
    };
};

freq = hslider("freq[style:numerical]", -0.5, -1.0, 1.0, 0.001);

process = colored_noise(12, freq);
```

**Comment by sletz** [comment]
Working here in Chrome and Firefox. Possibly clear your cache.

**Comment by procedural-audio** [comment]
Hmmm it works on my Windows machine but not my M1 Mac Mini. It's definitely not the cache since it doesn't work locally either. I'll look into it more tonight.

**Comment by josmithiii** [comment]
It sounds fine on my M1 Mac using faust2caqt.

I've noticed Core Audio can go silent indefinitely after getting hit with NaNs from somewhere.
I usually reboot to fix, but sometimes it straightens out eventually on its own after the offending app is closed.

**Comment by josmithiii** [comment]
Also, the latest version in the Faust libraries does not use a mask (because it didn't help to guard against 64-bit ints), so you might try that:

```
	noise = random / RANDMAX
	with {
		random = +(seed) ~ *(1103515245); // "linear congruential"
	};	

```
