### ISSUE TITLE
Jack-0.125.0 doesn't have 'jack_midi_reset_buffer'

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#78]
I had to patch like this 's|jack_midi_reset_buffer|jack_midi_clear_buffer|' to make it build.
This function is either only in the older, or only in the newer versions of Jack.

Please correct!

**Comment by sletz** [comment]
This function is in jack2 starting from 1.19.11.

**Comment by yurivict** [comment]
1.9.11 is RC1 of Jack2.
The current versions are Jack1 0.125.0, and Jack2 1.9.10.
You need to add ifdefs to make sure it is available.

**Comment by sletz** [comment]
Prepare a PR , thanks.
