### ISSUE TITLE
feature request: allow to explicitly enable foreign functions with LLVM

### ISSUE THREAD

**Issue by jcelerier** [grame-cncm/faust#783]
Hi,

to give the context: I'm trying to see if the Guitarix plugs can work in ossia score . 
Some of them call some foreign functions implemented in C/C++ (basically data tables for valve simulation).

What would be great would be to have something in the API such as: 

    registerKnownForeignFunction("some_function");

to allow Faust to generate llvm bitcode knowing that "some_function" will be in the address space of the process which will be loading and linking the LLVM bitcode afterwards. 

I've tried looking at how to implement it like this: https://github.com/jcelerier/faust/commit/5b612e2ea12a989d07477b886bfa111fd26af02f but I'm getting crashes at compilation time so there is certainly a lot missing for it to work - if this is even possible?

Thanks !

**Comment by sletz** [comment]
Any crash log?

**Comment by jcelerier** [comment]
hmmm even with CMAKE_BUILD_TYPE=Debug and checking that libfaust.so has debug symbols I still can't seem to get symbols:

```
ASSERT : please report this message, the stack trace, and the failing DSP file to Faust developers (file: fir_to_fir.hh, line: 572, version: 2.44.5, options: -lang llvm 14.0.6 -es 1 -mcd 16 -double -ftz 0 -vec -lv 0 -vs 32 )
====== stack trace start ======
/usr/lib/libfaust.so.2(+0x286093) [0x7f8f41a86093]
/usr/lib/libfaust.so.2(+0x28505b) [0x7f8f41a8505b]
/usr/lib/libfaust.so.2(+0x35e78f) [0x7f8f41b5e78f]
/usr/lib/libfaust.so.2(+0x2b6ea2) [0x7f8f41ab6ea2]
/usr/lib/libfaust.so.2(+0x2bac5a) [0x7f8f41abac5a]
/usr/lib/libfaust.so.2(+0x2b6090) [0x7f8f41ab6090]
/usr/lib/libfaust.so.2(+0x2bb4db) [0x7f8f41abb4db]
/usr/lib/libfaust.so.2(+0x2b722a) [0x7f8f41ab722a]
/usr/lib/libfaust.so.2(+0x2bb1aa) [0x7f8f41abb1aa]
/usr/lib/libfaust.so.2(+0x2b821a) [0x7f8f41ab821a]
/usr/lib/libfaust.so.2(+0x2bb4db) [0x7f8f41abb4db]
/usr/lib/libfaust.so.2(+0x2b722a) [0x7f8f41ab722a]
/usr/lib/libfaust.so.2(+0x2bb1aa) [0x7f8f41abb1aa]
/usr/lib/libfaust.so.2(+0x2b821a) [0x7f8f41ab821a]
/usr/lib/libfaust.so.2(+0x2bb4db) [0x7f8f41abb4db]
/usr/lib/libfaust.so.2(+0x2b722a) [0x7f8f41ab722a]
/usr/lib/libfaust.so.2(+0x2bb4db) [0x7f8f41abb4db]
/usr/lib/libfaust.so.2(+0x2b722a) [0x7f8f41ab722a]
/usr/lib/libfaust.so.2(+0x348f35) [0x7f8f41b48f35]
/usr/lib/libfaust.so.2(+0x45a981) [0x7f8f41c5a981]
====== stack trace stop ======
```

**Comment by jcelerier** [comment]
It works at 38ab1bc42d8ea091d3e6915d2a6b419d06ced5da

**Comment by sletz** [comment]
- can we interact on slack or Discord?
- please send me the DSP
