### ISSUE TITLE
FaustSawtooth example compilation error: narrowing convertion

### ISSUE THREAD

**Issue by fausto78** [grame-cncm/faust#791]
Hi,
I'm quite new to cpp programming, so it probably should be my mistake...
In a freshly installed Espressif-IDE I can't get to recompile the FaustSawtooth example after having introduced the cpp compiled DSP and Codec files.
I followed step-by-step the tutorial on https://faustdoc.grame.fr/tutorials/esp32/#using-the-esp32-c-development-environment.

The console returns the following warning threated as an error:
C:/Espressif/frameworks/esp-idf-v4.4.2/workspace/hellofaust/main/FaustSawtooth.cpp:1389:32: error: narrowing conversion of '((esp32audio*)this)->esp32audio::fSampleRate' from 'int' to 'uint32_t' {aka 'unsigned int'} inside { } [-Werror=narrowing]
                 .sample_rate = fSampleRate

In /main/CMakeLists.txt I registered only the 3 .cpp files. I hope it's correct.

I also found a command to suppress this error, but, sorry, I don't know where to use it.

Many thanks in advance.
Fausto (it's my name.. When I heard of the Faust compiler I realized I couldn't miss it :)

**Comment by sletz** [comment]
You can probably solve it by adding an explicit cast at C:/Espressif/frameworks/esp-idf-v4.4.2/workspace/hellofaust/main/FaustSawtooth.cpp:1389. With is the exact line ?

Interaction on Faust Slack of Discord might help also: https://faust.grame.fr/community/help/

**Comment by sletz** [comment]
BTW: are you using Faust in this context https://www.denerg.polito.it/en/the_department/internal_structures/laboratories/laboratori_area_elettrica/maglab ?

**Comment by fausto78** [comment]
> BTW: are you using Faust in this context https://www.denerg.polito.it/en/the_department/internal_structures/laboratories/laboratori_area_elettrica/maglab ?

It would be great using it in my Lab, but also to build audio effect processors and synths.
Thanks for the suggestion, I'll try ASAP!

**Comment by fausto78** [comment]
> You can probably solve it by adding an explicit cast at C:/Espressif/frameworks/esp-idf-v4.4.2/workspace/hellofaust/main/FaustSawtooth.cpp:1389. With is the exact line ?
> 
> Interaction on Faust Slack of Discord might help also: https://faust.grame.fr/community/help/

Many thanks!! It worked and I learned a lot.
Ciao
Fausto

**Comment by sletz** [comment]
> Many thanks!! It worked and I learned a lot. Ciao Fausto

If your cast edit is in a Faust architecture file, part of the Faust distribution, I would be happy to fix that. Or you can possibly prepare a Pull Request.

**Comment by fausto78** [comment]
> If your cast edit is in a Faust architecture file, part of the Faust distribution, I would be happy to fix that. Or you can possibly prepare a Pull Request.

It is in the cpp compiled with Faust under Ubuntu (I needed to specify -AC101, since I'm testing the Audio Dev Kit) and put in the Espressif-IDE under Win11.

Please tell me if and how could I help best.

**Comment by sletz** [comment]
Can you send me the file?

**Comment by fausto78** [comment]
Here you can find the cpp file and the console rows with the warnings. I hope It's enough. I started again from a WM8978 example, since it's precisely the same.
Many thanks again!

[FaustSawtooth.zip](https://github.com/grame-cncm/faust/files/9427754/FaustSawtooth.zip)
[BuildConsole_LastRows.txt](https://github.com/grame-cncm/faust/files/9427756/BuildConsole_LastRows.txt)

**Comment by sletz** [comment]
Thanks is this `.sample_rate = uint32_t(fSampleRate)`,  fix correct?  Is yes then I can fix it here https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/audio/esp32-dsp.h

**Comment by fausto78** [comment]
Yes, it is correct!

**Comment by sletz** [comment]
Thanks, fixed in https://github.com/grame-cncm/faust/commit/ba61c20530e555cc78922a97a09f27726203856d
