### ISSUE TITLE
Faust2daisy not working on MacOS HomeBrew install

### ISSUE THREAD

**Issue by madskjeldgaard** [grame-cncm/faust#816]
Hi! 

I've got some trouble with `faust2daisy` not working on a Mac with a faust installation and it seems to be a path issue:

```
Makefile:13: ../../../libdaisy/core/Makefile: No such file or directory
make: *** No rule to make target `../../../libdaisy/core/Makefile'.  Stop.
````

The value of ```$FAUSTARCH``` is  

```
/opt/homebrew/Cellar/faust/2.50.6/share/faust
```

**Comment by sletz** [comment]
I guess you'll have to install Daisy related stuff right ?
