### ISSUE TITLE
Documentation Requirement: Verified Step-by-Step Examples for Running DSP

### ISSUE THREAD

**Issue by Asher-** [grame-cncm/faust#824]
It is surprisingly frustrating to piece together which forms of output are suited to which hardware, and exactly how to combine that code. For example, there is no "mac os" option; I assume that audiokit is the preferred target, but this is a set of 3rd party libraries, and no explanation is given how to combine the dsp code with a default audiokit project. I can figure this out (and will plan to add details once I do), but there is no question that this is a barrier to entry for most people. 

In a similar vein, the VST target does not seem to document its dependencies (apparently VST SDK 2, which is no longer available), and the faustvst target does not clarify its relation to the vst target. 

My suggestion:

* There should be a platform list that describes options that can be deployed to the given platform, including suggestions as to which options are preferred. 
* Any target should provide documentation to compile a working example on any supported platform. This should be a one-stop solution to demoing a compiled example.

I hope to help contribute to this, so I am primarily posting this here to make note of a gaping hole in the Faust distribution.

**Comment by sletz** [comment]
See https://faustdoc.grame.fr/manual/tools/

**Comment by Asher-** [comment]
That doesn't match what I described or resolve any of the issues.

**Comment by sletz** [comment]
Better use https://faustide.grame.fr (see https://github.com/grame-cncm/faustide for some documentation)

**Comment by Asher-** [comment]
How will that help me get an instance running on mac os?

**Comment by sletz** [comment]
- https://faustdoc.grame.fr/manual/tools/ describes part of the information you need (platform, package requirement), and some more explanations added like a few hours ago
- if you want to improve it, please contribute. This project is open-source and contributions are welcomed. 
- but behaving the way you do is probably no the best way to start a proper contribution

**Comment by josmithiii** [comment]
Greetings - it sounds like you want to make a VST3 plugin using Faust.
Here is how I do it: https://ccrma.stanford.edu/courses/320c-spring-2022/assignments/15/

**Comment by Asher-** [comment]
Thanks @josmithiii!

@sletz As I made clear, I am asking these questions in light of work toward contributing. I'm not sure what behavior you are referring to. Closing the issue without addressing the issue was patronizing and rude. Particularly when the question was asked in the context of figuring out how to start contributing. The URL you provide does not in any way line up with the information that I asked about. It documents the --help output for the tools, which is already readily available. As I made clear, the issue concerns, for example, how to connect the code output, for example in the example of audiokit, with audiokit code. Similarly with the non-working VST tool. It seems to me that your response is the one embodying a behavior issue.

**Comment by sletz** [comment]
The I suggest  opening a specific issue for audio kit, to make is more clear, and I've re-opened the VST one.

**Comment by Asher-** [comment]
I will do that as well, but the issue is so much bigger than that. The project is a MESS. Which is quite surprising given how clean the code is (even if stylistically from the 90s).

**Comment by sletz** [comment]
> The project is a MESS.

You mean the code in https://github.com/grame-cncm/faust/tree/master-dev/architecture/audiokit ? Well this was something done as complete blind developed code. I am happy to help improving it. See also https://faustdoc.grame.fr/manual/architectures/ as generated explanation on architecture files.
