### ISSUE TITLE
Tests Broken

### ISSUE THREAD

**Issue by Asher-** [grame-cncm/faust#826]
∴ ./run_test_cpp.sh 
./run_test_cpp.sh: line 20: tempfile: command not found
ERROR : no files specified; for help type "faust --help"

Darwin Zero.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

**Comment by sletz** [comment]
It is an old and now uneeded file. Will be removed.

**Comment by Asher-** [comment]
Is there documentation about how to run tests?
