### ISSUE TITLE
C++11 vs 17/21

### ISSUE THREAD

**Issue by Asher-** [grame-cncm/faust#827]
Is there a reason to be using archaic c++ standards?

Are there target compilers that are still not capable of at least c++17?

**Comment by sletz** [comment]
Possibly yes on embedded platforms for instance. Which part of the the code are you locking at?
BTW: this does not seems to be a real "issue" right ? So this kind of discussion can possibly move on Faust Slack or Discord to avoid filling the issues with them, thanks.

**Comment by Asher-** [comment]
OK. How do I join slack? When I attempted yesterday it wanted me to create a login but then said I had to have emails at one of two domains in order to do so (which I obviously don't).

**Comment by sletz** [comment]
I can send an invite. On which mail ?

**Comment by Asher-** [comment]
asher@strong.ai please
