### ISSUE TITLE
Teensy 4.1: crash on passing invalid parameter path

### ISSUE THREAD

**Issue by hatchjaw** [grame-cncm/faust#834]
For a faust program with, e.g.

```faust
gain = hslider("gain", 1, 0, 1, .01);
```
then from a Teensy sketch calling

```c++
g.setParamValue("gain?", .5);
```

Teensy reboots and produces a crash report:
```
CrashReport:
  A problem occurred at (system time) 16:14:20
  Code was executing from address 0x14C0C
  CFSR: 82
	(DACCVIOL) Data Access Violation
	(MMARVALID) Accessed Address: 0x2 (nullptr)
	  Check code at 0x14C0C - very likely a bug!
	  Run "addr2line -e mysketch.ino.elf 0x14C0C" for filename & line number.
  Temperature inside the chip was 35.92 °C
  Startup CPU clock speed is 600MHz
  Reboot was caused by auto reboot after fault or bad interrupt detected
```

Running `addr2line` returns Teensy's `Print.cpp`, but not the line number. 

This appears to be an issue with the call to `fprintf` in `get`/`setParamValue()`. In this [ancient thread](https://forum.pjrc.com/threads/24730-fprintf-with-Teensy3-1-hangs) from the PJRC forum, Paul Stoffregen strongly advises using `Serial.printf` instead. Likely this still applies.

Minimal example to reproduce attached.
[param-crash-test.tar.gz](https://github.com/grame-cncm/faust/files/10098614/param-crash-test.tar.gz)

Thanks!

**Comment by sletz** [comment]
The problematic code is there https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/gui/MapUI.h#L159. So we may have to do something like:

```
#ifdef TEENSY_DRIVER 
Serial.printf(...) // to complete
#else 
fprintf(stderr, "ERROR : setParamValue '%s' not found\n", str.c_str());
#endif
```

Can you possible try in this direction  ?

**Comment by hatchjaw** [comment]
Thanks. I was thinking it might be preferable to inherit from MapUI (e.g. TeensyMapUI) and override `get`/`setParamValue`, but I see that if MIDICTRL is defined there are a large number of further calls to fprintf, inserted from `SimpleParser`, `dsp-adapter`, etc. 

So, I've submitted a PR that uses the preprocessor to substitute `fprintf` with `Serial.printf`.

**Comment by sletz** [comment]
Event better, thanks for the PR.
