### ISSUE TITLE
OSC with  alsaconsole app

### ISSUE THREAD

**Issue by bezlikijshlejf** [grame-cncm/faust#84]
Hi, sorry my english
i compile alsa-console app with osc support
run it -> send "hello" string message and catch echo, all working
i kill app
run it -> send "hello" string message and ... nothing... (any get/set messages, hello) .. pure silence
what i do not understand???
when recompile white new widget names everything working again

thanks for any help

**Comment by sletz** [comment]
Cannot reproduce the problem here : can you **exactly** describe which command you are using ?

**Comment by bezlikijshlejf** [comment]
run ./mysynth and use oscsend/oscdump from liblo-tools
I "solved" problem - autofill .mysynthrc file with arbitrary content, but with the same number of rows as the number of parameters. At the start my app just `stateRecall` all osc parameters and control works.
But i had another problem - big(1sec+) send-receive delay. I use thousands of osc-parameters. Is mycase - `realworld` case?

thanks

**Comment by sletz** [comment]
If you use "thousands of osc parameters." then yes you may have delays...
