### ISSUE TITLE
2.54.9: Compiling sound2faust with static libsndfile is a problem for distributions

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#840]
Since https://github.com/grame-cncm/faust/commit/d1fe8570d2d77839359c0cd6c13bb4abc0c7efb5 sound2faust wants to be compiled with libsndfile.a, but this breaks distribution packaging, which relies on linking against the shared library.

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/ca013457c9d52bdc0101c9d31fc3621fe3e1b103.
