### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [grame-cncm/faust#842]
Would you like to wrap any pointers with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [AudioFaust](https://github.com/grame-cncm/faust/blob/6c7e7cd10c1bc99203bf960f42751e8cef939d8e/architecture/teensy/teensy.cpp#L99)
- [InvZTAZMSolver](https://github.com/grame-cncm/faust/blob/66cdb528642fdf3d607fec1b7ea7f386d7b709a4/tools/physicalModeling/mesh2faust/vega/libraries/sparseSolver/invZTAZMSolver.cpp#L32)
- [time_bench_real](https://github.com/grame-cncm/faust/blob/eaff6253a1b2dde0accf0c208b3bdac452b5941f/architecture/faust/dsp/dsp-bench.h#L176)

**Comment by elfring** [comment]
:thought_balloon: Would you like to take [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") better into account?

**Comment by sletz** [comment]
This kind of change is huge and possibly invasive. Not the more urgent thing to do.
