### ISSUE TITLE
hazardous sed command

### ISSUE THREAD

**Issue by agraef** [grame-cncm/faust#852]
Hi @dfober @sletz, this one looks dubious to me:

https://github.com/grame-cncm/faust/blob/be04b2fd92b0fca1a152cd3b65edb37ea0967b39/build/Make.llvm.static#L31

I ran into this gem while building the static lib target (doing some work on pd-faustgen2). The underlying cause is that I'm using Homebrew in my build environment which has a libz, and for some reason `llvm-config --system-libs` (which is the value of `$(SYSLIBS)`) gives `-lm -lz /opt/homebrew/lib/libzstd.a -lcurses -lxml2`, which is bad because slashes are used as delimiters in the sed command there.

Yeah, so you could shrug it off as a LLVM or Homebrew bug, or my setup. ;-) But just interpolating the output into a sed expression delimited with slashes is a bit hazardous, because you simply don't know  what `llvm-config --system-libs` might give you; there might *well* be absolute paths to static libs and thus slashes in there, in which case this line breaks down.

I'd suggest changing the slashes to a question mark or something else that's not likely to occur in a filename, then it should be fine. Might also be worth checking other instances of sed commands elsewhere in the (C)Makefiles, just to make sure...

Have a nice Sunday! :) Yeah, I'm hacking on Sundays, semester is still on over here, so not enough time during the week. ;-)

**Comment by sletz** [comment]
Hi @agraef what concrete fix do you suggest?

**Comment by agraef** [comment]
Quoting myself:
> I'd suggest changing the slashes to a question mark or something else that's not likely to occur in a filename, then it should be fine.

In this case something like this (using pipe symbols in lieu of "/"):
~~~
sed -e "s|^SYSTEMLIBS..*|SYSTEMLIBS=\"$(SYSLIBS)\"|" $(CONFIG) > __tmp__ 
~~~

**Comment by sletz** [comment]
Dine https://github.com/grame-cncm/faust/commit/fcc51c12184b6e07ebdfc6fd51427ad1af498ac2 thanks !
