### ISSUE TITLE
Prominent link to GitHub from website

### ISSUE THREAD

**Issue by sedubois** [grame-cncm/faust#86]
I just discovered about this project through a tweet on twitter linking to the website, and I immediately wanted to discover the GitHub project to check the most obvious things, such as since when it is active, is it still actively developed, how many collaborators are there, how many people starred the project, and I also wanted to star the project myself in order to bookmark it, etc etc.

However, in contradiction with this very first expectation of mine, interestingly the GitHub project isn't linked anywhere (at least that I saw after a first browse across the website). It is only mentioned in some `git clone` commands, and so to access it I just googled "github faust". 

I think it would make sense to add a very prominent "GitHub" link to the website navigation headers, similarly as to what is done on basically the majority of other websites about a modern open-source library.

**Comment by sletz** [comment]
Done, thanks.
