### ISSUE TITLE
Unneccessary fatal error in generated LV2 plugins when LV2 host doesn't support URID

### ISSUE THREAD

**Issue by felakuti4life** [grame-cncm/faust#914]
Hello,

Repro for this one is pretty easy:
1. Generate a plugin using the faust2lv2 command with any basic audio effect,
2.  copy the emitted MyFilter.lv2 to your lv2 plugin search path (typically /usr/lib/lv2)
3. run `lv2apply -i AnySignal.wav -o Gen.wav https://faustlv2.bitbucket.io/MyFilter` (with MyFilter swapped with whatever your filter's URI is, which can be checked with lv2ls)
4. Observe the following issue:
```
https://faustlv2.bitbucket.io/MyFilter: host doesn't support urid:map, giving up
16523 Segmentation fault
```

root issue is [here](https://github.com/grame-cncm/faust/blob/master-dev/architecture/lv2.cpp#L1631)- if the host doesn't support URID mapping, we can't derive a URID for MIDI events, so we presume we can't run the lv2 plugin and return a nullptr. That's not a blocker for the plugin as-is to run though- the MIDI URID would stay at -1, and we just wouldn't receive MIDI events.

**Comment by sletz** [comment]
So fixed by https://github.com/grame-cncm/faust/pull/915 right ?

**Comment by felakuti4life** [comment]
Yup! Sorry, I referenced 914 in that PR but didn't cross reference here.
