### ISSUE TITLE
Unable to use faust2au with macOS x86_64 on version  2.60.3

### ISSUE THREAD

**Issue by shakfu** [grame-cncm/faust#917]
Having installed faust 2.60.4 via the provided binaries to `$HOME/.opt/faust` and having set `FAUST_INSTALL` to the same directory and PATH to `$HOME/.opt/faust/bin`, I tried to compile a macOS audiounit plugin via one of the simpler examples (`examples/generators/osc.dsp`):

```bash
faust2au osc.dsp
```
This generated an Xcode project but produced errors during compilation which had to be fixed with the following steps:

1. Add `$(HOME)/.opt/faust/include` to `HEADER_SEARCH_PATH`
2. Enable "C++11 [-std=c++11]" in `C++ Language Dialect`
3. Cast `int` -> `unsigned int` in all places giving the error  "Non-constant-expression cannot be narrowed from type 'int' to 'AudioUnitParameterID' (aka 'unsigned int') in initializer list"

After the above fixes, the compilation proceeded successfully and generated `FaustAU.component`.

Unfortunately after placing this audiounit in `~/Library/Audio/Plugins/Components` or `/Library/Audio/Plugins/Components` it was not recognized by any of my DAWs (Ableton Live 11.3.3 or Reaper 6.80).

I finally checked it with a plugin validaton tool, [pluginval](https://github.com/Tracktion/pluginval) initially with strictness level 5 or finally with the lowest level 1, but it was not validated with the following error:

```
Started validating: $HOME/Library/Audio/Plug-Ins/Components/FaustAU.component
Started validating: $HOME/Library/Audio/Plug-Ins/Components/FaustAU.component
Random seed: 0x7c1a14
Validation started
Strictness level: 1
-----------------------------------------------------------------
Starting tests in: pluginval / Scan for plugins located in: $HOME/Library/Audio/Plug-Ins/Components/FaustAU.component...
Num plugins found: 0
!!! Test 1 failed: No types found. This usually means the plugin binary is missing or damaged, an incompatible format or that it is an AU that isn't found by macOS so can't be created.
FAILED!!  1 test failed, out of a total of 1
*** FAILED


Finished validating: $HOME/Library/Audio/Plug-Ins/Components/FaustAU.component
*** FAILED WITH EXIT CODE: 1

Finished batch validation
```

Any help on how to resolve this would be much appreciated.

**Comment by sletz** [comment]
`faust2au` is no more maintained, better use [faust2juce ](https://github.com/grame-cncm/faust/tree/master-dev/architecture/juce) and compile an AU from there.

**Comment by shakfu** [comment]
@sletz thanks, that's interesting. I remember it working previously. I'll try the faust2juce translator then.

**Comment by shakfu** [comment]
@sletz 

I suggest not to remove `faust2au` in case someone can resolve the remaining issues.
