### ISSUE TITLE
Make fails on Mac OS 13.5

### ISSUE THREAD

**Issue by cheesymoo** [grame-cncm/faust#930]
- Clone the faust repo
- Run `make`
- Receive this output / errors:
```
if test -d .git; then git submodule update --init --recursive; fi
/Volumes/XcodeNovo/Xcode.app/Contents/Developer/usr/bin/make -C build cmake BACKENDS=regular.cmake TARGETS=regular.cmake
cd faustdir &&  -C ../backends/regular.cmake -C ../targets/regular.cmake -DCMAKE_BUILD_TYPE=Release "-DWORKLET=off" -DINCLUDE_LLVM=OFF -DUSE_LLVM_CONFIG=ON -DLLVM_PACKAGE_VERSION= -DLLVM_LIBS="" -DLLVM_LIB_DIR="" -DLLVM_INCLUDE_DIRS="" -DLLVM_DEFINITIONS="" -DLLVM_LD_FLAGS=""  -DLIBSDIR=lib -DBUILD_HTTP_STATIC=OFF -G 'Unix Makefiles' ..
/bin/sh: -C: command not found
make[1]: *** [cmake] Error 127
make: *** [compiler] Error 2
```

Part of the output `cd faustdir && -C` looks problematic, shouldn't there be a command before the `-C` flag?

**Comment by cheesymoo** [comment]
Installed cmake 3.26.4

**Comment by cheesymoo** [comment]
Note, `cmake` is insufficient, user must also install `pkg-config`

**Comment by pajama** [comment]
I have a newer version of cmake and pkg-config installed. getting:

> make -C build install DESTDIR= PREFIX=/usr/local
> if test -d ../.git; then git submodule update --init; fi
> cd faustdir &&  .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release "-DWORKLET=off"
> /bin/sh: ..: command not found
> make[1]: *** [install] Error 127
> make: *** [install] Error 2
