### ISSUE TITLE
making ancient instrument models

### ISSUE THREAD

**Issue by Reaper10** [grame-cncm/faust#942]
I have a interest in making ancient instrument models. 
string instrument 

1. [Talharpa](https://en.wikipedia.org/wiki/Talharpa)
![1024px-Talharpa,_by_Charlie_Bynum,_Silver_Spoon_Music,_NL_2014](https://github.com/grame-cncm/faust/assets/8137561/a0d85850-f6a1-4ab8-ad22-a2bc4c36032b)
[Talharpa videos](https://www.youtube.com/results?search_query=Talharpa)

2. [Nyckelharpa](https://en.wikipedia.org/wiki/Nyckelharpa)
![Nyckelharpa_0930_(cropped)](https://github.com/grame-cncm/faust/assets/8137561/2e6efc86-99a5-4093-81a1-d049f6839d30)
[video 1](https://www.youtube.com/results?search_query=Nyckelharpa) [video 2](https://www.youtube.com/watch?v=Vdq1LA-PKRw)

3.  [Hurdy gurdy](https://en.wikipedia.org/wiki/Hurdy-gurdy)
![Louvet_Drehleier](https://github.com/grame-cncm/faust/assets/8137561/a4fbd8f4-dfab-429a-addc-f61aeb569e07)
[Video 1](https://www.youtube.com/watch?v=gYJg9cLk1us) [video 2](https://www.youtube.com/watch?v=utLXgOnIwdo) [video 3](https://www.youtube.com/watch?v=_7PIHcCqbCs)

4. [Rebec ](https://en.wikipedia.org/wiki/Rebec)
![rebec-viking-age-music-musical-instrument-hedeby-scandinavia](https://github.com/grame-cncm/faust/assets/8137561/fb95c01d-4c20-4073-a6f2-d744fd70d27f)
[rebec instrument videos](https://www.youtube.com/results?search_query=rebec+instrument)
my thought is that it could be great to make a models for the ancient instruments. 

I think you can use some of the work already done but I'm not sure those i'm not a programmer 

**the questions** 

1. would you have to make a boody
2. would you need to make a new string type drone strings
3. would you need a wheel

**Comment by sletz** [comment]
This is not Faust compiler issue, is still needed, should be moved in https://github.com/grame-cncm/faustlibraries.
