### ISSUE TITLE
basics.lib : 2124 : ERROR : syntax error, unexpected ROUND

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/faust#950]
Some examples from https://faustcloud.grame.fr/doc/examples/index.html#violinmidi , for example fourSourcesToOcto, fail with this error:
```
$ faust2jaqt fourSourcesToOcto.dsp 
basics.lib : 2124 : ERROR : syntax error, unexpected ROUND
```

Version: 2.68.1
FreeBSD 13.2

**Comment by sletz** [comment]
Round is a missing primitive that was recently added. So probably a library synchronisation issue.
