### ISSUE TITLE
License information in the Csound generated C++ source file is not correct

### ISSUE THREAD

**Issue by gogins** [grame-cncm/faust#96]
[blowBottle_linux_csound-64bits.cpp.txt](https://github.com/grame-cncm/faust/files/1499861/blowBottle_linux_csound-64bits.cpp.txt)

At the top of a generated C++ source code file for a Csound plugin opcode, it says:

```
 IMPORTANT NOTE : this file contains two clearly delimited sections :
 the ARCHITECTURE section (in two parts) and the USER section. Each section
 is governed by its own copyright and license. Please check individually
 each section for license and copyright information.
```
However, this statement is not correct.

The part about the ARCHITECTURE section is correct, but the part about the USER section is not correct. There is, in fact, no copyright or license information in the generated USER section. This means that that section of the file is in the public domain. If that is the intention, the wording should be changed. If that is not the intention, an appropriate license should be provided. 

If the intention is that the user provide their own license, that should be clearly indicated in the initial statement.

**Comment by sletz** [comment]
The original template file is here : https://github.com/grame-cncm/faust/blob/master-dev/architecture/csound.cpp

Can you possibly correct it an do a Pull Request (again master-dev branch) ? Thanks.
