### ISSUE TITLE
Compilation assertion failure using waveform primitive with LLVM

### ISSUE THREAD

**Issue by DBraun** [grame-cncm/faust#996]
**Tested on Windows with Faust 2.70.4.**

This code compiles with LLVM.
```faust
process = rdtable(waveform{1,2,3,4},1)+1;
```
This code errors with LLVM.
```faust
process = rdtable(waveform{1,2,3,4},0)+1;
```
The assertion error is here: https://github.com/grame-cncm/faust/blob/de3ee552fcb26a10c4030828ffa3794ed61107c5/compiler/generator/llvm/llvm_instructions.hh#L1370

**Comment by sletz** [comment]
Fixed in https://github.com/grame-cncm/faust/commit/6201d6781ef3ae0cd5a2c0f6d84c3ebc52cc946b.
